### ISSUE TITLE
OVH cluster scale up plan

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#1021]
Currently we can fit about 40 user pods onto the two nodes in the OVH cluster. Work on making the cluster auto-scaling is under way. See #1020 for some plots on usage.

What should be the next step towards scaling up to 100 concurrent users?

My suggestion would be to add 3 or 4 more nodes and then we scale up the traffic fraction in a few steps (40, 60, 80, 100) to see how things work/break. In parallel we can work on something like I suggested [in gitter](https://gitter.im/jupyterhub/mybinder.org-deploy?at=5cffac7f6fc5846bab9d3c0f) to allow a cluster to advertise its size and available slots.

Does that sound like a good plan?

cc @yuvipanda @mael-le-gal

**Comment by mael-le-gal** [comment]
> to see how things **work**/~break~ " 😛 

All good for me, I can add 3 more nodes for you.

Should I add them step by step or all in one ?

**Comment by betatim** [comment]
I'd add them all in one go, I can't think of a reason that would break something.

**Comment by choldgraf** [comment]
Can we plan a blog post for when we scale it up? I can spend some time on a draft this week if that helps

**Comment by betatim** [comment]
Blog post: yes please! @jagwar mentioned OVH wanted to post one as well so looping them in for coordination (or deciding that we don't need to coordinate). I think once we have good number of pods running on the second cluster we should announce.

**Comment by mael-le-gal** [comment]
@choldgraf @betatim on our side I started writting the draft for the ovh blog post yesterday. I think it will be finished at the end of the week but after that there is a validation process to comply before the article can be officially release on the ovh blog.

**Comment by jqueguiner** [comment]
@mael-le-gal  : validtion can be done in 1 day

**Comment by mael-le-gal** [comment]
@betatim new nodes are here :

```
$ kubectl get nodes
NAME                                        STATUS   ROLES    AGE    VERSION
fifth-node                                  Ready    <none>   5m     v1.11.9
fourth-node                                 Ready    <none>   19m    v1.11.9
node-a031e240-a864-4a1a-87ff-55bdd6ec7cb6   Ready    <none>   225d   v1.11.9
secondary-node                              Ready    <none>   7d     v1.11.9
third-node                                  Ready    <none>   38m    v1.11.9
```

**Comment by betatim** [comment]
OVH is now at 20% of all traffic. Let's bump it up in a few hours if everything looks good.

ref #1024 (such a cool PR number...)

**Comment by betatim** [comment]
There is another repo now showing the same problem with pulling image layers:
```
  Normal   Created    2m                kubelet, secondary-node  Created container
  Normal   Started    2m                kubelet, secondary-node  Started container
  Normal   Pulling    1m (x3 over 2m)   kubelet, secondary-node  pulling image "binder-registry.mybinder.ovh/binder-ovh/r2d-f18835fd-5c3f2e5151ce047bac3a0f33c1446304-e68675:b90d1c9c85df0567615dbac4db5a4633b0bb7003"
  Warning  Failed     48s (x3 over 2m)  kubelet, secondary-node  Failed to pull image "binder-registry.mybinder.ovh/binder-ovh/r2d-f18835fd-5c3f2e5151ce047bac3a0f33c1446304-e68675:b90d1c9c85df0567615dbac4db5a4633b0bb7003": rpc error: code = Unknown desc = filesystem layer verification failed for digest sha256:e9c30664b4fd7dae5f48f410f701b31afae59f1811c568e6dbb46e0082f6954c
  Warning  Failed     48s (x3 over 2m)  kubelet, secondary-node  Error: ErrImagePull
  Normal   BackOff    21s (x4 over 2m)  kubelet, secondary-node  Back-off pulling image "binder-registry.mybinder.ovh/binder-ovh/r2d-f18835fd-5c3f2e5151ce047bac3a0f33c1446304-e68675:b90d1c9c85df0567615dbac4db5a4633b0bb7003"
  Warning  Failed     21s (x4 over 2m)  kubelet, secondary-node  Error: ImagePullBackOff
```

this is for https://gist.github.com/Chilipp/5c3f2e5151ce047bac3a0f33c1446304.git

**Comment by mael-le-gal** [comment]
I deleted the image from the ovh repository but now it seems to have other problems while compiling (same erreur on ovh and gke)

**Comment by betatim** [comment]
As long the error is about the build I don't think there is much we can do. OVH seems to be running smoothly so far. If someone feels like it and has time to keep an eye on things we could bump up the traffic to it again I think.

**Comment by choldgraf** [comment]
Draft for a federation announcement: https://hackmd.io/GfsRByQ1TBCue74RM8Pcfw

This is just a first take, so please do make edits, comments, etc.

OVH folks it'd be helpful to see what kind of release you are all putting together as well, we'd be happy to coordinate the messaging etc a little bit. In addition, let us know if there's something in particular we can put into our blog post that will make it more useful to you all :-)

**Comment by jagwar** [comment]
Awesome, today we are away from the office (meetup time), but we will share it with you monday.

**Comment by consideRatio** [comment]
Wow great work on this! :D @mael-le-gal @jagwar @jqueguiner @betatim @choldgraf and all others involved! :heart: :tada:

**Comment by yuvipanda** [comment]
This is super awesome :)

I'm curious - are the OVH nodes SSD backed? That massively changes performance of docker pulls...

**Comment by jagwar** [comment]
Yes on our side we are using c2-15 flavor (using SSD).  @mael-le-gal isn't at the office today. We will share the draft tomorrow.
