### ISSUE TITLE
Deploy to all production clusters, then test them

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#1023]
Currently we deploy to GKE, then test GKE, then deploy to OVH, then test OVH.

Sometimes the test of GKE fails (for no good reason) and we end up not deploying to OVH.

I think it would be good to first do the two deploys and then test both of them. This way we keep the two clusters more consistent. If someone else also thinks this is a good idea/would make our life easier start a PR :)

This change would be in `.travis.yml` and a good way to learn a bit more about how the automatic deploy setup works.

**Comment by henchc** [comment]
This had been merged! https://github.com/jupyterhub/mybinder.org-deploy/pull/1072
