### ISSUE TITLE
404s on mybinder.org return a stack trace

### ISSUE THREAD

**Issue by jtpio** [jupyterhub/mybinder.org-deploy#1041]
Going to https://mybinder.org/test returns a 404 with the following:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1676, in _execute
    result = self.prepare()
  File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 2431, in prepare
    raise HTTPError(self._status_code)
tornado.web.HTTPError: HTTP 404: Not Found
```

**Comment by betatim** [comment]
Thanks for reporting! Do you want to take a stab at fixing this?

The MVP of a fix is to set https://github.com/jupyterhub/mybinder.org-deploy/blob/master/images/federation-redirect/app.py#L170 to `False`. A slightly longer more involved fix is to add a custom error page template (maybe copied from BinderHub).

**Comment by jtpio** [comment]
Sure, will have a look in the next few days.

Was there a particular reason for leaving `debug=True`? I suppose to make it more convenient to debug in the early days of the federation?

Otherwise yes I agree adding a page template for errors would be good. This one from BinderHub for example: https://github.com/jupyterhub/binderhub/blob/master/binderhub/templates/error.html

**Comment by betatim** [comment]
Leaving `debug=True` in was a mistake :) 👍  to the template.
