### ISSUE TITLE
Configure ingress pods to reschedule themselves away from cordoned nodes

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#1048]
It has happened a few times now that we cordon nodes and end up with mybinder.org not being reachable because all ingress pods are on a cordoned node. Because of how the ingress stuff is setup ingress pods that are on a cordoned node are considered "unhealthy" and removed from the load balancer rotation.

We should investigate configuring the ingress pods so that they ask to be rescheduled if they find themselves on a cordoned node.

**Comment by yuvipanda** [comment]
ingress and other infra stuff runs in the core nodes now! \o/
