### ISSUE TITLE
Split up / re-format README

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#105]
Current README is a mix of multiple bits of docs:

1. An actual README, that just tells us what this repo is and what it is used for
2. Deployment instructions, but maybe not 100% complete (@betatim had suggestions for example)
3. Some form of #11 but not enough.

We should split this up into multiple pages that can then grow independently.

**Comment by willingc** [comment]
Good plan @yuvipanda. Thanks for the heads up. Enjoy your trip too.

**Comment by willingc** [comment]
I'll take a first pass at this later this week now that the SRE guide is live.

**Comment by choldgraf** [comment]
Our README is nice and short now :-) closing!
