### ISSUE TITLE
Remove 100 concurrent users limit for workshop

### ISSUE THREAD

**Issue by anpaz-msft** [jupyterhub/mybinder.org-deploy#1062]
Hi,

We would like to use Binder on a workshop today (6/27/2019) about quantum computing; the workshop became very popular and now we're expecting about 200+ people. Any chance we can get over the 100 users limitation for just today?
This will be the repo we'll be using: https://github.com/msr-quarc/intern-workshop-2019

Thanks!

**Comment by betatim** [comment]
Closing this as I think we found a good solution on twitter: https://twitter.com/cgranade/status/1144310102049955840
