### ISSUE TITLE
Modify gcloud commands for creating clusters

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#1098]
We should update our SRE guide (and upstream docs) to use `gcloud container clusters create NAME --enable-ip-alias ...` (the last flag is the key) when creating clusters.

This will give you a https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips cluster. This has been the default until now but there is a change coming up in the `gcloud` CLI tool that will make "routes based" clusters the default. I assume we want to stick with VPC native clusters. This is also where the gcloud tool maintainers want to get (back) to as default.

**Comment by yuvipanda** [comment]
We terraform everything now! https://github.com/jupyterhub/mybinder.org-deploy/tree/master/terraform
