### ISSUE TITLE
GESIS Binder events to StackDriver

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/mybinder.org-deploy#1099]
Hi, once @yuvipanda asked if we are open to publish GESIS Binder events to archive.analytics.mybinder.org (https://discourse.jupyter.org/t/ann-a-new-binder-gallery/1204/5). We would like to do that :)

For that reason I just created a PR on our repo (https://github.com/gesiscss/orc/pull/1). And I hopefully made all required changes based on https://github.com/jupyterhub/mybinder.org-deploy/issues/986 and https://github.com/jupyterhub/mybinder.org-deploy/pull/1011. The only missing part is `serviceAccountKey` secret which we need from you.

Are you still interested in receiving GESIS binder events into your StackDriver? If yes, could we proceed checking the changes I made on our repo (https://github.com/gesiscss/orc/pull/1)?

**Comment by betatim** [comment]
I sent a key to @bitnik for the service account `gesis-events-stackdriver-write@binder-prod.iam.gserviceaccount.com`

**Comment by bitnik** [comment]
Service account is added into config and we just checked with Tim and there are gesis binder events in stackdriver now :)
