### ISSUE TITLE
Upgrading k8s version on OVH cluster

### ISSUE THREAD

**Issue by mael-le-gal** [jupyterhub/mybinder.org-deploy#1160]
The current `k8s` version of the OVH cluster is `1.11.x` and we need to upgrade to at least `1.13.x` (bug fixes + more security).

It's the first time we will do an upgrade on this custer. I will switch the ovh traffic to 0% until the upgrade is done. And switch it on again if everything is allright.

**Comment by choldgraf** [comment]
I just merged your PR, good luck with the upgrade!

**Comment by choldgraf** [comment]
It looks like Travis failed on the deploy because of some errors in the ovh step...is the upgrade already in progress?

I’m not going to revert the PR, because since the step that is breaking is OVH, I don’t want to send *more* traffic to it.

**Comment by mael-le-gal** [comment]
I think this is again the error of deployment that is linked to the version of k8s. If we are sure that all the traffic is away from ovh we can stay like this. The time for me to upgrade the cluster.

**Comment by choldgraf** [comment]
Ok cool, I think the redirector should be working because it deploys before it tests, and Travis failed on the test. Would be good to upgrade and confirm quickly though! 😊

**Comment by choldgraf** [comment]
@mael-le-gal I'm seeing a little bit of instability in the OVH cluster since switching back on the traffic (here's the grafana, second yellow line is switching back on traffic):

![image](https://user-images.githubusercontent.com/1839645/64986789-a9556100-d87c-11e9-8982-8bdbaaf03961.png)


is that expected in the short-term?

**Comment by choldgraf** [comment]
Just a note that launches have been happy for the last several hours, so I'm gonna close this one, thanks @mael-le-gal for upgrading!
