### ISSUE TITLE
Shiny app not deploying

### ISSUE THREAD

**Issue by pablobernabeu** [jupyterhub/mybinder.org-deploy#1175]
I would massively appreciate any help about the reasons why my Shiny app isn't deploying in the Shiny interface of Binder. It does deploy through Binder's RStudio. The URL I'm using is:

https://mybinder.org/v2/gh/pablobernabeu/Modality-switch-effects-emerge-early-and-increase-throughout-conceptual-processing/master?urlpath=shiny/ERPs/Analyses%20of%20ERPs%20averaged%20across%20trials/Shiny%20app/

**Comment by choldgraf** [comment]
Hi @pablobernabeu - you might want to ask around on either the Binder gitter channel (gitter.im/jupyterhub/binder) or the community forums (discourse.jupyter.org). This repository is meant for maintaining the BinderHub deployments that serve mybinder.org

For your problem, can you give more information about your setup (e.g. link to your github repo, and instructions you've followed to set up the repo, etc)

**Comment by pablobernabeu** [comment]
Hi @choldgraf - thanks a lot. I will ask there. 

Glad to expand. The Github repo is [this one](https://github.com/pablobernabeu/Modality-switch-effects-emerge-early-and-increase-throughout-conceptual-processing), and the instructions I followed were from the Binder docs. Especially, I mimicked the [Binder R Examples from Github](https://github.com/binder-examples/r). So, I have a Jupyter index and a runtime file, as well as `library(httr)` among the `install.R` packages. RStudio launches well, and so does the Shiny app from there (the latter requires setting the working directory accordingly to ERPs/Analyses of ERPs averaged across trials/Shiny app).

**Comment by betatim** [comment]
I'd recommend running `repo2docker <yourgithuburlhere>` locally to get access to more of the logs to help debug what is happening/tripping up the Shiny server.

I'd also suggest we close this (and reopen it in the repo2docker repository) as this is probably not an issue with mybinder.org itself but one of the tools it uses.

**Comment by pablobernabeu** [comment]
Thanks! I'm trying some tips from the gitter channel. I've never used the Git terminal, but I'll try and check what you mention if I can't get it to work.

**Comment by pablobernabeu** [comment]
The error was caused by the %20s in the URL--one of @fomightez's suggestions on the Gitter suggestions on the Binder Gitter channel. Kudos to him!
Now live! https://mybinder.org/v2/gh/pablobernabeu/Modality-switch-effects-emerge-early-and-increase-throughout-conceptual-processing/master?urlpath=shiny/Shiny-app/
