### ISSUE TITLE
no traffic to GESIS since version checks?

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/mybinder.org-deploy#1204]
Hi, we just realised that since we merged https://github.com/jupyterhub/mybinder.org-deploy/pull/1191, it looks like we don't get any traffic from federation or only a little:
https://notebooks.gesis.org/grafana/d/fZWsQmnmz/pod-activity?orgId=1&panelId=3&fullscreen&from=now-7d&to=now&refresh=1m

Also when we compare launches in [last day](https://notebooks.gesis.org/gallery/gesisbinder/24h/) and [last week](https://notebooks.gesis.org/gallery/gesisbinder/7d/), there is a decrease. And there isn't any launches of repos "ipython-in-depth" and "jupyterlab-demo".

Do you have any idea what is happening?

**Comment by bitnik** [comment]
I forgot to mention that from 11.10 23:02 till 12.10 at 7:45, GESIS Binder was not up-to-date, so in that period it is normal that we didn't get any traffic.

**Comment by betatim** [comment]
No idea really. In the logs of the federation redirect I see that the health is being checked and that it is healthy at the moment. https://mybinder.org/active_hosts also looks like it is happy :-/
