### ISSUE TITLE
Instantly Fails to Connect

### ISSUE THREAD

**Issue by arnavs** [jupyterhub/mybinder.org-deploy#1281]
This [link](https://mybinder.org/v2/gh/arnavs/HealthSimulations.jl/master?filepath=signal-disclosure%2Fmain.ipynb) has historically worked, but now instantly fails to connect to event stream. 

I think this has been happening for a few days or weeks.

Just a standard Julia repo with a project/manifest, so nothing fancy going on.

**Comment by betatim** [comment]
When I click on the Binder button on that page I get https://mybinder.org/v2/gh/jlperla/KnowledgeDiffusionSimulations.jl/master which instantly starts building the repository.

**Comment by arnavs** [comment]
Thanks @betatim, I put the wrong link in the issue. 

But, when I try the new link, it also seems to work now... I can't really pinpoint what changed? This is in Safari on macOS Catalina. It just instantly would say "failed to connect to event stream."

Will close this as I can't reproduce anymore.

**Comment by arnavs** [comment]
@betatim Still seeing this, now on a different machine (Safari on macOS Catalina still.)

Just to confirm, the link is: https://mybinder.org/v2/gh/arnavs/HealthSimulations.jl/master?filepath=signal-disclosure%2Fmain.ipynb

**Comment by choldgraf** [comment]
Just a note that "failed to connect to event stream" often means there's a problem with the streaming logs, but not necessarily with the underlying build. This has been an ongoing issue unfortunately.

FWIW, I just clicked the link and it's launched into a build

**Comment by arnavs** [comment]
OK, it works for me again... weird. Different wifi network, if that makes a difference. 

Closing.
