### ISSUE TITLE
 R-based repos no longer build at ovh or gke while they still build at gesis

### ISSUE THREAD

**Issue by fomightez** [jupyterhub/mybinder.org-deploy#1308]
It seems that because of the release of a new version/patch(?) of R (3.6.2) on [the 12th of this month](https://www.r-project.org/), repos based on [the official R template]((https://github.com/binder-examples/r)) no longer build at ovh or gke while they still build at gesis for now. This repo at https://github.com/fomightez/testrtempl gives the same error reported in [this discourse post](https://discourse.jupyter.org/t/cannot-get-r-project-working/2917?u=fomightez) when I try with gke or ovh. The only thing I changed after copying from [the current R-based template](https://github.com/binder-examples/r) was where the badges point.  The one that works at present (gesis) results in having R version 3.6.1.

According to [the latest documentation](https://github.com/jupyter/repo2docker/pull/772/commits/efab51b3141f53d4ac17472050fcd151c3db2607) you can specify 'patch releases'. Seems specifying 3.6.1 in the runtime doesn't fix things on Google or OVH. On the plus side though, it doesn't break it at gesis. Changing to 3.6.2 in the runtime makes it consistently not build **everywhere**. And so I'd say that specifying a particular patch release only works up to a point? If a brand new patch release comes out, something has to be changed actively, it seems. Or maybe I am missing what the documentation means by 'patch releases' in the 3.6 series?

**Comment by choldgraf** [comment]
that error message definitely makes it seem like a version error... Thanks for reporting! Hmm, maybe it's a bug in the runtime build pack? Or a bug in the R docker file?

**Comment by fomightez** [comment]
**UPDATE:**  
Despite the original title of this issue, now the R-based builds also fail to build using Gesis. They must have updated in the last few days. This means R-based build using the current approach illustrated by https://github.com/binder-examples/r , using `runtime` and `install.R`, presently do not work in the public Binder Federation.

**Comment by choldgraf** [comment]
Do you know if there is a corresponding issue in repo2docker for this? I think that's where the fix would be. Have we confirmed that this also doesn't work when using repo2docker locally?

**Comment by manics** [comment]
I can reproduce it when running the installation commands manually: https://github.com/jupyter/repo2docker/pull/830

**Comment by choldgraf** [comment]
I believe that this is now fixed - I merged @manic's PR to repo2docker and then manually deployed it to mybinder.org. I was able to successfully build the `binder-examples/r` repository, and we can get confirmation from others if it works for them too.

@manic's PR basically just pinned the `r-recommended` version to the `R_VERSION` as well, so now both should have the same explicit R version, which seems correct anyway

**Comment by ctb** [comment]
Worked for me on https://github.com/ngs-docs/2020-ggg-298-first-day-rnaseq, thank you!

**Comment by betatim** [comment]
I'll close this now. There are a few more issues related to building repos with older versions of R linked via https://github.com/jupyter/repo2docker/issues/813 (as usual wisdom and time to help fix it are very welcome :) )
