### ISSUE TITLE
R examples works on mybinder.org while it fails locally with repo2docker

### ISSUE THREAD

**Issue by xhochy** [jupyterhub/mybinder.org-deploy#1318]
The [R example](https://github.com/binder-examples/r) runs successfully on mybinder.org but locally using the lastest version of `repo2docker` it comes up only with a Python kernel. The reason is that the `RBuildPack` doesn't detect it being an R repository, see https://github.com/jupyter/repo2docker/blob/6e93cb06a44ca9b7faeb09c580dc9b922c617594/repo2docker/buildpacks/r.py#L74-L99 and the default `PythonBuildPack` is started.

**Comment by xhochy** [comment]
This seems to indicate that either a different `repo2docker` version or configuration is deployed on `mybinder.org`. I couldn't find evidence supporting either guess

**Comment by manics** [comment]
The last update to the repo2docker version on mybinder.org was https://github.com/jupyterhub/mybinder.org-deploy/pull/1311/
which is the same as the repo2docker `master`: https://github.com/jupyter/repo2docker/tree/d9335cf18b294938a1b066673c87fd6f58bcfa25

What version of repo2docker are you using?

**Comment by xhochy** [comment]
Yes, the latest release of `repo2docker` doesn't work but the master does. So no problem with the mybinder deploy but it would be nice if `repo2docker` would get a new tag.
