### ISSUE TITLE
grafana for GESIS cluster

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/mybinder.org-deploy#1325]
Some panels in mybinder.org/grafana shows wrong data for GESIS cluster, e.g. "Launch/Build Success panel" (https://grafana.mybinder.org/d/3SpLQinmk/1-overview?orgId=1&refresh=1m&var-cluster=gesis&fullscreen&panelId=16). The reason is that under notebooks.gesis.org we run 2 binderhub instances, one is public binder, which is member of federation, other is a authenticated persistent binder (exists in `jhub-ns` k8s namespace), where we have more launch failures which is expected and our prometheus collects metrics from both. 

For this issue I just imported "1. Overview" dashboard from mybinder grafana and updated the query only for "Launch/Build Success panel" (https://notebooks.gesis.org/grafana/d/3SpLQinmk/1-overview?orgId=1&refresh=1m&var-cluster=default&fullscreen&panelId=16) by adding `kubernetes_namespace!="jhub-ns"` into filters in queries. 

Probably there is a better one, but adding this filter is just a quick solution came into my mind and it should work for all clusters. I am not sure how to proceed here. We can update each dashboard in mybinder grafana in the same way where required or we can remove GESIS cluster from there and for GESIS we can use https://notebooks.gesis.org/grafana/, where we already updated queries.

**Comment by betatim** [comment]
For this specific case I think adding the filter to the query is a good thing to do.

How to deal with differences in the clusters that result in different queries in general is tricky :-/ I do like having one place to go to where you can see the same charts for each cluster without having to keep them in sync across different grafana instances.

For now I've updated the query. Let's think a bit more.

**Comment by betatim** [comment]
Maybe we can setup a datasource in grafana that applies this filter or a prometheus "output" which does this? So that the mybinder.org grafana includes something in its query to the gesis prometheus instance to have the data already removed but the grafana on gesis gets the data.

**Comment by rgaiacs** [comment]
This is out date. GESIS sunset the authenticated persistent binder.
