### ISSUE TITLE
basic auth for GESIS prometheus

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/mybinder.org-deploy#1342]
Hi, we just added basic auth for GESIS prometheus (http://notebooks.gesis.org/prometheus), which is also used in mybinder grafana. I just shared auth details with @betatim in keybase, so you can update that datasource in grafana. Right now when I open mybinder grafana there are errors, it should be due to what we the basic auth we just added.

**Comment by betatim** [comment]
Thanks. I configured the datasource on grafana.mybinder.org with the details you sent and it seems to be working.
