### ISSUE TITLE
RTD build failing

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/mybinder.org-deploy#1397]
The RTD build is failing because metachannel is no longer available (see https://github.com/jupyterhub/jupyterhub/issues/2958#issuecomment-606483892).

I tried fixing this in JH (https://github.com/jupyterhub/jupyterhub/pull/3010) by using pip instead of conda to install the requirements. Should we try do the same here too?

**Comment by choldgraf** [comment]
argg - do you know why metachannel is down? Permanently? (and either way, I think we should try to use pip wherever possible)

**Comment by GeorgianaElena** [comment]
@choldgraf  checkout this: https://github.com/regro/conda-metachannel/issues/31#issuecomment-606267515.
 Is there anything we can do to help?

**Comment by choldgraf** [comment]
good question - depends on how much it costs etc. I'm also not positive how much added value we're getting from it because I don't understand what it's doing super well haha, but perhaps you and other team members can comment on that?
