### ISSUE TITLE
Turing cluster: Scheduled maintenance 2020-05-04

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/mybinder.org-deploy#1425]
Hi all,

Azure informed me that there will be some scheduled maintenance affecting the Turing federation cluster on **4th May 2020**. The plan is to move Turing to staging for that day to experiment with the federation redirector and if it's clever enough to work out when the cluster is down :-)

**Comment by betatim** [comment]
Do you want to make a PR today to set that up? I am not quite sure which timezone Azure uses so 4 May might start soon (or not for a good while).

**Comment by sgibson91** [comment]
Maintenance window is 17:30 - 19:30 UTC. I'm not sure I know what "moving to staging" means in terms of the PR actually! 😬
