### ISSUE TITLE
Increase limit for NSLS-II user workshop to 300

### ISSUE THREAD

**Issue by tacaswell** [jupyterhub/mybinder.org-deploy#1438]
We are using binder for a workshop at the NSLS-II Users Meeting that was far better attended than expected and have discovered 100 concurrent user limit on https://github.com/bluesky/tutorials .  We are currently running the workshop (and have about 2 hours left util 1600 EST).  Would it be possible to get the limit increased for the rest of the day?

https://nsls2cfnusersmeeting.bnl.gov/workshops/workshop.aspx?year=2020&id=163

We apologize for the very short notice of this requset!

**Comment by betatim** [comment]
Good luck! Can we trade you answers to the following questions in exchange for the bumped up limit? Replies in sub-bullet point format works well for us, no full sentences needed. This is mostly about creating some amount of data that will be easy to look at later.

Could you please help us keep track of this? In the issue please mention:
* who you are,
* a bit of details about the event/course/context,
* if money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
* a link to the repository you are using,
* what type of event it is (a talk, a workshop, lecture course, training session)
* how many people you expect to attend the event,
* the exact times and dates of the event(s) (with timezone information)

**Comment by danielballan** [comment]
I'll jump in for that.

* Brookhaven National Lab National Synchrotron Light Source II
* An annual ["Users' Meeting"](https://nsls2cfnusersmeeting.bnl.gov/workshops/workshop.aspx?year=2020&id=163)
* Free (this year)
* https://github.com/bluesky/tutorials
* Something between a workshop and a training session
* 250
* 2020-05-19 1:00:00 - 2020-05-19 4:00:00 EDT

Thanks again. We expected ~40 like last year but were surprised late by 250 attendees this year, hence the late request. We'll plan ahead next year.

**Comment by choldgraf** [comment]
Thanks @danielballan for the information :-) I think we can close this now unless we wanna keep it open for a debrief

**Comment by manics** [comment]
I'm closing this so it doesn't show up when we list the current [Impact](https://github.com/jupyterhub/mybinder.org-deploy/labels/impact) labels.
