### ISSUE TITLE
Issue template for increasing resources requests

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/mybinder.org-deploy#1446]
### Proposed change

Add an issue template where we ask for details when requests to bump resources for certain repositories are made (usually for online events where a lot of people are expected to attend).

(Proposed by Tim at the [May team meeting](https://jupyterhub-team-compass.readthedocs.io/en/latest/monthly-meeting/2020-05-21.html) :sparkles: )

### Alternative options

- Allow free-text requests
- Have a maintainer ask for details about the use-case of the request

### Who would use this feature?

This would be useful for both maintainers and people asking for more resources for their event.
Providing as much information as possible right from the start, will speed up the decision process.

### (Optional): Suggest a solution

Start with the template proposed by @betatim [here](https://jupyterhub-team-compass.readthedocs.io/en/latest/monthly-meeting/2020-05-21.html).

**Comment by GeorgianaElena** [comment]
I looked into having both the organizational and repo-based templates at the same time and this is what I found [in the docs](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file#about-default-community-health-files):

*If a repository has any files in its own .github/ISSUE_TEMPLATE folder, including issue templates or a config.yml file, none of the contents of the default .github/ISSUE_TEMPLATE folder will be used.*

It sounds that we can just have one or the other?

(cc @sgibson91 :sun_with_face:)

**Comment by sgibson91** [comment]
That's disappointing! I guess we could either:

1) have the template in a repository that doesn't have the support bot installed, or;
2) manually copy across the configs for the support bot to this repo.

I think if we are going to roll out the support bot org-wide then 2 is our only option, but having to sync up the support bot/issue templates in 2 places is sub-optimal. What do you think?

**Comment by GeorgianaElena** [comment]
When debugging why the request-info bot doesn't work across the org repos, I bumped into this probot [piece of documentation](https://github.com/probot/probot/blob/3f0491f63b854de5372e8bed0017b87c8762297e/docs/best-practices.md#store-configuration-in-the-repository).

Assuming the support bot uses the version of probot that has this extending feature (I'll have to look into it) we could "extend" the support bot config here from the org-wide `.github` repo. Although not ideal, at least this way, we would only maintain it in only one place.

But I don't know if there's an "extending" option for the other issue templates, so we may have to copy-paste them here to have them in this repo :confused:

**Comment by sgibson91** [comment]
> Assuming the support bot uses the version of probot that has this extending feature (I'll have to look into it) we could "extend" the support bot config here from the org-wide `.github` repo. Although not ideal, at least this way, we would only maintain it in only one place.

That sounds like a good place to begin.

> But I don't know if there's an "extending" option for the other issue templates, so we may have to copy-paste them here to have them in this repo 😕

I agree, I suspect there isn't an extension option for issue templates 🙁

**Comment by betatim** [comment]
For this repo we don't receive a lot of issues/PRs from outsiders. So maybe we can live with the fact that we don't have the default templates here (or only have the copy&pasted ones).

**Comment by choldgraf** [comment]
Note that @GeorgianaElena has a PR to address this here: #1447
