### ISSUE TITLE
504 Gateway Time-out error on turing.mybinder.org

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/mybinder.org-deploy#1461]
Turing is currently experiencing time-out issues when trying to redirect. You can see this by trying to visit turing.mybinder.org. At the moment, I'm at a loss as to the cause. All nodes are healthy and nothing suspicious in the hub logs.

**Comment by sgibson91** [comment]
This was fixed by forced deleting some hanging user pods in `Completed` and `Terminating` states. I'm not sure why those two things are linked though!

**Comment by choldgraf** [comment]
Thanks for the debug and the post-mortem notes :-)
