### ISSUE TITLE
Increase limit for SciPy tutorial (Deep Learning) to 300

### ISSUE THREAD

**Issue by hugobowne** [jupyterhub/mybinder.org-deploy#1477]
### 1. Who you are

Hugo Bowne-Anderson (Coiled) and Dhavide Aruliah (Quansight) @dhavide

### 2. A few details about the event/course/context

SciPy conference

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

Registration:  $75/$25US for students

Speakers paid $1KUS in total for material development time, is my understanding.

### 4. A link to the repository you are using

https://github.com/hugobowne/deep-learning-from-scratch-pytorch

(note that there will be pytorch requirements not yet in the environment). @dhavide will be able to speak more to this

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

### 6. How many people you expect to attend the event

It's not clear to me. My understanding is that anybody who registered for SciPy _can_ attend. And there may be 900-1K registrants? 

### 7. The exact times and dates of the event(s) (with timezone information)

9am CDT Wednesday 07/08

### 8. How do you plan to give mybinder.org a shout out at the event

Not by getting 100s of people to launch binders and then talking for 10 minutes ;)

More seriously, by doing what i do every time: continually communicating that Binder is the go-to PyData stack & Jupyter way of spinning up labs // notebooks in executable & reproducible environments at the click of a button // badge.

**Comment by manics** [comment]
The quota was bumped yesterday. Good luck with the workshop, please give us some feedback afterwards.

**Comment by hugobowne** [comment]
thank you and will do!
