### ISSUE TITLE
Increase limit for SciPy tutorial (Xarray) to 300

### ISSUE THREAD

**Issue by jhamman** [jupyterhub/mybinder.org-deploy#1479]
### 1. Who you are

Joe Hamman (NCAR; @jhamman), Ryan Abernathey (Columbia U.; @rabernat), Stephan Hoyer (Google; @shoyer), and Deepak Cherian (NCAR; @dcherian)

### 2. A few details about the event/course/context

SciPy conference tutorial

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

Registration: $75/$25US for students

Speakers paid $1KUS in total for material development time, is my understanding.

### 4. A link to the repository you are using

https://github.com/xarray-contrib/xarray-tutorial

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

### 6. How many people you expect to attend the event

Not 100% sure. We're expecting 100+ but due to the distributed nature of this years conference, we don't know for sure.

### 7. The exact times and dates of the event(s) (with timezone information)

Thursday, July 6. 5:45a - 11:00a PT.

### 8. How do you plan to give mybinder.org a shout out at the event

We're building this into the intro to the workshop. You folks rock!

**Comment by manics** [comment]
Just noticed your day `Thursday` and date `July 6` don't match. In any case the quota was bumped yesterday. If you're workshop has already happen I hope it went well, if not good luck! Please give us some feedback afterwards.

**Comment by dcherian** [comment]
Thanks @manics . Things worked well during the tutorial!
