### ISSUE TITLE
Increase limit for SciPy tutorial (Conda) to 300

### ISSUE THREAD

**Issue by davidrpugh** [jupyterhub/mybinder.org-deploy#1480]
1. Dr. David R. Pugh, Staff Scientist at King Abdullah University of Science and Technology (KAUST); Certified Instructor, The Carpentries.

2. Introduction to Conda for (Data) Scientists: This lesson is an introduction to Conda for (data) scientists. Conda is an open source package and environment management system that runs on Windows, macOS and Linux. Conda installs, runs, and updates packages and their dependencies. Conda easily creates, saves, loads, and switches between environments on your local computer. While Conda was created for Python programs it can package and distribute software for any languages such as R, Ruby, Lua, Scala, Java, JavaScript, C/ C++, FORTRAN. This lesson motivates the use of Conda as a development tool for building and sharing project specific software environments that facilitate reproducible (data) science workflows.

3. SciPy 2020 pays a 1000 USD stipend to tutorial instructors. I am currently arranging for Enthought to donate this stipend to the Python Software Foundation. I would be happy to push some or all of this money your way if possible. Given the number of tutorials that are using mybinder.org perhaps Enthought could work something out to help push some of the donated stipend money your way.

4. https://github.com/carpentries-incubator/introduction-to-conda-for-data-scientists/tree/binder

5. What type of event it is:
- [ ] talk
- [X] workshop
- [ ] lecture course
- [ ] training session

6. Have been told to expect 200-300 participants.

7. 07/09/2020 from 9 am - 1 pm CDT.

8. Will be thanking mybinder.org at the start and end of the event.

**Comment by manics** [comment]
The quota was bumped yesterday. Good luck with the workshop, please give us some feedback afterwards.

**Comment by davidrpugh** [comment]
Thanks! That's fantastic. Will definitely provide feedback.
