### ISSUE TITLE
Requesting bump resources for Bayesian stats tutorial

### ISSUE THREAD

**Issue by ericmjl** [jupyterhub/mybinder.org-deploy#1481]
### 1. Who you are

Eric J. Ma (@ericmjl) and Hugo Bowne-Anderson (@hugobowne)

### 2. A few details about the event/course/context

SciPy 2020, tutorial.

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

Yes, attendees have to pay to attend SciPy, and tutorial leads receive a stipend.

### 4. A link to the repository you are using

https://github.com/ericmjl/bayesian-stats-modelling-tutorial/

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

### 6. How many people you expect to attend the event

We are not sure, but since we know that there are 900+ registered for SciPy and two tutorials running concurrently, a safe upper-bound limit should be 500 people (though I seriously don't expect _that_ many).

### 7. The exact times and dates of the event(s) (with timezone information)

8 am to 12 pm CDT, on 6 July

### 8. How do you plan to give mybinder.org a shout out at the event

1. At each of my tutorials that use Binder, I have a habit of publicly acknowledging the Binder team's role in open computational education.
2. This time round, at the end of the workshop, I will be reminding participants to make donations to NumFOCUS and other non-profits that support open computing tooling.

**Comment by manics** [comment]
Hi @ericmjl, please could you add the date of the workshop, you've only included the time 🙂. Thanks!

**Comment by ericmjl** [comment]
Oh my, 🤦  me! Updated!

**Comment by hugobowne** [comment]
duplicate issue: https://github.com/jupyterhub/mybinder.org-deploy/issues/1476

**Comment by ericmjl** [comment]
Whoops! OK, let’s close this one then :).
