### ISSUE TITLE
Increase limit for SciPy tutorial (Dask) to 300

### ISSUE THREAD

**Issue by jrbourbeau** [jupyterhub/mybinder.org-deploy#1483]
### 1. Who you are

James Bourbeau (Coiled; @jrbourbeau), Dharhas Pothina (Quansight; @dharhas), Mike McCarty (Capital One; @mmccarty)

### 2. A few details about the event/course/context

SciPy conference tutorial

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

Registration: $75/$25 US for students

Speakers paid $1k US in total for material development time

### 4. A link to the repository you are using

https://github.com/dask/dask-tutorial

### 5. What type of event it is:

- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

### 6. How many people you expect to attend the event

Not 100% sure. We're expecting 100+ but due to the distributed nature of this years conference, we don't know for sure. 

We're offering mybinder.org as one option for following the tutorial locally. However, we're also providing other setup options (e.g. a conda `environment.yml` for local installs), so we're not sure how many attendees will opt to use binder.  

### 7. The exact times and dates of the event(s) (with timezone information)

Tuesday July 7, 2020 from 9AM - 1 PM CT

### 8. How do you plan to give mybinder.org a shout out at the event

Will thank the binder team at the start and end of the tutorial

**Comment by manics** [comment]
The quota was bumped yesterday. Good luck with the workshop, please give us some feedback afterwards.
