### ISSUE TITLE
📈 2020-07-13 Request to bump resources for Uproot & Awkward Arrays Tutorial at PyHEP 2020

### ISSUE THREAD

**Issue by matthewfeickert** [jupyterhub/mybinder.org-deploy#1499]
> 📅 Ideally open an issue two weeks before an event, though we will still consider requests up to 48 hours before the event 📅

This request is being put in less than 48 hours in advance. We fully understand this request might not be possible to fulfill and can drop Binder support for this section. We apologize for this late request.

### 1. Who you are

@matthewfeickert (PyHEP 2020 workshop organizer contact) on behalf of @jpivarski (presenter).

### 2. A few details about the event/course/context

This is for a tutorial at the [PyHEP 2020 workshop](https://indico.cern.ch/event/882824/) 2020-07-13 through 2020-07-17.

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

No, all speakers and organizers are volunteers. The workshop is free of charge and all resources will be made publicly available both on the [workshop website/Indico page](https://indico.cern.ch/event/882824/) and on the [High Energy Physics Software Foundation YouTube channel](https://www.youtube.com/channel/UCv4hukXGkCYvBClQMKzypnQ).

### 4. A link to the repository you are using

https://github.com/jpivarski/2020-07-13-pyhep2020-tutorial

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

(This is a tutorial at a workshop, so I chose "workshop". I will be submitting more of these, so please let me know if I should change this.)

### 6. How many people you expect to attend the event

There are 1000 attendees registered, but we would anticipate that an upper _estimate_ would be maybe 600-700 would connect at this time.

### 7. The exact times and dates of the event(s) (with timezone information)

[Uproot & Awkward Arrays (TUTORIAL)](https://indico.cern.ch/event/882824/timetable/#29-uproot-awkward-arrays-tutor) is occurring at 8:00 - 9:00 UTC-6 on 2020-07-13.

### 8. How do you plan to give mybinder.org a shout out at the event

We will make an announcement at the start of the workshop about Binder, the service, and how the resources are being provided. If there is specific language the Binder team would like us to use we are happy to integrate this in.

**Comment by jpivarski** [comment]
> ### 4. A link to the repository you are using
> https://github.com/jpivarski/2020-07-13-pyhep2020-tutorial

An exact Binder link is now available: we want 600‒700 people to be able to run

https://mybinder.org/v2/gh/jpivarski/2020-07-13-pyhep2020-tutorial.git/1.1?urlpath=lab/tree/tutorial.ipynb

on July 13, 2020 at 13:10—14:10 UTC. I hope the request isn't coming too late. Thanks!

**Comment by matthewfeickert** [comment]
Thanks very much for correcting the Issue titles @betatim. I'll use that format for any others that get sent in.

**Comment by betatim** [comment]
We should maybe update the template if people like having the date. In this case it was helpful because there were so many that came in at the same time :)

**Comment by betatim** [comment]
We set a limit of 400 concurrent pods/instances for this repository. Typically mybinder.org peaks at 800 concurrent instances across all different repos during the working day. So compared to the current "global" size of mybinder.org 400 concurrent instances for one repo corresponds to about 50% of the global capacity. As a result we won't increase the limit further. mybinder.org only works because lots of people share the resources we have so giving more than 50% of our typical capacity to one repository isn't sustainable (imagine every day three repos came and requested this scale of boost).

The good thing is that from our experience so far is that only about 1/3 of people who are "following" a live stream/tutorial start a binder. So you should be fine with a limit of 400.

**Comment by matthewfeickert** [comment]
This is great! Thanks so much @betatim and all!

> The good thing is that from our experience so far is that only about 1/3 of people who are "following" a live stream/tutorial start a binder. So you should be fine with a limit of 400.

Yup. I'll adjust the other request numbers today after I see how many connect throughout today's meetings (maybe a lower number of resources would be fine).

**Comment by betatim** [comment]
Right now there are about 40 concurrent pods running

**Comment by matthewfeickert** [comment]
> Right now there are about 40 concurrent pods running

Were having a Zoom issue where only 300 people are able to get into our room, so some people might not have hit yet. I asked that people try to use the CERN resources first if possible to not slam things, but that's having issues now so you may see a spike soon.

**Comment by betatim** [comment]
Correction: now about 160 pods

**Comment by matthewfeickert** [comment]
We've now fixed the Zoom issue and have over 400 people in the meeting. Hopefully there isn't too much traffic at the moment.

**Comment by manics** [comment]
FYI the mybinder grafana dashboards are public, you can see your pods here:
https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&refresh=1m&from=now-3h&to=now

**Comment by matthewfeickert** [comment]
> FYI the mybinder grafana dashboards are public, you can see your pods here:
> https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&refresh=1m&from=now-3h&to=now

oh! I did not know that but that is _so_ useful! Thank you @manics! I will now be monitoring this for all future talks for PyHEP.

**Comment by matthewfeickert** [comment]
For context, we had 430 people max in the call and it looks like we capped out at around 250 pods.

![Jim_talk](https://user-images.githubusercontent.com/5142394/87314403-c41e5380-c4e8-11ea-8e5f-3c1afc0407b9.png)

**Comment by matthewfeickert** [comment]
Closing this Issue as the talk has finished. Thanks very much Binder team for being awesome!
