### ISSUE TITLE
📈 2020-07-13 Request to bump resources for Ganga Tutorial at PyHEP 2020

### ISSUE THREAD

**Issue by matthewfeickert** [jupyterhub/mybinder.org-deploy#1500]
> 📅 Ideally open an issue two weeks before an event, though we will still consider requests up to 48 hours before the event 📅

This request is being put in less than 48 hours in advance. We fully understand this request might not be possible to fulfill and can drop Binder support for this section. We apologize for this late request.

### 1. Who you are

@matthewfeickert (PyHEP 2020 workshop organizer contact) on behalf of @egede (presenter).

### 2. A few details about the event/course/context

This is for a tutorial at the [PyHEP 2020 workshop](https://indico.cern.ch/event/882824/) 2020-07-13 through 2020-07-17.

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

No, all speakers and organizers are volunteers. The workshop is free of charge and all resources will be made publicly available both on the [workshop website/Indico page](https://indico.cern.ch/event/882824/) and on the [High Energy Physics Software Foundation YouTube channel](https://www.youtube.com/channel/UCv4hukXGkCYvBClQMKzypnQ).

### 4. A link to the repository you are using

https://github.com/ganga-devs/ganga/

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

(This is a tutorial at a workshop, so I chose "workshop". I will be submitting more of these, so please let me know if I should change this.)

### 6. How many people you expect to attend the event

There are 1000 attendees registered, but we would anticipate that an upper _estimate_ would be maybe 600-700 would connect at this time.

### 7. The exact times and dates of the event(s) (with timezone information)

[Ganga: flexible use of of virtualisation for user based large scale computations (TUTORIAL)](https://indico.cern.ch/event/882824/timetable/#37-ganga-flexible-use-of-of-vi) is occurring at 17:50 - 18:45 UTC-6 on 2020-07-13.

### 8. How do you plan to give mybinder.org a shout out at the event

We will make an announcement at the start of the workshop about Binder, the service, and how the resources are being provided. If there is specific language the Binder team would like us to use we are happy to integrate this in.

**Comment by matthewfeickert** [comment]
@betatim Seems that the reported number of attendees for the "Pacific" timezone sessions is very much ff from reality as we peaked at 100 people in the call and at most had 38 Binder sessions running all at once.

![ganga_grafana](https://user-images.githubusercontent.com/5142394/87364563-931a3f00-c539-11ea-982d-0785a65f51e1.png)

I'm sorry that we gave such a drastic over estimate on resources, but I'll go scale down the requests in all the other Issues.

**Comment by betatim** [comment]
That's fine. It is better that we overestimate the resources and expect to be able to handle that than the other way around.

Thanks for the data on how many people were in the call and how many binders were running. It seems like (4/3)*pi is emerging as the natural constant to multiply the number of people in a live stream by to get number of concurrent binders. (I'm expecting a paper on the arxiv by theorists tomorrow explaining why 4/3pi is natural and not fine tuned 😂)
