### ISSUE TITLE
📈 2020-07-15 Request to bump resources for Coffea Tutorial at PyHEP 2020

### ISSUE THREAD

**Issue by matthewfeickert** [jupyterhub/mybinder.org-deploy#1501]
> 📅 Ideally open an issue two weeks before an event, though we will still consider requests up to 48 hours before the event 📅

This request is being put in less than the requested two weeks in advance. We fully understand this request might not be possible to fulfill and can drop Binder support for this section. We apologize for this late request.

### 1. Who you are

@matthewfeickert (PyHEP 2020 workshop organizer contact) on behalf of @mat-adamec (presenter).

### 2. A few details about the event/course/context

This is for a tutorial at the [PyHEP 2020 workshop](https://indico.cern.ch/event/882824/) 2020-07-13 through 2020-07-17.

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

No, all speakers and organizers are volunteers. The workshop is free of charge and all resources will be made publicly available both on the [workshop website/Indico page](https://indico.cern.ch/event/882824/) and on the [High Energy Physics Software Foundation YouTube channel](https://www.youtube.com/channel/UCv4hukXGkCYvBClQMKzypnQ).

### 4. A link to the repository you are using

https://github.com/CoffeaTeam/coffea-casa-tutorials

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

(This is a tutorial at a workshop, so I chose "workshop". I will be submitting more of these, so please let me know if I should change this.)

### 6. How many people you expect to attend the event

There are 1000 attendees registered, but we would anticipate that an upper _estimate_ would be maybe 300-400 would connect at this time. Based off of Issue #1499 this seems a realistic upper limit.

### 7. The exact times and dates of the event(s) (with timezone information)

[Columnar Analysis at Scale with Coffea (TUTORIAL)](https://indico.cern.ch/event/882824/timetable/#33-columnar-analysis-at-scale) is occurring at 08:00 - 08:45 UTC-6 on 2020-07-15.

### 8. How do you plan to give mybinder.org a shout out at the event

We will make an announcement at the start of the workshop about Binder, the service, and how the resources are being provided. If there is specific language the Binder team would like us to use we are happy to integrate this in.

**Comment by mat-adamec** [comment]
> ### 4. A link to the repository you are using
> 
> https://github.com/CoffeaTeam/coffea-casa

Hi - I'll be the presenter of this tutorial! The repository actually ended up over at: https://github.com/CoffeaTeam/coffea-casa-tutorials rather than what is specified above. Sorry for the confusion!

**Comment by matthewfeickert** [comment]
Thanks for the heads up @mat-adamec! I've updated the Issue body.

**Comment by matthewfeickert** [comment]
Updated the number of expected simultaneous instances to be `< 400`.

**Comment by matthewfeickert** [comment]
There was about 180 people in the talk but low usage of the Binder Federation resources with 68 launches across the Federation.

GKE (56):

![coffee_casa_gke](https://user-images.githubusercontent.com/5142394/87569677-1dbf8300-c68d-11ea-8eb8-5bcb02d09f8b.png)

OVH (12):

![coffee_casa_ovh](https://user-images.githubusercontent.com/5142394/87569755-36c83400-c68d-11ea-906a-4677506f05a7.png)
