### ISSUE TITLE
📈 2020-07-16 Request to bump resources for SModelS  Talk at PyHEP 2020

### ISSUE THREAD

**Issue by matthewfeickert** [jupyterhub/mybinder.org-deploy#1504]
> 📅 Ideally open an issue two weeks before an event, though we will still consider requests up to 48 hours before the event 📅

This request is being put in less than the requested two weeks in advance. We fully understand this request might not be possible to fulfill and can drop Binder support for this section. We apologize for this late request.

### 1. Who you are

@matthewfeickert (PyHEP 2020 workshop organizer contact) on behalf of @WolfgangWaltenberger (presenter).

### 2. A few details about the event/course/context

This is for a talk at the [PyHEP 2020 workshop](https://indico.cern.ch/event/882824/) 2020-07-13 through 2020-07-17.

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

No, all speakers and organizers are volunteers. The workshop is free of charge and all resources will be made publicly available both on the [workshop website/Indico page](https://indico.cern.ch/event/882824/) and on the [High Energy Physics Software Foundation YouTube channel](https://www.youtube.com/channel/UCv4hukXGkCYvBClQMKzypnQ).

### 4. A link to the repository you are using

https://github.com/SModelS/pyhep2020

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

(This is a talk at a workshop, so I chose "workshop". I will be submitting more of these, so please let me know if I should change this.)

### 6. How many people you expect to attend the event

There are 1000 attendees registered, but we would anticipate that an upper _estimate_ would be maybe 300-400 would connect at this time. Based off of Issue #1499 this seems a realistic upper limit.

### 7. The exact times and dates of the event(s) (with timezone information)

[SModelS – a tool for interpreting simplified-model results from the LHC](https://indico.cern.ch/event/882824/timetable/#58-smodels-a-tool-for-interpre) is occurring at 08:45 - 09:15 UTC-6 on 2020-07-16.

### 8. How do you plan to give mybinder.org a shout out at the event

We will make an announcement at the start of the workshop about Binder, the service, and how the resources are being provided. If there is specific language the Binder team would like us to use we are happy to integrate this in.

**Comment by WolfgangWaltenberger** [comment]
Hey, the repository is public, I binderized it, and it seems to be working. I put the link to binder on the README.md page of the github repository. Is there anything else I should do from my side?

**Comment by matthewfeickert** [comment]
> Hey, the repository is public, I binderized it, and it seems to be working. I put the link to binder on the README.md page of the github repository. Is there anything else I should do from my side?

No, @WolfgangWaltenberger I think you're good.

**Comment by matthewfeickert** [comment]
I've updated the number of expected simultaneous instances to be `< 400`.

**Comment by matthewfeickert** [comment]
There was about 100 people in the talk and low usage of the allocated Binder Federation resources with 30 launches across the Federation.

GKE (12):

![smodels_gke](https://user-images.githubusercontent.com/5142394/87685010-8586d400-c748-11ea-9718-b08bb0bce652.png)

GESIS (18):

![smodels_gesis](https://user-images.githubusercontent.com/5142394/87685020-8881c480-c748-11ea-9be5-0cbdb8625512.png)
