### ISSUE TITLE
Issues connecting when session is on hub-binder.mybinder.ovh

### ISSUE THREAD

**Issue by machow** [jupyterhub/mybinder.org-deploy#1509]
Hello--sorry if this is the wrong repo to raise an issue on.

I'm testing out creating a free, interactive data science course ([draft page](https://mchow.com/intro-to-siuba/intro-data-science/build/01b-filter/)) that would allow students to run code via binder (extremely similar to https://course.spacy.io/chapter1). Similar to the spacy course, I'm using @Jupyterlab/services v3.2.1. However, whenever it tries to create a connection on the .ovh domain, the kernel continuously tries to reconnect for a couple minutes and then dies.

Here's a session I was unable to connect to: https://hub-binder.mybinder.ovh/user/machow-purview-bihhxi0i/

After a bunch of refreshing to test, it appears...

* I can paste in `hub-binder.mybinder.ovh/user/<session-string>/tree?token=<token>` to the browser, and access the session, run code, etc...
* When the session is on hub.gke.mybinder.org it works fine.

I'm happy to investigate further, put the code for connecting to the session into a repo, etc.. but wanted to check--are there are any differences between the mybinder.org and .ovh services that might help with troubleshooting? One challenge is that if I refresh something like the spacy course, I never get routed to the .ovh one!

**Comment by betatim** [comment]
Off the top of my head the area I'd investigate is "cross site requests" and "ad-blockers". What error message(s) do you see when things don't work?

we do see problems with ad-blocking/tracker blocking software sometimes with the GESIS cluster which is also on a different domain (like the OVH one). It would also fit with "works when I explicitly copy&paste the URL but doesn't when my JS tries to do the same".

ps. if this turns into a longer "support" chat we should move it to a thread on https://discourse.jupyter.org/ as we try to use the issues only for discussions on concrete changes to the repo and keep the rest to the forum (easier to discover, more readers, etc). My hunch is that this isn't a problem with our clusters as it works for the spacy course, which means we should move the discussion :)

**Comment by betatim** [comment]
In my browser console I see "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://hub-binder.mybinder.ovh/user/machow-purview-wvgii7jp/api/kernels?1594617263342. (Reason: CORS request did not succeed)."

In the network connections tab I see the following (there is indeed no pre-flight request):
<img width="1238" alt="Screenshot 2020-07-13 at 07 17 11" src="https://user-images.githubusercontent.com/1448859/87273280-f7f17d00-c4d8-11ea-8554-e5b05460d421.png">

**Comment by machow** [comment]
Thanks for your response--I turned off adblock, and it worked out! I think the thing that threw me a bit, is that for me the POST request succeeded, but the websocket connection failed. Not sure why our POST requests have different CORS policies ¯\_(ツ)_/¯. 

I'll have to jump on the discourse and see what people are up to, since we've been using mybinder more with volunteer projects @CodeforPhilly, and it's been super interesting to explore the frontend tooling around jupyter!

Thanks again for you help!

## post succeeding

![image](https://user-images.githubusercontent.com/2574498/88095282-1a773c00-cb52-11ea-879a-736852c8d8f8.png)

## websocket error

![image](https://user-images.githubusercontent.com/2574498/88095220-fddb0400-cb51-11ea-8785-fd6aa172deed.png)
