### ISSUE TITLE
📈 2020-07-14 request to bump resources for PyROOT Talk at PyHEP 2020

### ISSUE THREAD

**Issue by matthewfeickert** [jupyterhub/mybinder.org-deploy#1514]
> 📅 Ideally open an issue two weeks before an event, though we will still consider requests up to 48 hours before the event 📅

This request is being put in less than 48 hours in advance. We fully understand this request might not be possible to fulfill and can drop Binder support for this section. We apologize for this late request.

Resources are also being made available on CERN's Binder Hub instance for attendees with CERN accounts.

### 1. Who you are

@matthewfeickert (PyHEP 2020 workshop organizer contact) on behalf of @stwunsch (presenter).

### 2. A few details about the event/course/context

This is for a talk at the [PyHEP 2020 workshop](https://indico.cern.ch/event/882824/) 2020-07-13 through 2020-07-17.

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

No, all speakers and organizers are volunteers. The workshop is free of charge and all resources will be made publicly available both on the [workshop website/Indico page](https://indico.cern.ch/event/882824/) and on the [High Energy Physics Software Foundation YouTube channel](https://www.youtube.com/channel/UCv4hukXGkCYvBClQMKzypnQ).

### 4. A link to the repository you are using

https://github.com/stwunsch/pyhep2020-pyroot

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

### 6. How many people you expect to attend the event

There are 1000 attendees registered, but we would anticipate that an upper _estimate_ would be maybe 300-400 would connect at this time. Based off of Issue #1499 this seems a realistic upper limit.

### 7. The exact times and dates of the event(s) (with timezone information)

[A new PyROOT for ROOT 6.22](https://indico.cern.ch/event/882824/timetable/#39-a-new-pyroot-for-root-622) is occurring at 08:40 - 09:10 UTC-6 on 2020-07-14.

### 8. How do you plan to give mybinder.org a shout out at the event

We will make an announcement at the start of the workshop about Binder, the service, and how the resources are being provided. If there is specific language the Binder team would like us to use we are happy to integrate this in.

**Comment by choldgraf** [comment]
@matthewfeickert can you say how many of these issues you're planning on opening up? (apologies if you've done this somewhere already). It is a little bit hard keeping track of them for me.

**Comment by matthewfeickert** [comment]
> Can you say how many of these issues you're planning on opening up? (apologies if you've done this somewhere already). It is a little bit hard keeping track of them for me.

@choldgraf Yes, apologies on this. I've made it clear to the PyHEP speakers that today is the last day that I will be making any resource requests and I got a flood of them in my inbox this morning.

![total_so_far](https://user-images.githubusercontent.com/5142394/87326183-0733f300-c4f8-11ea-9800-d01846226934.png)

The total shown in the screenshot is not correct though, as there are some duplicates.

This is the last request for 2020-07-14 but I will open all remaining issues today. I expect the number to be less than 10.

Also apologies if any of this is being viewed as abuse of the great resource that is the Binder Federation. We don't want that, so if any of this is becoming a problem please let us know and we can remove certain talks.

**Comment by matthewfeickert** [comment]
> Can you say how many of these issues you're planning on opening up? 

@betatim @choldgraf I'm done with all PyHEP 2020 request (and destroying the Issues) now. Thanks for putting up with the noise today.

**Comment by matthewfeickert** [comment]
Updated the number of expected simultaneous instances to be `< 400`.

**Comment by matthewfeickert** [comment]
There was about 320 people in the talk but hardly any use of the Binder Federation resources with 27 launches across OVH and GESIS (I also made the CERN BinderHub available, so haven't checked there on usage).

OVH:
![ovh_pyroot](https://user-images.githubusercontent.com/5142394/87436838-2fccf300-c5b3-11ea-868f-0047f3369121.png)

GESIS:
![gesis_pyroot](https://user-images.githubusercontent.com/5142394/87436867-38252e00-c5b3-11ea-8666-837c43868ff1.png)
