### ISSUE TITLE
📈 2020-07-15 request to bump resources for High Performance Python Tutorial at PyHEP 2020

### ISSUE THREAD

**Issue by matthewfeickert** [jupyterhub/mybinder.org-deploy#1521]
> 📅 Ideally open an issue two weeks before an event, though we will still consider requests up to 48 hours before the event 📅

This request is being put in less than 48 hours in advance. We fully understand this request might not be possible to fulfill and can drop Binder support for this section. We apologize for this late request.

Resources are also being made available on CERN's Binder Hub instance for attendees with CERN accounts.

### 1. Who you are

@matthewfeickert (PyHEP 2020 workshop organizer contact) on behalf of @henryiii (presenter).

### 2. A few details about the event/course/context

This is for a tutorial at the [PyHEP 2020 workshop](https://indico.cern.ch/event/882824/) 2020-07-13 through 2020-07-17.

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

No, all speakers and organizers are volunteers. The workshop is free of charge and all resources will be made publicly available both on the [workshop website/Indico page](https://indico.cern.ch/event/882824/) and on the [High Energy Physics Software Foundation YouTube channel](https://www.youtube.com/channel/UCv4hukXGkCYvBClQMKzypnQ).

### 4. A link to the repository you are using

https://github.com/henryiii/python-performance-minicourse

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

### 6. How many people you expect to attend the event

There are 1000 attendees registered, but we would anticipate that an upper _estimate_ would be maybe 100-200 would connect at this time. Given Issue #1500, a generous upper cap would be 150 simultaneous instances.

### 7. The exact times and dates of the event(s) (with timezone information)

[High-performance Python (TUTORIAL)](https://indico.cern.ch/event/882824/timetable/#48-high-performance-python-tut) is occurring at 17:00 - 18:00 UTC-6 on 2020-07-15.

### 8. How do you plan to give mybinder.org a shout out at the event

We will make an announcement at the start of the workshop about Binder, the service, and how the resources are being provided. If there is specific language the Binder team would like us to use we are happy to integrate this in.

**Comment by matthewfeickert** [comment]
Updated expected number of attendees to be `< 200` given Issue #1500.

**Comment by matthewfeickert** [comment]
There was about 70 people in the talk and low usage of the Binder Federation resources with 41 launches across the Federation.

GKE (36):

![henry_gke](https://user-images.githubusercontent.com/5142394/87608899-b1fa0c00-c6c6-11ea-8abd-9a741c2e507a.png)

OVH (5):

![henry_ovh](https://user-images.githubusercontent.com/5142394/87608908-b9211a00-c6c6-11ea-8de7-7ac53581829d.png)

**Comment by choldgraf** [comment]
I think it's pretty cool that you're watching the grafanas for us, thanks :-)
