### ISSUE TITLE
Collect information about builds

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#1529]
In #1524, one of the things that occurred was a pretty large number of builds. We should investigate our current resource allocations to builds and model what happens when there are a lot of build requests, to see if there are any changes that should be made there, either in configuration here, or capabilities in BinderHub.

**Comment by betatim** [comment]
Resource consumption by build pods is a tricky thing. I'll try to explain my understanding.

When a build is launched a new pod is spawned that then uses a dockerd to build the requested repository. The spawned pod (named something like `build-org-repo-slug-123`) itself requires nearly no CPU/RAM. All the work is performed in the dockerd. The dockerd is most likely running in a different pod (BinderHub configured to use docker-in-docker (dind)) or on the host itself (BinderHub configured not to use dind). The following only applies to the dind case, I have no experience with the "docker on host" case.

We have one dind pod on each node in the cluster. Each dind pod needs to request (and have a limit of) CPU and RAM. This is where the load comes from during builds. If there are expensive statements in a repos (generated) `Dockerfile` the CPU and RAM limit on the dind pod is what prevents it from consuming too many resources. The resources we request/limit the dind pod to are independent of how many builds are taking places right now.

The build pod itself uses no very little CPU and RAM as it mostly just "commands" the dind pod to perform work. However the number of build pods scales with the number of concurrent builds taking place (one for each build).

My recommendation: configure the dind pod itself to have a modest CPU and low-ish RAM request, enforce a high but not too high limit of CPU/RAM.

Configure each build pod to request a "typical" amount of CPU and RAM. Typical means a realistic amount of CPU and RAM that we want to dedicate to a build. Set the limit for CPU/RAM to the same value as the request.

By making a build pod "consume" resources in the eyes of the k8s scheduler we can trigger a scale up when there are enough build pods running and consuming resources. As I understand it the RAM requested by a pod doesn't get "blocked" from use by other pods. As long as there is spare RAM other pods are free to use it as long as they stay within their limit. Similarly with CPU requests. This means the resources requested by the build pods aren't going to waste. We are requesting them to help the "accounting" of how busy a node really is.

The reason to request some amount of CPU for the dind pod is that the requested amount of CPU is used to compute the "fair share"/relative priority of pods on a node. As I understand it the "spare" CPU of a node is assigned to competing pods based on their requested CPU. So all pods will get some but pods requesting virtually no CPU will have a lower priority than pods requesting more. So by controlling the requested amount of CPU for the dind pod we can control the weight we give to notebook pods and builds.

**Comment by betatim** [comment]
To add another angle to this, repo2docker support limiting the amount of RAM for a build. I think this would apply "inside" the dind pod. So we could use this in a situation where (say) a dind pod has up to 10GB of RAM and we want to limit each individual repo build to use at most 2GB of that 10.

**Comment by minrk** [comment]
That's some great analysis! On further analysis of the incident in question, there actually weren't as many builds as I thought when I opened the issue,  It was actually a large number of build *watchers* which is not the same thing. But I still think your plan is a good one.

Based on your suggestions, I think we can:

1. pick a 'typical' and max number for resource allocations to builds
2. apply modest resource requests to dind pods
3. apply a resource limit on dind that's somewhere in the range of `n_builds_per_node * [typical, max]`
4. use 'typical' value in resource requests on the build pods, even though they don't really use them
5. apply 'max' resource limits on the build pods via repo2docker


Proposed first draft:

```yaml
build:
  request:
    # cpu: builds cannot request or limit cpus independently of dind
    mem: 1G
  limit:
   mem: 2G
dind:
  request:
    cpu: 2 # unchanged
    mem: 1G # reduced from 8Gi
  limit:
    cpu: 5 # unchanged
    mem: 12Gi # unchanged
```

We need https://github.com/jupyterhub/binderhub/pull/1144 to be able to set different requests and limits


Downside: if we aren't careful, the sum(build.request.mem) can easily exceed dind.limit.mem if we set the dind limit too low. A manual, explicit limit of builds per node would help keep those two in sync. The upside is that this should still be strictly an improvement over where we are now, because additional builds are consuming scheduled resources which is not the case today.
