### ISSUE TITLE
📈 2020-08-04 Request to bump resources for Introduction to Conda tutorial at PyCon Africa

### ISSUE THREAD

**Issue by davidrpugh** [jupyterhub/mybinder.org-deploy#1546]
1. Dr. David R. Pugh, Staff Scientist at King Abdullah University of Science and Technology (KAUST); Certified Instructor, The Carpentries.

2. Introduction to Conda for (Data) Scientists: This lesson is an introduction to Conda for (data) scientists. Conda is an open source package and environment management system that runs on Windows, macOS and Linux. Conda installs, runs, and updates packages and their dependencies. Conda easily creates, saves, loads, and switches between environments on your local computer. While Conda was created for Python programs it can package and distribute software for any languages such as R, Ruby, Lua, Scala, Java, JavaScript, C/ C++, FORTRAN. This lesson motivates the use of Conda as a development tool for building and sharing project specific software environments that facilitate reproducible (data) science workflows.

3. No money is changing hands.

4. https://github.com/carpentries-incubator/introduction-to-conda-for-data-scientists/tree/binder

5. What type of event it is:
- [ ] talk
- [X] workshop
- [ ] lecture course
- [ ] training session

6. Have been told to expect 200-300 participants.

7. 08/04/2020 from 2 pm - 4 pm West Africa Time (WAT).

8. Will be thanking mybinder.org at the start and end of the event.

**Comment by betatim** [comment]
Let us know how it goes on the day

**Comment by davidrpugh** [comment]
Thanks @betatim will let you know how it goes!
