### ISSUE TITLE
Check in on cert-manager on prod after 2020-09-15

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#1589]
We upgraded cert-manager in #1582, which went smoothly! However, we won't really know if everything worked until cert-manager starts trying to issue new certificates. The first certs to expire (I believe) are on prod, expiring on 2020-10-15, which means renewal should start on 2020-09-15 or a little after. We should check on cert-manager on prod around this time to make sure everything is happy.

**Comment by minrk** [comment]
cert-manager has issued new certificates as it was supposed to

**Comment by sgibson91** [comment]
I think turing is now suffering from invalid certs if the hubup app is to be believed
