### ISSUE TITLE
terraform for deploying clusters

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#1595]
Provisioning of cloud resources themselves is not yet automated, which is coming up now as we discuss some possible shifts in deployments which could mean redeploying our GKE clusters. We have manually deployed things (SQL server for matomo, buckets for analytics, clusters) so far, but it would make transitions like this easier if we could use terraform to automate this. If nothing else, it would serve as documentation for what we've actually deployed!

On gitter, folks have been discussing using terraform for this step, and several folks have had positive experiences with this in the last year.

**Comment by yuvipanda** [comment]
Trying to list the bits of cloud infrastructure we need that aren't handled by helm / deploy.py.

1. GKE Cluster itself
2. NodePools for the Cluster
3. Container Registry
4. Stackdriver config for analytics (and buckets too? I'm not sure)
5. SQL Server for Matomo
6. Reserve the load balancer IPs so we don't lose them during cluster re-creates
7. Service Accounts + keys for various things

**Comment by manics** [comment]
I've used it for a test project and liked it's usability. The main downside from a team perspective is it requires a persistent tfstate file that has to be saved after every run and shared amongst anyone who wants to update the deployment. There's several ways to automatically share the tfstate file but I've never used them, this is one of the main reasons I'm not using it in production.

Terraform won't incorporate resources created outside the tfstate file (at least it didn't last time I used it), in contrast to some other tools such as Ansible which take your existing state into account. OTOH if it's designed for "one-off" use where it's only used to create the infrastructure but not update it this could be quite a nice way to get started with a new cluster.

**Comment by yuvipanda** [comment]
> There's several ways to automatically share the tfstate file but I've never used them, this is one of the main reasons I'm not using it in production.

I've used https://www.terraform.io/docs/backends/types/gcs.html for this. Was fairly trivial to set up, and worked pretty flawlessly after!

**Comment by minrk** [comment]
> Terraform won't incorporate resources created outside the tfstate file (at least it didn't last time I used it)

It can with [terraform import](https://www.terraform.io/docs/import/index.html) I used this a couple of times in the spring. It's not perfect and a bit tedious, but it can work.

**Comment by minrk** [comment]
> I've used https://www.terraform.io/docs/backends/types/gcs.html for this

We also stored tfstate on azure storage as soon as we had two folks deploying, and it worked well, so I think we should go the GCS route from the start.

**Comment by betatim** [comment]
An existing terraform chart/recipe (what do we call them?) https://github.com/neurolibre/terraform-binderhub (via https://twitter.com/agahkarakuzu/status/1303405216906313729)

**Comment by betatim** [comment]
Does someone want to tackle creating a terraform recipe for setting up a staging cluster?

**Comment by minrk** [comment]
@betatim I started at #1604. The cluster is running, we just need the service account(s) for deployment and the SQL server for matomo.

**Comment by minrk** [comment]
btw, that linked terraform module is for deploying binderhub *on kubernetes*, i.e. automating what we already have automated in deploy.py. The cluster bootstrapping they have is only manual deployment of kubernetes with kubeadm on nodes provisioned via openstack/jetstream, not managed kubernetes. In short: it's great for folks who want binderhub and are either using openstack or already have kubernetes, but is missing the same automation steps we are trying to fill.

We *could* move everything over to terraform, including our calls to helm and/or kubectl, but I don't actually think we should. I think scoping it to just the gcloud resources (cluster, VMs, service accounts) and then using our helm stuff is going to be more pleasant, and certainly smaller task for now.

**Comment by yuvipanda** [comment]
> We _could_ move everything over to terraform, including our calls to helm and/or kubectl, but I don't actually think we should. I think scoping it to just the gcloud resources (cluster, VMs, service accounts) and then using our helm stuff is going to be more pleasant, and certainly smaller task for now.

Big +1!

**Comment by minrk** [comment]
The new GKE clusters, service accounts/roles, GCS buckets, and SQL servers are all deployed with terraform now.

The only things not automated at this point are:

- reservation of static IPs (IPs reserved with terraform could not be used by the GKE load-balancer for some reason)
- initial install of helm itself, which is only a few lines and very rarely done. I think it should also go away when we move to helm 3, so may not need to be run again anyway
