### ISSUE TITLE
Setting up `gke2.mybinder.org` (migrate gke.mybinder.org to new project)

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#1596]
Wanted to start this issue to discuss the migration from our current GCP projects (binder-prod, binder-staging, binder-sandbox) to the new GCP project we have.

Is there anything to do for binder-sandbox? I've not used it in forever and don't know off things that live there. I assume all of them can be turned off/deleted though. It is a sandbox after all. I would also not re-create a sandbox for now in the new project.

For binder-staging we need to create a new GKE cluster with all the trimmings. A new thing is that we need to pick a prefix for the image registry that doesn't interfere with binder-prod. Right now staging and prod have their own registries. If we can create multiple registries in one project we should consider that. I'd propose we try to set it up as `staging2.mybinder.org`, add it to our `deploy.py` and when we have confidence that it works turn off `staging.mybinder.org`.

For binder-prod we need to do everything we need to do for binder-staging and more:
* setup logging (we have some filters/excludes to reduce ingested log volume to keep costs down)
* setup launch analytics (with support for receiving events from other clusters like OVH and Gesis)
  * transfer the existing events/data from the old analytics instance
* setup matomo
  * do people actively use it? I still use GA on the rare occasion that I look at analytics. If no one loves using it maybe we can save some effort and not migrate it?
  * needs a SQL database and proxy
  * transfer existing data
* transfer the grafana boards/config (we probably don't need the data)
* transfer the federation redirector

I'd propose that we setup the new "prod" instance BinderHub as `gke2.mybinder.org` and add it to `deploy.py` and the federation redirect as soon as we can. Basically we pretend it is just another cluster joining the federation. Then we can start working on setting up/transferring the "support infrastructure" (logging, analytics, etc) one by one. At some point we will have everything running on the new cluster (hopefully).

xref https://github.com/jupyterhub/mybinder.org-deploy/issues/1595 which is about setting up terraform recipes(?) to help setup infrastructure.

What do people think?

---

please edit this post's lists if you want to help flesh them out/correct things/add missing things

**Comment by manics** [comment]
How often do the Grafana dashboards change? For other projects I've uploaded the dashboards to https://grafana.com/grafana/dashboards, the Grafana Helm chart can automatically pull dashboards from there (you pass it the online dashboard id): https://github.com/grafana/helm-charts/tree/main/charts/grafana#import-dashboards

The main downside is it's more work to modify a dashboard.

**Comment by minrk** [comment]
> Is there anything to do for binder-sandbox? 

No, there's nothing there in general, it's only used for ad-hoc testing. In the single-project setup, we will just use the new project for these now.

👍 to setting up a new staging cluster first on the new project and migrating to it in deploy.py, also 👍 to setting up the new prod cluster as an *additional* cluster before tearing down the current one.

I think it would be great to try to do this in terraform, even if we don't set up terraform to run in CI (terraform mistakes can be *super* destructive, so running with the human confirmation step until we are very confident in what changes are safe is prudent). But at the same time, we do have a relatively short timeline and figuring out terraform will make this take longer.

**Comment by minrk** [comment]
> How often do the Grafana dashboards change?

They tend to go pretty long periods without updates, but then can get a lot of little tweaks. I think it's probably good to publish our charts this way periodically, but I think *only* relying on the published chart id might be too much.

**Comment by minrk** [comment]
GKE2 is up and running, and taking a tiny bite slice of the federation as of #1617 ! I successfully migrated matomo data so we haven't lost any analytics there, and I have manually migrated the events archive history with:

```python
gsutil -m rsync gs://mybinder-events-archive gs://binder-events-archive
```

Still to do:

- [ ] monitor new cluster for issues
- [ ] increase new cluster capacity
- [ ] migrate some prometheus data, if possible, if we care (maybe we don't?)
- [ ] migrate grafana dashboards
- [ ] start logging to new events archive (I don't see a way to not lose *some* events during the transition, but hopefully not much)
- [ ] migrate DNS so that gke2 serves the top-level mybinder.org domain

Tricky bits:

- letsencrypt needs dns updated to issue certs, but won't have valid certs for a short time after DNS is updated. This means that I think we'll have invalid SSL downtime on mybinder.org for a (hopefully short) period. I can manually retrieve wildcard certs via DNS verification, but temporarily injecting them while cert-manager works itself out seems iffy and possibly prone to more serious error.
- coordinating event-log updates to minimize lost events

@bitnik how does GESIS configure event-logging? It will need new credentials and a new log endpoint for the new cluster when the time comes, but that's not deployed from here.

**Comment by betatim** [comment]
This is super cool!!

I don't care about the prometheus data. In the past we've had to delete it when the PV it is stored on filled up and no one ever asked/remarked on the fact that "data seems to be missing". So I'd say most other people also don't mind.

For the let's encrypt tricky bit: right now mybinder.org resolves to 1.2.3.4 (old GKE), browsers visit it and get a good cert. On the new GKE we can't obtain a cert until after we update the DNS record for mybinder.org to point at 5.6.7.8 (new GKE). Once we update the DNS record (and wait a short moment) the new GKE cluster will be able to obtain a certificate. However there is a short window in time where my browser will already visit the new GKE but it doesn't have a cert yet. This means I will get a warning from my browser about invalid certificates.

I typed it out in my own words to check if that I understood it. Is it right?

If yes it sounds like that time window would be pretty short (a few minutes?) if we coordinate updating the DNS record and forcing a cert refresh on the new GKE cluster. I'd be Ok with us doing that early in the European day and having a few minutes of downtime. The alternative sounds like it would take a lot of your human time, so unless it is a skill you want to learn/get experience with I'd vote for a short down time.

**Comment by minrk** [comment]
> Is it right?

Yes, exactly right.

>  it sounds like that time window would be pretty short

It *should* be short, hopefully around 5-15 minutes, but one never knows with DNS. Plus, we have to be a little careful with the presumable failure back-off if we switch the cluster before we switch DNS because the retry interval will probably get longer after the first few tries fail. That could add to the time.

I think doing it EU AM should be fine. Let's maybe aim for Thursday?

I'd like to get the events archive logging moved today, if we can.

**Comment by minrk** [comment]
after #1620 (and #1624) events are now being logged to the new events archive by gke, ovh, and gke2. Could have been as much as ~30-40 minutes of events dropped in between. GESIS will need to be updated to match (#1625)

**Comment by minrk** [comment]
Everything's moved over and seems to be running fine. The events archive and Grafana dashboards have migrated well, so I think there isn't anything precious on binder-prod anymore. I think we should remove binder-prod from the federation on Monday morning and shut it down late Monday / early Tuesday so we can shut down the `binder-prod` project Tuesday or Wednesday at the latest, so there's a comfortable amount of time to spare before it starts charging @choldgraf money at the start of October, which is Thursday.

**Comment by choldgraf** [comment]
amazing, thanks so much for putting in the time to get this switched over, it makes me much less stressed out :-)

**Comment by minrk** [comment]
GKE1 is now drained, with 0 user pods running. I think we can delete the `binder-prod` project tonight or tomorrow and be totally done with the migration.

**Comment by choldgraf** [comment]
I feel like we should have a ceremony of some kind haha. `gke`, you served us well 🖖

**Comment by betatim** [comment]
Looking into why https://archive.analytics.mybinder.org/ stops at 24th September. It looks like generating the new `index.html` fails.

**Comment by betatim** [comment]
Fixed now. A few of the `jsonl` files had lost their metadata when they got "hand merged" to take care of dropped events. Added tat back by hand which made the indexer happy.

We also restarted the GCS proxy as it kept serving an old version of the index page. Not quite sure why but a restart fixed it.

**Comment by minrk** [comment]
FWIW, a restart *did not* fix it, it was still serving the old file for a while after restart. But at some point the GS CDN (or whatever) got all in sync and the updated version started being served.

Going to shut down binder-prod now.

**Comment by minrk** [comment]
@choldgraf I think you might be the only one with a view on the old billing account, but I believe everything is now shutdown on all the `binder-` projects. Let us know if you see anything active that still might be billing to that account.
