### ISSUE TITLE
2020-10-15 bump resources for coiled/data-science-at-scale to 500

### ISSUE THREAD

**Issue by hugobowne** [jupyterhub/mybinder.org-deploy#1605]
### 1. Who you are

Hugo Bowne-Anderson, working with [Coiled](coiled.io/), long-time Python user, Binder / Jupyter fan

### 2. A few details about the event/course/context

Live coding session on DataCamp's FB page! Teaching a bunch of Dask-y distributed stuff. 

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

No money.

### 4. A link to the repository you are using

https://github.com/coiled/data-science-at-scale

### 5. What type of event it is:
- [ ] talk
- [ ] workshop
- [ ] lecture course
- [ ] training session
- [x] online live coding session

### 6. How many people you expect to attend the event

Thousands will likely attend. Perhaps several hundred will attempt to connect using binder.

### 7. The exact times and dates of the event(s) (with timezone information)

4pm ET on 10/15

### 8. How do you plan to give mybinder.org a shout out at the event

Continually communicating that Binder is the go-to PyData stack & Jupyter way of spinning up labs // notebooks in executable & reproducible environments at the click of a button // badge.

**Comment by betatim** [comment]
@hugobowne can/do you want to make a PR to do this so we can just press merge on it? That would greatly facilitate our laziness :)

**Comment by hugobowne** [comment]
@betatim I messed up the date here and we have already had the session!

It went well.
