### ISSUE TITLE
add GESIS to the new production cluster

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#1625]
Migrating to a new production cluster has revealed some missing automation for the GESIS cluster. In particular, this means:

- [ ] gesis prometheus data source credentials need to be re-added and do not appear to be stored in this repo (this should be fixed by adding it to its own file in secrets/, or in grafana config in secrets/config/prod-gke2.yaml)
- [ ] new credendials for publishing events. This file is now available for gesis in this repo at `secrets/events/gesis.json` and needs to be added to the gesis deployment in order to publish events to the new archive

The most pressing one is getting the updated secret for events-archive because publishing to two events lists is a bit of a pain to reconcile (if it's a small number of lost events, I don't think we should bother).

/cc @bitnik @arnim

**Comment by bitnik** [comment]
hi @minrk, we shared both of them in keybase with @betatim . 

I just tried to create a new private folder including you, but no success and I am not sure what I am doing wrong. Could one of you do it? Or do you prefer another way?

**Comment by minrk** [comment]
@bitnik I think I had to follow you back, should work now. I put the events-publisher key in there.

**Comment by minrk** [comment]
Confirmed that GESIS is publishing events to the new archive as of five minutes ago and the prometheus creds are now stored ina. secret (#1632)
