### ISSUE TITLE
DESI High @ Bay Area Science Festival. 

### ISSUE THREAD

**Issue by michaelJwilson** [jupyterhub/mybinder.org-deploy#1656]
# 1. Who you are
Mike Wilson, postdoc. at Lawrence Berkeley National Lab. @michaelJwilson.

### 2. A few details about the event/course/context
[DESI High](https://github.com/michaelJwilson/DESI-HighSchool) @ the [Bay Area Science Festival](https://www.bayareasciencefestival.org/) on Sat., Oct 24th 2020.

We're running two sessions in parallel, in [English](https://www.bayareasciencefestival2020.org/event/desi-high-teaching-teenagers-dark-energy-with-hot-off-the-telescope-data/) (requires registration to access) and in [Spanish](https://www.bayareasciencefestival2020.org/event/desi-high-jovenes-aprendiendo-energia-oscura-con-datos-directos-del-telescopio/)

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
No

### 4. A link to the repository you are using
https://github.com/michaelJwilson/DESI-HighSchool

### 5. What type of event it is:
- [x] talk
- [ ] workshop
- [ ] lecture course
- [x] training session

### 6. How many people you expect to attend the event
We can cater to ~ 200 students if Binder allows.

### 7. The exact times and dates of the event(s) (with timezone information)
9 am - 6pm on Sat. Oct. 24th (leeway either side of the event). 

### 8. How do you plan to give mybinder.org a shout out at the event
We'll be, and have been, advertising Binder widely.  Specific requests welcome.

**Comment by betatim** [comment]
This sounds like a cool event!! I am going to see if my (old) particle physics knowledge is good enough to make some sense of the repo content :D 

There is a PR that increases the resources that should get merged in time for the event

**Comment by michaelJwilson** [comment]
:) thanks!  I'm sure you'll be all set!  We'll be adding more for you to get your teeth into at a later stage, once we have all the material for these events set up.

**Comment by michaelJwilson** [comment]
Thanks!

**Comment by michaelJwilson** [comment]
Morning @betatim, would it be possible to get an allocation limit of 150 for 17, 24 Feb. and Mar 3?  We're holding similar events in partnership with [unam](https://www.unam.mx/).  Thanks!

**Comment by betatim** [comment]
Thanks for letting us know. Sounds fine to me.

I think there is nothing for us to do other than wait longer to undo the allocation.

**Comment by michaelJwilson** [comment]
:) great, thanks for your help.
