### ISSUE TITLE
2020-10-20 Request to bump resources for Introduction to Python for Data Science training

### ISSUE THREAD

**Issue by davidrpugh** [jupyterhub/mybinder.org-deploy#1657]
1. Dr. David R. Pugh, Staff Scientist at King Abdullah University of Science and Technology (KAUST); Certified Instructor, The Carpentries.

2. Introduction to Python for Data Science: This lesson is an introduction to programming in Python for people with little or no previous programming experience. It uses plotting as its motivating example, and is designed to be used in both Data Carpentry and Software Carpentry workshops. This lesson references JupyterLab, but can be taught using a regular Python interpreter as well.

3. No money is changing hands.

4. https://github.com/kaust-vislab/introduction-to-data-science-workshop

5. What type of event it is:
- [ ] talk
- [X] workshop
- [ ] lecture course
- [ ] training session

6. Have expecting between 100 and 200 participants. Most of whom will be female students from King Fahd University of Petroleum and Minerals (KFUPM) in Saudi Arabia.

7. 2020-10-20 from 8:30 am - 5 pm Arabian Standard Time (AST) (UTC+3).

8. Will be thanking mybinder.org at the start and end of the event.

**Comment by choldgraf** [comment]
Ooops - I just saw that this is in the past 😬 - has it already happened @davidrpugh ??

**Comment by davidrpugh** [comment]
Yep. Didn’t have any issues though so it’s all good. Any idea what the standard max number of concurrent users for a repo?

**Comment by choldgraf** [comment]
Yep, it is 100 concurrent sessions. Glad that you had an ok experience!

**Comment by choldgraf** [comment]
I am gonna close this one as I think it's been "resolved" - I am glad that things still went well for you even though we failed to bump the resources!
