### ISSUE TITLE
Let's Encrypt incorrectly notifying us about expiring domains

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#1668]
We received an email from letsencrypt (LE) notifying us that the certificates from the following domains will expire on 15. November 2020:
* archive.analytics.mybinder.org
* gke.mybinder.org
* hub.gke.mybinder.org
* hub.mybinder.org
* static.mybinder.org

I checked static.mybinder.org and the current certificate we have on the cluster is set to expire on 2020-12-23. Checking https://crt.sh/?q=static.mybinder.org shows that certificate as well as one that will expire on 2020-11-15. This is a bit weird/interesting. Normally LE is good at knowing that you've renewed your certs but in this case something went wrong and they can't tell that we have a new cert for the domain already. Any ideas what we can investigate to figure out why? (Mostly worried we will get a lot of false alarm emails which will train us to ignore them and then one day a real one will slip through).

Overall I think we can ignore the warning from letsencrypt. What is

**Comment by minrk** [comment]
I think this relates to the deployment to the new cluster, which meant cert-manager requested *new* certs for these domains instead of renewing the existing ones. So those old certs (which are lost in the ether) are still valid and going to expire instead of having been renewed.

**Comment by minrk** [comment]
All of which means this should be a one-time thing and we shouldn't expect it to occur again until the next time we request *new* certs instead of renewing certs, presumably due to our next migration to a fresh cluster.

**Comment by betatim** [comment]
Ok. I think that makes sense. I had thought LE was super smart and they'd be able to notice that we got new certificates instead of renewing.

Closing this as I think we think this won't happen regularly.
