### ISSUE TITLE
Ensure we have up-to-date HTTPS certs

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/mybinder.org-deploy#1699]
Let's encrypt expiry bot has messaged the binder-team emailing list the following.

----

Hello,

Your certificate (or certificates) for the names listed below will expire in 10 days (on 15 Nov 20 04:32 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.

We recommend renewing certificates automatically when they have a third of their
total lifetime left. For Let's Encrypt's current 90-day certificates, that means
renewing 30 days before expiration. See
https://letsencrypt.org/docs/integration-guide/ for details.

archive.analytics.mybinder.org
gke.mybinder.org
hub.gke.mybinder.org
hub.mybinder.org
static.mybinder.org

---

I'm not 100% this is a problem. It will be a problem if we have no valid certs, but it may be a non-problem if we have two separate sets of certs and this only regard a set no longer in use.

**Comment by manics** [comment]
It's a side-effect of the cluster migration, see https://github.com/jupyterhub/mybinder.org-deploy/issues/1668

**Comment by consideRatio** [comment]
Ah excellent thanks @manics!
