### ISSUE TITLE
ESiWACE2 DSL Training for climate & weather model developers

### ISSUE THREAD

**Issue by BenWeber42** [jupyterhub/mybinder.org-deploy#1701]
Dear mybinder.org developers,

I'd like to request an increase in resources for our upcoming training course :)
### 1. Who you are

[MeteoSwiss](https://www.meteoswiss.ch)

### 2. A few details about the event/course/context

This is a training course targeting developers of climate & weather models. The goal is to show domain scientists how domain specific languages can be used to gain performance portability without sacrificing productivity. Performance portability allows to run bigger simulations on stronger machines which leads to improved weather forecasting and climate predictions.

The training course is offered by ESiWACE (Centre of Excellence in Simulation of Weather and Climate in Europe)

More specifically:
https://www.esiwace.eu/events/esiwace2-dsl-training/esiwace-2-domain-specific-language-dsl-training

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

Free/None

### 4. A link to the repository you are using

https://github.com/dawn-ico/dusk-dawn-notebook

Related Software:
dusk: https://github.com/dawn-ico/dusk
dawn: https://github.com/MeteoSwiss-APN/dawn

### 5. What type of event it is:

- [ ] talk
- [ ] workshop
- [ ] lecture course
- [x] training session

### 6. How many people you expect to attend the event

We will end up with roughly 90 - 110 registered participants. Of course, it's unlikely that all will turn up, but I think 60 - 80 people using the notebooks is realistic.

### 7. The exact times and dates of the event(s) (with timezone information)

Nov 25: 13:30 - 18:00
Nov 26: 09:00 - 18:00
Nov 27: 09:00 - 15:00
All times in Europe/Vienna / UTC100

### 8. How do you plan to give mybinder.org a shout out at the event

We will have a small slide set introducing how to use mybinder to do the exercises. One slide is dedicated to acknowledge and thank for your support. It currently contains the four logos of the binderhub federation (https://mybinder.readthedocs.io/en/latest/about/federation.html). Not sure if I'm missing important contributors. Guidance here is very much welcome :)

Thanks a lot for all the support so far and the great service!

**Comment by choldgraf** [comment]
Hey @BenWeber42 - thanks for reaching out! Just a note that the current repository limit for Binder is 100 users, so if you're only expecting ~100 users on the day of, and it's unlikely all will be using Binder at once (in our experience with workshops, it's more like 70-80% that actually click the binder links etc), then you shouldn't have a problem hitting the limit. That said, if you still prefer we could bump it to 150 users. Let us know!

**Comment by BenWeber42** [comment]
Thanks for the answer. You're right, that we might stay within 100 concurrent users limit.
However, the documentation advises to open an issue already if more than 50 users are expected (https://mybinder.readthedocs.io/en/latest/about/user-guidelines.html#running-events-with-mybinder-org).

The main reason I opened the issue, is that I feel like we might come fairly close to that limit if our audience turns out to be quite motivated. I agree, it's not necessarily expected, but I also feel like, we can get pretty close if we're _unlucky_. If it could be bumbed to say 120 or 150 concurrent users, that would be much appreciated.
:slightly_smiling_face:

**Comment by betatim** [comment]
If you want to increase the limit to be on the safe side and feel up to it: a Pull Request like https://github.com/jupyterhub/mybinder.org-deploy/pull/1658/files is one I'd merge.

(Gruesse aus der Naehe von Zuri)

**Comment by BenWeber42** [comment]
Thanks a lot @betatim !

(Gruesse zurueck aus Zuri :slightly_smiling_face:  )
