### ISSUE TITLE
binderhub chart not available in https://github.com/helm/charts/

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#1706]
Any ideas why https://github.com/jupyterhub/mybinder.org-deploy/pull/1705/checks?check_run_id=1416619783 (#1705) this keeps happening? When we run our checks they fail to fetch the binderhub chart from our helm chart repo. When you restart them they work.

Could it be that they execute "too quickly" after we publish the chart or before the chart has been published?

If the issue is "runs too soon" my only idea is to add a `sleep and retry` to the check to automate the manual step of "click restart, come back later" step.

**Comment by manics** [comment]
Do you have a link to the failed build log? When you rerun the job it updates the existing check instead of creating a new one.

How does henchbot work- does it get the chart version from the git repo, or from the helm-chart website after its published
https://jupyterhub.github.io/helm-chart/index.yaml
which should rule out slow publication unless there's some outdated caches?

**Comment by betatim** [comment]
I think henchbot runs ever 10(?)minutes and for BinderHub looks at the chart repo `index.yaml` to find out if there is anything new. For repo2docker it inspects the source code repo. https://github.com/henchbot/mybinder.org-upgrades/blob/fe7c5af057d6226e35b26dc1effc21307e63320c/src/mybinder-upgrades/henchbot.py#L335

What is weird is that the error isn't "that version of your chart doesn't exist" but "the chart itself doesn't exist" :-/ Which should never happen, unless maybe the `index.yaml` somehow contains a syntax error?

**Comment by manics** [comment]
I've opened https://github.com/henchbot/mybinder.org-upgrades/pull/4 to switch to using the published GitHub pages `index.yaml`.

**Comment by consideRatio** [comment]
This seems like a closed issue, if not, it needs clarification
