### ISSUE TITLE
[BUG] Binder health endpoints on Turing and OVH different to GKE

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/mybinder.org-deploy#1720]
CI tests for binder health on Turing and OVH are currently failing due to an "I expected JSON but got something else" error which is corroborated by visiting the following links.

* https://gke.mybinder.org/health
* https://ovh.mybinder.org/health
* https://turing.mybinder.org/health

As you can see, GKE is the only one correctly returning a JSON object whereas OVH and Turing have HTML responses.

**Comment by minrk** [comment]
hmmm!

two things:

1. even failures should return json errors, not html pages. This needs to be handled in `write_error` in `binderhub/base.py`. We do this in jupyterhub, jupyter/notebook, etc.
2. the actual error appears to be a failure to list pods. On ovh, it's failing with:

```
 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.3.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/ovh/pods?labelSelector=app%3Djupyterhub%2Ccomponent%3Dsingleuser-server (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
```

not sure what's up there. Seems like it should work if k8s api calls are working at all.

**Comment by minrk** [comment]
turing is also failing in a similar but not quite identical fashion:

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.0.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/turing/pods?labelSelector=component%3Dbinderhub-build (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))
```

**Comment by minrk** [comment]
Aha! I think I messed this up in https://github.com/jupyterhub/binderhub/pull/1192 where one failed check might get re-used instead of re-tried if `this await` fails. Need to think...

**Comment by sgibson91** [comment]
> 2. the actual error appears to be a failure to list pods.

This should now be fixed by https://github.com/jupyterhub/binderhub/pull/1220 which will go live via #1719

**Comment by sgibson91** [comment]
The bug wasn't _actually_ fixed because the new binderhub image wasn't pushed on merge of jupyterhub/binderhub/#1220, this is due to a regression in chartpress. But once the updated image is available, then this issue should be close-able. I will open an issue on jupyterhub/binderhub regarding the JSON/HTML problem.

**Comment by consideRatio** [comment]
Closing this as the health endpoints are not functional and Min's other identified issue about HTML being used instead of JSON is tracked in jupyterhub/binderhub#1221
