### ISSUE TITLE
Remove unused tags to become chartpress/helm3 compliant?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/mybinder.org-deploy#1725]
- This repo has three tags in it, [prod](https://github.com/jupyterhub/mybinder.org-deploy/tree/prod)/[staging](https://github.com/jupyterhub/mybinder.org-deploy/tree/staging)/[beta](https://github.com/jupyterhub/mybinder.org-deploy/tree/beta), all several years old.
- `chartpress` rely on tags to deduce a Chart.yaml version to set and image tags to set.
- Helm 3 requires published charts to follow SemVer2.
- `chartpress` 1.0.0+ validates the deduced version to be valid SemVer2.
- Currently with our tags in this repo, we get a deduced version from chartpress like `prod-n2521.hed24c88`.
- We can make `chartpress` deduce a semver2 valid version by removing these tags for example.

I suggest that we delete the several years old prod/staging/beta, and tag the commit that introduced Chart.yaml with 0.1.0. Would that be okay?

## Can I do this?

```shell
# Delete the remote tags that influence the version
# decided by chartpress, which preferably is a valid Semver2
# version which it isn't with these tags around.
git push origin --delete refs/tags/beta
git push origin --delete refs/tags/prod
git push origin --delete refs/tags/staging

# Tag the commit introducing the Chart.yaml file, which was the
# commit where the 0.1.0 version was introduced in it as it
# currently is set.
git tag -a 0.1.0 -m 0.1.0 8ff8b82
git push origin refs/tags/0.1.0
```

## References
Only the images [mybinder-tool-federation-redirect](https://console.cloud.google.com/gcr/images/binderhub-288415/GLOBAL/mybinder-tool-federation-redirect?gcrImageListsize=30) and [mybinder-tool-analytics-publisher](https://console.cloud.google.com/gcr/images/binderhub-288415/GLOBAL/mybinder-tool-analytics-publisher?gcrImageListsize=30) will be influenced by getting a new version tag as far as I know.

**Comment by betatim** [comment]
Seems like we used these tags way back when we still had a `prod` and a `staging` branch. See #367 for some history on this.

I think it is safe to remove them.

Could we also add an option to chartpress to not do what ever new thing it is doing? It would be the "the setup we have has worked for a long time, so why change it now" option.

I think I'd remove them.

**Comment by consideRatio** [comment]
Nice tracking this down @betatim! The tags were pointing to the tip of branches that are now deleted it seems.

> [...] I'll also archive the 'staging' and 'production' branches to tags, and we'll just be using the familiar 'master' branch. - quote from https://github.com/jupyterhub/mybinder.org-deploy/pull/367#issuecomment-365424558

## Suggested action plan - sounds ok?
1. Remove the tags (prod, staging, beta)
2. Add a tag (0.1.0) tagging a commit on master branch later than the previous tags, for example b9317cf.
   It is practically helpful to tag a commit after the previous tags, as it will make it be prioritized by chartpress over the older tags which may remain on local clones.

## Backup info: the removed tags pointed to these commits
- prod tag: 3665d10
- staging tag: 6984ac6
- beta tag: af039b7

---

> Could we also add an option to chartpress to not do what ever new thing it is doing? It would be the "the setup we have has worked for a long time, so why change it now" option.

@betatim I understand you don't perceive this as helpful by chartpress, but it is a loud failure with intent. I consider the current chartpress functionality to be a desired compromise now that helm3 enforce charts being packaged to be published to a Helm chart repo to have semver2 compliant version fields.

If you deem it be better overall to warn rather than fail, which I think would benefit human users of chartpress and be a drawback for CI system usage of chartpress during a helm2->helm3 transition, then I'd be happy to merge on a chartpress PR about it.

**Comment by minrk** [comment]
I've no objection to the action plan, but if I understand, we could also fix this by only adding a tag for today, e.g.`git tag -am 2020.12.4 HEAD`. This repo doesn't and won't likely ever have meaningful version numbers, so specifying that some version was 0.1.0 isn't more useful than specifying the same version today or any other day, as long as it's valid and the most recent tag returned by `git describe`.

The chart version validation is a bit overzealous, I think, but it makes sense when publishing charts. mybinder.org here is not publishing charts, though, so I think it makes sense to only apply the strict enforcement at the publish stage (which mybinder.org doesn't have and thus wouldn't hit). I've opened https://github.com/jupyterhub/chartpress/pull/109 to that effect.

**Comment by consideRatio** [comment]
Thanks @minrk!

- I removed the prod/staging/beta tags
- I pushed a 2020.12.4 tag (important to not have a leading 0 for semver btw).
- I created #1728 to go back to chartpress 1.0.* again as attempted before but require at least 1.0.2

**Comment by betatim** [comment]
I was thinking of having a CLI flag that we can pass to chartpress to say "hey, we know this is dangerous but we are doing it on purpose please don't fail on none semver compliant versions" as a way to have the default be what publishers of charts want but give an escape hatch to the other big group of users which don't want to publish. I like Min's PR.

**Comment by minrk** [comment]
@betatim yeah, I thought about that  as well, since it creates a difference between the test environment and deploy environment, meaning less than everything is tested in a PR. Putting the strict version check in that behind a `--strict-version`  flag that starts with `strict_version = publish` by default instead of hardcoded as I made it makes sense to me.

**Comment by betatim** [comment]
The next step would be to create a ticket/PR in chartpress right?

**Comment by consideRatio** [comment]
@betatim @minrk I think adding a flag to make this warning an error during build to add more complexity both for chartpress users and developers than merits its value both for users and developers. But, if we do add a flag, I think the flag should be made to opt-out of the strict version check rather than to opt-in.

**Comment by betatim** [comment]
Agreed that the flag should be to disable the strict behaviour. It is a way for the user to say "I know that I am doing something potentially dangerous, but I am a consenting adult so it won't be your fault when it goes wrong."

**Comment by consideRatio** [comment]
@betatim I'm a bit confused because of the ambivalence of "strict behavior". I consider two situations with three outcomes:

- situations: chartpress is packaging a chart, or chartpress is doing something less critical, or is doing something entirely different.
- outcomes: chartpress provides no warning, a warning, or raises an error.
