### ISSUE TITLE
Request to bump resources for workshop on accessing NASA astrophysics archives

### ISSUE THREAD

**Issue by stargaser** [jupyterhub/mybinder.org-deploy#1748]
### 1. Who you are

David Shupe, Scientist for the InfraRed Science Archive at Caltech/IPAC. I am also a member of the Proceedings Committee for SciPy (2019, 2020, 2021) and a member of the Astropy Project.

At SciPy 2020 I attended the Xarray tutorial, where I learned that it is possible to ask for a bump in resources for a workshop or tutorial.

### 2. A few details about the event/course/context

At the online 237th meeting of the American Astronomical Society, we are holding a workshop "Using Python to Search NASA's Astrophysics Archives". We primarily show how to use the pyvo package, along with Scientific Python packages including astropy and matplotlib, to find, download and visualize astronomical data from NASA space observatories. We have a repository of Jupyter notebooks and we have a "launch:binder" badge on the top-level README.

The workshop is listed on the page https://aas.org/meetings/aas237/program -> Workshops ->  Friday, 8 January at the end.

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

The American Astronomical Society is charging $25 per participant to cover costs associated with these online events. The workshop organizers do not receive any funds.

### 4. A link to the repository you are using

https://github.com/NASA-NAVO/navo-workshop

### 5. What type of event it is:
- [ ] talk
- [ x ] workshop
- [ ] lecture course
- [ ] training session

### 6. How many people you expect to attend the event

We have set a limit of 50 participants.

### 7. The exact times and dates of the event(s) (with timezone information)

The workshop will be held on Friday, 2021 January 8, from 3:00pm to 5:00pm Eastern Standard Time.

### 8. How do you plan to give mybinder.org a shout out at the event

We will advertise the support from mybinder.org in the opening presentation we will make at the workshop.

**Comment by betatim** [comment]
Hey 👋 !

If your workshop will have a limit of 50 participants you should be good to go already. The default limit is 100 live instances per repository.

**Comment by stargaser** [comment]
Thanks @betatim, I understand the 100 limit now, and that we don't need a bump in resources for that.

I want to ask about session timeouts. I [read here](https://mybinder.readthedocs.io/en/latest/about/about.html#how-long-will-my-binder-session-last) that sessions time out after ten minutes of inactivity. We're worried about cases where the workshop has a 15-minute break, and a participant comes back to find their work has been lost. To prevent this, would they leave their focus on the browser tab for their Binder session? Is it not possible to lengthen the timeout for a specific repository for a workshop event?

**Comment by sgibson91** [comment]
There's some info in [this comment](https://github.com/jupyterhub/mybinder.org-deploy/issues/1717#issuecomment-739720368) about culling times, why it's not simple to change them and some mitigating actions :)

**Comment by stargaser** [comment]
Thanks @sgibson91 , that helps a lot!

I also found some discussions on Discourse about [Pycon 2019 experience](https://discourse.jupyter.org/t/pycon-2019-and-mybinder-org/920) and [reducing startup times](https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956). I want to implement some of those suggestions, including the [nbzip Jupyterlab extension](https://github.com/data-8/nbzip) so the workshop participants can save their work easily.

I'll close this issue -- thanks all for the clarifications!

**Comment by betatim** [comment]
If you find a mixture of all the linked advice above and have some spare time I think turning that synthesis into a blog post or [forum post](https://discourse.jupyter.org/) or some other publication would be great. Especially with your view as a "not spending all my life working on mybinder.org" person. But yeah, spare time is a rare resource :-/
