### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by DevinBayly** [jupyterhub/mybinder.org-deploy#1758]
Hello there,

I recently completed writing some scrapy code that allows a group of researchers to gather information about retailers like target and their approaches to covid-19 mitigation within their stores. I put the jupyter notebooks on binder for my "introduction to the code" session and a researcher asked me if they were allowed to use them for gathering and interacting with additional data by tweaking lines of my code. I wasn't sure if this was an allowed usage so I'm asking here. Please let me know what you think!

**Comment by manics** [comment]
Hi! I noticed you've also posted on the Jupyter Community Forum: https://discourse.jupyter.org/t/usage-question-can-my-researchers-keep-using-the-binder-for-their-work-if-we-cite-binder-in-publication/7240

That forum has a wider reach than this repo, so I'll close this issue to avoid answers being split across two locations.

**Comment by DevinBayly** [comment]
Ok, just hoping someone answers me somewhere haha. Thanks!
