### ISSUE TITLE
Request for increasing user quota for university seminar (4.2 - 5.2)

### ISSUE THREAD

**Issue by Beremi** [jupyterhub/mybinder.org-deploy#1802]
### 1. Who you are
I am Michal Béreš, a student of VŠB - TUO (university in the Czech republic). We are making a short course for high school students interested in mathematics and programming.
### 2. A few details about the event/course/context
Our curse is called SKOMAM (http://skomam.vsb.cz/index.php?page=uvod) and it is focused on high school students interested in math. Part of our curse was a programing lecture usually held at our university. Due to covid restrictions, we are forced to hold this course online. We will be doing the course in Jupyter notebooks, and we would like to use Binder as a provider of servers. 
### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
Everything in the course is free of charge and speakers are also not paid.
### 4. A link to the repository you are using
https://github.com/Beremi/SKOMAM
### 5. What type of event it is:
- [ ] talk
- [ ] workshop
- [X] lecture course
- [ ] training session

### 6. How many people you expect to attend the event
We are expecting a maximum of 300 users.
### 7. The exact times and dates of the event(s) (with timezone information)
The curse is from 4. 2. 8:45 CET to 5.2. 16:00 CET.
### 8. How do you plan to give mybinder.org a shout out at the event
We gracefully mention binder support to our students and lectors.

**Comment by betatim** [comment]
We increased the quota for the repo just now. Let us know how it goes.

**Comment by Beremi** [comment]
Thank you very much!
Our course went very well everything including binder was smooth.
We just got much fewer attendees than we expected (around 60) so increased quota was not needed after all.

Thanks again for the quota increase and more importantly for the binder itself its a fabulous tool.

Michal
