### ISSUE TITLE
terminate pods and/or processes based on cumulative cpu usage

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#1811]
we have our idle culler, which lets us set a maximum pod lifetime, which we currently set at 6 hours. However,  6 hour pod that's mostly idle has a very different cost to the cluster from a pod that's been pegging a cpu at 100% that whole time.

In looking at minesweeper, I think we can consider looking at max aggregate cpu time as well, to terminate "hardworking" pods earlier than idle ones.

I think we have the ability to handle cpu times both at the process and pod level (I'm still figuring out how to access the pod metric, but it's available [in prometheus](https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?panelId=18&fullscreen&orgId=1)). The process metric is easy enough, and readily available in minesweeper. The pod metric is trickier, as is perhaps process *groups*.

What do folks think about automatically killing user processes after, e.g. 1 cpu-hour? Or even less? And what about pods? From the above chart, I think we would be shutting down ~30 process per day if we terminated processes that used more than 1 cpu hour.

**Comment by manics** [comment]
1 hour seems fine, even a workshop making heavy use probably won't last more than 3-4 hours, most of which would be coding or listening to a speaker. It might be good to make these limits explicit though, either for people running workshops (https://mybinder.readthedocs.io/en/latest/about/user-guidelines.html), or perhaps on the mybinder front page so it's clear to everyone?

**Comment by betatim** [comment]
Sounds like a smart idea. I have no feeling/intuition for how many CPU hours we'd expect 99% of "legitimate" processes to use. We could start with a large value and then keep turning it down till we get to the point where (on average) we kill "a handful" of processes a day. Then we can inspect what it is we are killing and re-decide?

If we end the "busy" processes in a pod won't it eventually shutdown itself due to inactivity? Makes me think doing the easy thing (cumulative CPU time for processes) gets us a long way along. But learning new things about how to get the metric for the whole Pod is also interesting :D -> process based would already be cool.

**Comment by minrk** [comment]
If we kill processes only (not pods), I think this will be minimally disruptive. I suspect a significant fraction of these are tutorial notebooks left in an infinite loop and abandoned. I've seen several of these when searching for possible miners (e.g. "why is ipython-in-depth running at 100% cpu? Oh, I see Untitled1.ipynb is pegged in a neverending for-loop, and they are now working on Untitled2.ipynb...). Another large number are ML models/tutorials that are legitimate, but I think we can say that they are 'using up' their allotted resources.

The main case killing a process will not cover:

- cpu usage due to many parallel and/or short-lived processes

I will try to collect some statistics on pods from prometheus to at least see how many we are likely to affect at all.

**Comment by minrk** [comment]
I've been poking around, and it looks like only 5% of pods use more than one cpu-minute and only 0.7% use more than 10 cpu-minutes. If we only look at pods that run for at least an hour, that's still only 25% of pods using at least one cpu-minute and 4.4% using at least 10 minutes.

Only about 1/1000 pods use at least one cpu hour (1/100 of pods that run for at least an hour use at least one cpu hour).

So setting this limit would affect between 0.1 and 1 percent, depending on how you look at it.

I'll post my analysis tomorrow, I'm out of time today.

**Comment by minrk** [comment]
I finished some analysis of the prometheus pod cpu usage [here](https://github.com/minrk/binder-cpu-data/blob/main/usage.ipynb), which I mainly organized in the form of CDFs, which summarize the data in the form of "what fraction of pods use at least N cpu-seconds", and produced those summaries for a few subsets of data, which look like this:

<img width="680" alt="Screen Shot 2021-02-04 at 13 32 56" src="https://user-images.githubusercontent.com/151929/106893383-c860c700-66ed-11eb-9fd6-8dedbafde351.png">


Key data points:

Taking all pods for the last 4 weeks (440k pods)

- median session time: 14 minutes
- median cpu usage: 6 seconds
- only 1.2% of all pods use more than 10 cpu-minutes
- only 0.3% (1158 total pods) use more than 1 cpu-hour. These are the pods that would be terminated by our proposed limit.

Of course, absolute numbers means including the very large number of visits that probably click a link and never run anything, which could skew things.

We can select down to 'active' sessions in various ways, e.g. by only looking at age >= 20 minutes (~1/3 pods):

- median session time: 35 minutes
- median cpu usage 17 seconds
- 1.5% use at least 30 cpu-minutes
- still only 0.7% of these use 1 cpu-hour
- 21% of these sessions are at least one hour

Another way to define 'active' sessions is those that use at least 10 cpu-minutes (5300, or 1.2% of all sessions). This is the subset that's actually doing significant computational work on Binder, whether it's a simulation, a `jupyter lab build`, or an infinite loop.

- 22% of these use at least 1 cpu-hour
- 10% use 2 cpu-hours

Finally, if we select only "heavy" sessions, defined as:

- at least 10 cpu-minutes
- at least 1 hour total duration

We get 3500 pods (0.8% of all sessions), where:

- 62% run for at least 2 hours
- 16% exhaust the session max of 6 hours
- 57% use at least 30 cpu-minutes
- 32% use at least 1 cpu-hour

Summary for this 'heavy' user subset:

<img width="643" alt="Screen Shot 2021-02-04 at 13 33 13" src="https://user-images.githubusercontent.com/151929/106895036-07901780-66f0-11eb-9906-1dc35dd5e648.png">

Checking the repos for this set also reveals that over 1/3 of them were from the youtube-scraping abuse repos, so there definitely isn't a huge amount of legit use in this range.
