### ISSUE TITLE
Just to inform you about a possible spike this afternoon (UTC+1)

### ISSUE THREAD

**Issue by IgnasiLucas** [jupyterhub/mybinder.org-deploy#1813]
### 1. Who you are
My name is José Ignacio Lucas Lledó. I am a professor at the University of Valencia (Spain). I am teaching an introduction course to Bioinformatics.

### 2. A few details about the event/course/context
Because of restrictions due to the COVID-19, I want to teach remotely some computer sessions. Mybinder allows me to make sure that all students will have the same environment, and they won't have to worry about installing anything. So, they can follow the session and do the work from their homes. They are 32 in all. It is the first time I use mybinder, and I'm very excited about it. I actually requested my university to set up our own binder hub. If the session this afternoon is successful, I will keep teaching this way a few more times this semester. I realize it's too late now to tell you about this afternoon's session. 

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
This is a public university. Only undergraduate students and me are expected to attend. It's part of the daily teaching.

### 4. A link to the repository you are using
https://github.com/IgnasiLucas/T2_seqs

### 5. What type of event it is:
- [ ] talk
- [ ] workshop
- [ ] lecture course
- [X] training session

### 6. How many people you expect to attend the event
Only 33. I do not really need an increase in the limits. But I thought it would be a good idea to let you know. Also, because it's out of my hands, and I know there is a chance that it will not work. I do have a plan B, just in case.

### 7. The exact times and dates of the event(s) (with timezone information)
February 4th, 2021, 15:00 - 17:00 (UTC + 1)

### 8. How do you plan to give mybinder.org a shout out at the event
I am very aware that it is mybinder.org who provides the service for free. I already mentioned mybinder.org during theory sessions, including their logo in my slides. I just plan to mention it again, to make students aware.

**Comment by manics** [comment]
Thanks for letting us know. As you've noticed 33 users is well within the normal limits, so everything should be fine 😄
