### ISSUE TITLE
Request to bump resources

### ISSUE THREAD

**Issue by krisrs1128** [jupyterhub/mybinder.org-deploy#1834]
### 1. Who you are

My name is [Kris Sankaran](https://stat.wisc.edu/staff/sankaran-kris/), I am an assistant professor of statistics at the University of Wisconsin - Madison.

### 2. A few details about the event/course/context

I am hosting a workshop about data visualization for remote sensing, as a part of UW Madison's [Data Science Research Bazaar](https://datascience.wisc.edu/data-science-research-bazaar/). 

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

[Registration](https://www.eventbrite.com/e/2021-data-science-research-bazaar-tickets-134421276657) is free and open to the public.

### 4. A link to the repository you are using

https://github.com/krisrs1128/mappingvis

### 5. What type of event it is:
- [ ] talk
- [X] workshop
- [ ] lecture course
- [ ] training session

### 6. How many people you expect to attend the event

There are ~ 150 people currently registered. I expect this to drop to 35 - 50% this amount, but wanted to write this issue just in case.

### 7. The exact times and dates of the event(s) (with timezone information)

2:45 - 4:45pm CST
February 17, 2021

### 8. How do you plan to give mybinder.org a shout out at the event

* I describe binder in my introductory slides
* Everyone will be following along from binder

**Comment by minrk** [comment]
added in #1838

**Comment by krisrs1128** [comment]
Thank you, I appreciate it. I've really enjoyed preparing the workshop materials with binder.
