### ISSUE TITLE
Unable to use Proxy to access server created on MyBinder

### ISSUE THREAD

**Issue by valhuber** [jupyterhub/mybinder.org-deploy#1842]
I have been very excited by the combination of MyBinder and JupyterLab.  It is wonderful to create a no-install demo.  Thankyou!

This [MyBinder](https://notebooks.gesis.org/binder/v2/gh/valhuber/ApiLogicServerTutorial/HEAD?urlpath=lab) creates an API Server.   This works fine - you can access it in JupyterLab by curl at `localhost`:
```bash
curl -X GET "http://localhost:5000/Order\
?include=\
&fields%5BOrder%5D=Id%2CCustomerId%2CEmployeeId%2COrderDate%2CAmountTotal\
&page%5Boffset%5D=0\
&page%5Blimit%5D=2\
&sort=Id%2CCustomerId%2CEmployeeId\
&filter%5BCustomerId%5D=ALFKI"\
 -H  "accept: application/vnd.api+json" \
 -H  "Content-Type: application/vnd.api+json"
```

The server / API is also accessible by Open API (Swagger).  Seeing this requires, of course, a (local) Browser with a connection to the created server.  Locally, it is  `http://localhost:5000/'. 

I presume the **proxy** is the approach for the remote server, but I have been unable to make this work.

I have tried 2 ways to get the server address.

Using a terminal and `hostname -I`, I can get the URL, and then try things like:
```bash
http(s)://10.244.95.170/proxy/5000
```

I also noted the url for MyBinder, and tried to use that, eg,
```bash
https://notebooks.gesis.org/binder/jupyter/user/valhuber-apilogicservertutorial-tyc6zhvz/proxy/5000
```

In my requirements.txt file, I have `jupyter-server-proxy`.  Is there also a step required to _enable_ it?

If the proxy is not the right approach, is there another alternative?

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
