### ISSUE TITLE
Request for extra resource during STFC Particle Physics Masterclass (4th March)

### ISSUE THREAD

**Issue by StewMH** [jupyterhub/mybinder.org-deploy#1843]
### 1. Who you are
STFC (UK research organisation) staff.
### 2. A few details about the event/course/context
We are running a virtual event introducing school students to particle physics, with some hands-on data analysis examples.
https://www.eventbrite.co.uk/e/registration-of-interest-particle-physics-masterclass-2021-at-ral-tickets-120176456015
### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
The event is free of charge to all participants.
### 4. A link to the repository you are using
https://github.com/olaiya/zboson-exercise/
### 5. What type of event it is:

- [ ] training session

### 6. How many people you expect to attend the event
300 people simultaneously. We are also expecting to host 100 or so more on our own dedicated server
### 7. The exact times and dates of the event(s) (with timezone information)
9:00 - 17:00 GMT, Thursday 4th March
### 8. How do you plan to give mybinder.org a shout out at the event
We will thank mybinder for the contribution while running the session, and it will also be listed on slides.

Happy to discuss or clarify any of this.

**Comment by manics** [comment]
Sounds fine to me. Normally we bump the quotas by adjusting the mybinder.org config a few days before the event. If you want you can help us out/remind us by opening a PR like https://github.com/jupyterhub/mybinder.org-deploy/pull/1801 a few days before.
