### ISSUE TITLE
180DC European Summit

### ISSUE THREAD

**Issue by jireland88** [jupyterhub/mybinder.org-deploy#1847]
Hi,

We're 180 Degrees Consulting Bristol, a student society set-up to offer pro bono consulting services to charities and social enterprises. Last year we realised we couldn't find any student societies helping charities with their data so we set up a data team to do pro bono data science. Since then we've worked with the likes of AgeUK, St Peters Hospice and Student Minds to deliver everything from dashboards to NLP and network analysis.

We've been offered the change to speak at 180DC's European Summit on our data science work. The European Summit is a chance for individual 180DC branches to share their ideas and learnings with other branches to improve the skills of the wider network. I've seen data science talks previously use Binder and was really impressed with how interactive it made the session so I wanted to use it for this.

However, we've now found we have over 200 sign-ups which breaches the terms of use and so I'm asking for increased resources for the 28th February to accommodate this talk.

The summit is completely free to attend. There are sponsors but no money changing hands involving speakers or attendees.

The repository is here: https://github.com/jireland88/Data_Science_in_Pro_Bono_Consulting

The event is an educational workshop run and attended by students.

We're expecting 200-300 attendees and the event will run from 2-3 PM GMT on the 28th of February.

We'll include Binder's logo on the PowerPoint and mention the project and its mission whilst people are launching the notebook.

Apologies for the late notice, we'd love to use your technology to make our talk as engaging and interactive as possible.

Kind regards,
Jake - 180DC Bristol

**Comment by manics** [comment]
Sounds like a great project! We bump the quotas by adjusting the mybinder.org config a few days before the event. If you want you can help us out by opening a PR like https://github.com/jupyterhub/mybinder.org-deploy/pull/1801. Since not everyone will actually use mybinder setting the limit to ~200 should be fine, unless you get signifinantly more than 300 signups!

**Comment by jireland88** [comment]
Ok will do. Thanks so much :)

> Sounds like a great project! We bump the quotas by adjusting the mybinder.org config a few days before the event. If you want you can help us out by opening a PR like #1801. Since not everyone will actually use mybinder setting the limit to ~200 should be fine, unless you get signifinantly more than 300 signups!

**Comment by betatim** [comment]
the PR for this is #1849

**Comment by betatim** [comment]
Thanks for making the PR. I merged it already now as the event is in a few days.

**Comment by jireland88** [comment]
Awesome, thanks Tim :)

**Comment by rgaiacs** [comment]
Closing because the workshop already happen.
