### ISSUE TITLE
rollback failed deploys?

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#185]
We have tests to verify that a deploy succeeded (yay!). But when the tests suggest that the deploy did not succeed, we leave it in place. This has been useful, because test failures seem to most often be problems in the test at this point, rather than problems in the deployment. But maybe we should be doing a rollback to the previous state when the test fails?

**Comment by willingc** [comment]
Can we add a notification to gitter when a deploy to production test fails? I would think at this point it might be too noisy to notify on deploy to staging test fails.

**Comment by yuvipanda** [comment]
We sort of get notified for both on the right sidebar now.

Rollback would involve:

1. Pushing a new PR to this repo
2. Merging it.

Not sure if we can / should do that automatically.

**Comment by choldgraf** [comment]
we now have instructions in the [site reliability guide](https://mybinder.readthedocs.io/en/latest/) to roll back if there's ever a fail, so I'll close this!
