### ISSUE TITLE
Request of a temporary increase of quota for May 10 to 14

### ISSUE THREAD

**Issue by francedirenzo** [jupyterhub/mybinder.org-deploy#1853]
### 1. Who you are
I am one of the organizers of the 2021 edition of the [Gravitatinal Wave Open Data Workshop](https://www.gw-openscience.org/static/workshop4/index.html#), to be held online from May 10 to 14.
### 2. A few details about the event/course/context
An important part of the workshop is constituted by hands-on sessions, where participants are tutored to complete a series of tutorials, in the format of Jupyter notebooks, about the analysis and visualization of data. I found using mybinder to be very convenient in order to have all the same Python environment.
### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
Participation in the event is free. No fees etc.
### 4. A link to the repository you are using
[This is the repository for 2021 edition](https://github.com/gw-odw/odw-2021), which is quite empty at the moment of writing. For comparison, please refer to the one of the [2020 edition of the workshop](https://github.com/gw-odw/odw-2020).
### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

### 6. How many people you expect to attend the event
We will have 150 participants + 20 mentors. I would like to encourage participants to make use of mybinder.org. For this reason, I'm requesting a temporary increase in limits for the accesses to the repo.
### 7. The exact times and dates of the event(s) (with timezone information)
The exact times of the hands-on sessions are, from May 10 to May 14 2021, two sessions of 1h30: from 12:00 UTC to 13:30 UTC, and from 22:30 UTC to 00:00 UTC of the next day. Also, a couple of hours around the session times would be very helpful.
### 8. How do you plan to give mybinder.org a shout out at the event
I already recommend mybinder.org as one of the preferred methods for attending the hands-on sessions: you can find it in the setup.md file in the previous github repo. I would like it to be the standard (if not the only) way to do that, besides the installation of conda and the environment directly on the laptops of the participants. Quota limits prevent me to sponsor it too much with 150+ participants. This is why I'm asking for a temporary quota limit increase.

Thanks! 
Best,
Francesco

**Comment by manics** [comment]
Hi :wave: . We normally bump the quotas by adjusting the mybinder.org config a few days before the event. If you haven't heard from us around 5 days before your event starts feel free to remind us, or if you want you can open a PR like https://github.com/jupyterhub/mybinder.org-deploy/pull/1801 a few days before.

**Comment by rgaiacs** [comment]
Closing because the workshop already happen.
