### ISSUE TITLE
Bump resources for agentpy workshop

### ISSUE THREAD

**Issue by JoelForamitti** [jupyterhub/mybinder.org-deploy#1854]
### 1. Who you are
I am the developer of the [agentpy](https://github.com/joelforamitti/agentpy) package.
### 2. A few details about the event/course/context
I will host a workshop on how to use the agentpy package at the [Social Simulation Fest 2021](https://www.socsimfest21.eu/tuesday/). 
### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
No money involved.
### 4. A link to the repository you are using
https://github.com/JoelForamitti/agentpy_workshop
### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session
### 6. How many people you expect to attend the event
50-150 (maximum 300)
### 7. The exact times and dates of the event(s) (with timezone information)
Tuesday, 16 March, 13.00 - 17:00 (CET)
### 8. How do you plan to give mybinder.org a shout out at the event
I will let everyone know that the event would not be possible without it :)

**Comment by manics** [comment]
Hi :wave: . We normally bump the quotas by adjusting the mybinder.org config a few days before the event. If you want to help us out you can open a PR like https://github.com/jupyterhub/mybinder.org-deploy/pull/1801 a few days before.

**Comment by JoelForamitti** [comment]
Hi @manics, I created a PR here: https://github.com/jupyterhub/mybinder.org-deploy/pull/1865
Is it possible to merge it in time for the event? (before this Tuesday, 16.03.)
Thanks a lot! Binder is a fantastic tool for this
