### ISSUE TITLE
quota increase request for 4/5 at 4:30 PM EDT

### ISSUE THREAD

**Issue by delbert** [jupyterhub/mybinder.org-deploy#1879]
### 1. Who you are
i am delbert murphy @ microsoft
### 2. A few details about the event/course/context
we are teaching an Intro to Quantum Computing session at QC Hack:  https://www.qchack.io/
### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
it is an all-volunteer event, hosted by students at Yale and Stanford, for QC hackers, world-wide.  it looks like there are sponsors of the event, so money must change hands, but i don't know how that works
### 4. A link to the repository you are using
https://github.com/tcNickolas/QuantumKatas
### 5. What type of event it is:
- [ ] talk
- [x ] workshop
- [ ] lecture course
- [ ] training session

### 6. How many people you expect to attend the event
there are 1200 students registered, so far.  we are told that about 200 will attend the event 
### 7. The exact times and dates of the event(s) (with timezone information)
April 5, 2021, at 4:30 PM EDT - 6:00 PM EDT
### 8. How do you plan to give mybinder.org a shout out at the event
we tell our students as they get into the lab and my colleagues who Tweet will thank you over Twitter

**Comment by manics** [comment]
Hi :wave: . We normally bump the quotas by adjusting the mybinder.org config a few days before the event. If you want to help us out you can open a PR like https://github.com/jupyterhub/mybinder.org-deploy/pull/1801.

**Comment by manics** [comment]
Closed by https://github.com/jupyterhub/mybinder.org-deploy/pull/1883
