### ISSUE TITLE
Running a workshop with interactive Jupyter Notebooks

### ISSUE THREAD

**Issue by AndresPenuela** [jupyterhub/mybinder.org-deploy#1888]
In a few days  I will run a workshop (20 participants) with the goal of introducing PhD students to Jupyter Notebooks with interactive visualization (Bqplot and Plotly). I have already used MyBinder last year for the same workshop but with less participants (5 individuals) and it went very well. This year, given that the number of individuals running the same interactive Notebook simultaneously will be higher, I was wondering if this could affect the time the Notebook will load and how reactive the interactive figures will be?

Thanks!

**Comment by rgaiacs** [comment]
Closing because the workshop already happen.
