### ISSUE TITLE
Two sessions with 40 students each.

### ISSUE THREAD

**Issue by afmoene** [jupyterhub/mybinder.org-deploy#1904]
This Tuesday (May 11) I will be running a data analysis practical at Wageningen University in the afternoon (timezone UTC+2).  In totalI have  80 students, but they will work in 2 hour shifts, so 40 students at the same time. Computationally it is not very intensive, but the notebook comes with quite some data (see https://github.com/afmoene/hupsel/tree/master/fluxnet-explorer).

I hope this usage is OK. 

Arnold Moene

**Comment by manics** [comment]
Hi, this should be fine, it's within the documented limits https://mybinder.readthedocs.io/en/latest/about/user-guidelines.html#maximum-concurrent-users-for-a-repository

If you have any problems feel free to contact us on [Gitter](https://gitter.im/jupyterhub/binder)
