### ISSUE TITLE
Use mybinder for online exams?

### ISSUE THREAD

**Issue by nikwa** [jupyterhub/mybinder.org-deploy#1923]
I don't know if this is an odd use case, but I give it a try. 

I am planning a computer-based exam where some of the exam questions they are expected to write code in Python. The exam will be done on computers in an exam hall provided by the university via the cloud-based assessment platform Inspera assessment. In Inspera you can write and submit python code with syntactic support, but you cannot execute any code. You can also not run any other software installed on the computer, however, you can allow access to a set of web resources that the teacher specify. Could mybinder.org be used as such a web resource? My idea was that they could write their code in a notebook, possibly extending existing code in the repository, copy the code into Inspera and submit.

The exam is executed via the so called Safe Exam Browser that only allows access to the specified web resources.
I have tried this setup by allowing the binder-link from a public repository as such a resource, as well as https://hub.gke2.mybinder.org/ on which the server runs (as I understand). It works sometimes, and sometimes it just gets stuck on the launching procedure, maybe I need to allow to access to more resources than these two?

I don't know if this is a reasonable use case of mybinder.org or if they are other online interpreter that is more suited for my use case. My requirements are
* Should not require any login
* Should not be possible to communicate via the allowed internet resources
* Should preferably be a service which is non-commercial
* Should be easy to copy code to another window
* That it is linked to a github repository is a plus but not a necessity

Also, I don't know how this solution would scale, we would expect 100-150 students taking the exam.

**Comment by manics** [comment]
Hi! mybinder.org is run on a best-effort basis and doesn't have anything like a service level agreement, so this probably rules it out for exams where availability is critical.

I'm guessing you don't need the full flexibility of BinderHub, and that having a fixed set of dependencies in a Python environment for users is enough, so have you through about running your own JupyterHub, e.g. see https://tljh.jupyter.org/en/latest/ ?

**Comment by rgaiacs** [comment]
Closing as older than 2 years.
