### ISSUE TITLE
No SPARQL kernel ?

### ISSUE THREAD

**Issue by akuckartz** [jupyterhub/mybinder.org-deploy#1926]
I would love to run this ipynb-file:
https://github.com/bobdc/misc/blob/master/JupyterSPARQL/Jupyter%20and%20SPARQL%20and%20Dort%20or%20Dordrecht.ipynb

But mybinder reports that a SPARQL kernel is missing.

**Comment by akuckartz** [comment]
A few years ago an issue was raised indicating that a SPARQL kernel was available at that time: #694

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/sparql-kernel-and-mybinder/9489/2
