### ISSUE TITLE
Request for increase in resources during RAL PPD Grad lectures

### ISSUE THREAD

**Issue by olaiya** [jupyterhub/mybinder.org-deploy#1929]
### 1. Who you are
STFC (research organisation) staff

### 2. A few details about the event/course/context
We are providing courses for particle physics grad students. We would like to run some machine learning examples via jupyter notebooks. 

https://indico.stfc.ac.uk/event/299/

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
The event is free of charge.

### 4. A link to the repository you are using
https://github.com/olaiya/MLTutorialNotebooks

### 5. What type of event it is:
- [ ] lecture course

### 6. How many people you expect to attend the event
Around 100 have registered. But as it is free past experience has shown that anywhere up to 200 may attend

### 7. The exact times and dates of the event(s) (with timezone information)
Wednesday 9th June 0900-1230 BST

### 8. How do you plan to give mybinder.org a shout out at the event
Thank mybinder during the lecture and recommend using mybinder

**Comment by manics** [comment]
Sorry for missing this. If you had 100 registrations the default mybinder limits should've been fine, especially as not everyone will launch mybinder. In future please don't hesistate to ping us if you don't get a response a few days before your workshop.
