### ISSUE TITLE
SPM12 and neuroimaging analysis

### ISSUE THREAD

**Issue by vrubino** [jupyterhub/mybinder.org-deploy#1931]
Hello, would it be possible to use Jupyter and Mybinder to run fMRI analyses with SPM12? 
They are very heavy in terms of disk usage (e.g. 15-30 GB in total for a study with 30 participants).
Thanks

**Comment by choldgraf** [comment]
Hello - i suspect that this won't work with the binderhub at mybinder.org - that environment is quite small. Also isn't spm a Matlab tool?

**Comment by rgaiacs** [comment]
Closing as older than 2 years.
