### ISSUE TITLE
Deploy a staging cluster at Turing to add to the staging env for testing

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/mybinder.org-deploy#1935]
### Summary

It's currently difficult/impossible to test more complex networking concepts that involve the federation redirector since there is only one member in the staging federation currently. @callummole and myself can work towards deploying a small, non-scalable cluster at the Turing to help with this initiative.

### What needs to be done?

- [x] Provision cluster with similar resources to gke-staging
- [x] Add `turing-staging` config to this repository
- [x] Update `deploy.py` to upgrade staging
- [x] Do a local deploy, get IP addresses and set up DNS records
- [x] Update github actions workflow to include the new staging cluster
- [ ] ...

**Comment by sgibson91** [comment]
@callummole I added an extra step here we'll need to do which is configure A records in the DNS zone for IP addresses and such. This might be a step that'll be good to do synchronously

**Comment by sgibson91** [comment]
@callummole I think we've covered the main point of this issue (barring CI/CD issues). Want to close?

**Comment by callummole** [comment]
with pleasure.
