### ISSUE TITLE
Request to bump resources for a summer school

### ISSUE THREAD

**Issue by markusschmitt** [jupyterhub/mybinder.org-deploy#1942]
### 1. Who you are
I am a Postdoc at the University of Cologne and co-organizer of the school.

### 2. A few details about the event/course/context
From July 16 to 18 we are holding a summer school on [Machine Learning in Condensed Matter Physics](https://www.crc183.uni-koeln.de/summer-school-machine-learning/), organized by the CRC 183, a joint research center of the FU Berlin, Universities of Cologne and Copenhagen, and the Weizmann Institute. A central part of the event will be two hands-on sessions, where we would like to encourage participants to run notebooks using mybinder.org.

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
No money is changing hands.

### 4. A link to the repository you are using
[https://github.com/markusschmitt/crc183_summer_school_2021](https://github.com/markusschmitt/crc183_summer_school_2021) (currently empty, content coming soon.)

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [x] training session

### 6. How many people you expect to attend the event
We are expecting around 80 people to participate actively in the hands-on sessions.

### 7. The exact times and dates of the event(s) (with timezone information)
- July 17, 4pm-6pm (CEST)
- July 18, 10:30am-12:30pm (CEST)

### 8. How do you plan to give mybinder.org a shout out at the event
We will advertise mybinder.org in the presentations and acknowledge the support on the school's website.

**Comment by manics** [comment]
Hi :wave: . Thanks for letting us know. The default mybinder quota is 100 so you should be fine, if your requirements change please feel free to ping us again.

**Comment by markusschmitt** [comment]
Great, thanks! 

We just realized that the available memory is a bit short for our purposes. Is there a chance of having that increased?
