### ISSUE TITLE
Resource limit for conference on 6/30

### ISSUE THREAD

**Issue by campagnola** [jupyterhub/mybinder.org-deploy#1945]
### 1. Who you are
I am a neuroscience researcher at the Allen Institute for Brain Science in Seattle

### 2. A few details about the event/course/context
I'm running an hour-long tutorial starting at 8:30 am PST that describes how to access data resources we have published. This is part of a workshop in larger neuroscience conference: https://2021meeting.cns.org/home-2021

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
Attendance requires a registration fee. I and others presenting this workshop are not being paid for it.

### 4. A link to the repository you are using
https://mybinder.org/v2/gh/AllenInstitute/aisynphys/binder-r2p3

### 5. What type of event it is:
A tutorial, embedded in a workshop, embedded in a conference.

### 6. How many people you expect to attend the event
Rough guess, around 100-200. Some unknown fraction of those attendees will choose not to use mybinder.

### 7. The exact times and dates of the event(s) (with timezone information)
Our session runs 8:45-9:45 am PST on Wednesday, June 30.

### 8. How do you plan to give mybinder.org a shout out at the event
At the beginning of the talk, I will invite attendees to load up mybinder on their own machines and tell them what an awesome free service it is.

**Comment by manics** [comment]
Hi :wave: . The default mybinder quota is 100 so you'll most likely be fine, especially as not everyone will launch the repo on mybinder.

However if you're worried about hitting the limit please open a PR to bump the limit like https://github.com/jupyterhub/mybinder.org-deploy/pull/1801 .

**Comment by campagnola** [comment]
Thanks! I think we'll be fine with 100.
