### ISSUE TITLE
2021-07-08 Request to bump resources for Excursion talk at PyHEP 2021

### ISSUE THREAD

**Issue by matthewfeickert** [jupyterhub/mybinder.org-deploy#1947]
> 📅 Ideally open an issue two weeks before an event, though we will still consider requests up to 48 hours before the event 📅

This request is being put in less than the requested two weeks in advance. We fully understand this request might not be possible to fulfill and can drop Binder support for this section. We apologize for this late request. @matthewfeickert will handle all of the PRs that are necessary for this request as he [did for PyHEP 2020 last year](https://github.com/jupyterhub/mybinder.org-deploy/pulls?q=is%3Apr+author%3Amatthewfeickert+is%3Aclosed). 

### 1. Who you are

@matthewfeickert (PyHEP 2021 workshop organizer contact) on behalf of @irinaespejo (presenter).

### 2. A few details about the event/course/context

This is for a Jupyter notebook talk at the [PyHEP 2021 workshop](https://indico.cern.ch/event/1019958/) 2021-07-05 through 2021-07-09.

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

No, all speakers and organizers are volunteers. The workshop is free of charge and all resources will be made publicly available both on the [workshop website/Indico page](https://indico.cern.ch/event/1019958/) and on the [High Energy Physics Software Foundation YouTube channel](https://www.youtube.com/channel/UCv4hukXGkCYvBClQMKzypnQ).

### 4. A link to the repository you are using

https://github.com/irinaespejo/excursion

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

### 6. How many people you expect to attend the event

There are 1100 attendees registered, but we would anticipate that an upper _estimate_ would be maybe 300-400 would connect at this time based on PyHEP 2020 which had similar numbers.

### 7. The exact times and dates of the event(s) (with timezone information)

[Active Learning for Level Set Estimation](https://indico.cern.ch/event/1019958/timetable/#14-active-learning-for-level-s) is occurring at 15:00 - 15:30 UTC+2 on 2021-07-08.

### 8. How do you plan to give mybinder.org a shout out at the event

We will make an announcement at the start of the workshop about Binder, the service, and how the resources are being provided. If there is specific language the Binder team would like us to use we are happy to integrate this in.

**Comment by manics** [comment]
Based on last year I think this should be fine. Unless someone on the mybinder team thinks otherwise I think it'll be easiest if you could open a single PR to bump the limits for all your workshops.

**Comment by matthewfeickert** [comment]
> Unless someone on the mybinder team thinks otherwise I think it'll be easiest if you could open a single PR to bump the limits for all your workshops.

Okay so just go for it all at once for the whole week then instead of day by day like last year? If yes, then can we do PR #1976 by itself and then do 1 big one following that as some of our presenters are very slow to get us repo links this year. :grimacing:

**Comment by manics** [comment]
It's unlikely the repos will see significant usage before the workshop so adding them all together means you can be sure they're ready :smiley: 

If traffic remains high after the workshop we can remove them one-by-one.

**Comment by matthewfeickert** [comment]
Okay great! Thanks @manics. Just to be safe I'll also produce removal PRs after each day of the workshop to move them off if needed, though to reduce the work on the PR shifter I'll just have them ready to go and will only submit a removal PR at the end of the week unless needed beforehand.
