### ISSUE TITLE
GESIS needs the build_token_secret

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#1958]
in secrets/config/common.yaml:binderhub.config.BinderHub.build_token_secret

This is a *shared* secret for signing build tokens, so all members of the federation should use the same value.

**Comment by MridulS** [comment]
Deployed with the `build_token_secret` and everything looks okay (incoming traffic from mybinder is back up).

**Comment by minrk** [comment]
Perfect, thanks!
