### ISSUE TITLE
What is this repo for?

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#2]
Is it

1. the specific deployment files for beta.mybinder.org?
2. example/reference/documentation on which people should base their own deployments?
3. something else?

It's not clear from the readme. I had assumed 1., which would suggest that it shouldn't be part of people putting together their own deployments. But @choldgraf mentioned this repo when going through a binder deployment, so now I'm not sure.

cc @willingc

**Comment by choldgraf** [comment]
I think the pieces are still settling, but as I see it:

1. `jupyterhub/binder` is documentation for people who will click on binder links. It is the only binder repo that could be considered documentation for `mybinder.org`. It is also a "routing" repository that points people to other repos that cover their specific questions (e.g. binderhub or repo2docker). 
2. `jupyterhub/binderhub` is dev-facing documentation for deploying your own binderhub, and for describing the guts of the binderhub tech. It'll point people to z2jh, repo2docker, etc as necessary and will go into more detail about things that an average user won't care about (e.g. kubernetes).

Right now `jupyterhub/binder` is *only* documentation, it doesn't have any tech inside it. Though we could move the actual `mybinder.org` deployment config into it if that would simplify things a bit.

**Comment by yuvipanda** [comment]
This repo is only for mybinder.org deployment, and I've renamed it to clarify. Previous name was ambiguous.

**Comment by yuvipanda** [comment]
Edited README a little to clarify too.

**Comment by willingc** [comment]
To recap, this repo:

- contains specific deployment information for the `mybinder.org` 
- does not contain documentation or resources for generic binder or binderhub deployments
- it is an example for a specific use case of a BinderHub deployment (which other documentation may refer to at some point)

I'm going to update:
- [ ] repo title and tags at the top of the GitHub page
- [ ] the README to correct links

**Comment by yuvipanda** [comment]
tyvm, @willingc. All these seem accurate to me!

**Comment by choldgraf** [comment]
agree - and thanks @minrk for catching this
