### ISSUE TITLE
Request for increase for conference tutorial 

### ISSUE THREAD

**Issue by grburgess** [jupyterhub/mybinder.org-deploy#2001]
### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

**Comment by manics** [comment]
Hi :wave: . We normally bump the quotas by adjusting the mybinder.org config a few days before the event. If you haven't heard from us around 5 days before your event starts feel free to remind us, or if you want you can open a PR like https://github.com/jupyterhub/mybinder.org-deploy/pull/1801 a few days before.

**Comment by grburgess** [comment]
@manics  thanks!

**Comment by rgaiacs** [comment]
Closing because the workshop already happen.
