### ISSUE TITLE
Course Medical data with R (in Spain)

### ISSUE THREAD

**Issue by 1fjmanzano** [jupyterhub/mybinder.org-deploy#2003]
### 1. Who you are

I'm Javier Manzano, PhD a Math teacher in Valladolid (Spain). 

### 2. A few details about the event/course/context

In September I start teaching an online course to around 100 medical doctors on Medical data with R. 
Here`s a link with information about the course (in spanish).
https://www.saludcastillayleon.es/formacion/es/formacion-continuada/oferta-formativa-actual/actualidad-formativa/analisis-datos-medicos-programa-r

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

The course is organized by the regional public health service (Castilla y León, Spain). It is free for students (doctors). Teachers are getting paid.

### 4. A link to the repository you are using

These are the notebooks from week 1. We expect to be working 4 weeks. 
https://github.com/1fjmanzano/S1_notebooks

I still have not upload the Notebooks of the rest of the weeks (in other repositories). So there are 3 repositories still to upload.

### 5. What type of event it is:
- [ ] talk
- [ ] workshop
- [ X] lecture course (online)
- [ ] training session

### 6. How many people you expect to attend the event

Around 100 (93 right now)
### 7. The exact times and dates of the event(s) (with timezone information)
From September 7, 2021 to October 14, 2021 (Central European Summer Time CEST)

### 8. How do you plan to give mybinder.org a shout out at the event

We will explain to our students that the practices (Labs) are implemented in mybinder.org which allows to take advantage of all the didactic and pedagogical possibilities of Jupyter Notebooks.
Of course, we will emphasize that mybinder.org is a great resource to share content, in our case, in the medical and educational field.

**Comment by manics** [comment]
Hi! mybinder.org already allows 100 users for a repo so this should be fine, especially as it's rare for all event attendees to actually launch a server.

**Comment by 1fjmanzano** [comment]
Thanks for the answer. We'll try.
Cheers
