### ISSUE TITLE
CourseKata Statistics and Data Science

### ISSUE THREAD

**Issue by adamblake** [jupyterhub/mybinder.org-deploy#2007]
### 1. Who you are

I am Adam Blake, a researcher and developer at UCLA working with [CourseKata](https://coursekata.org). CourseKata was founded in 2017 by a group of learning scientists at UCLA and Cal State LA with a shared interest in understanding and improving how students learn things that are hard to learn. Our initial focus is on the teaching and learning of introductory statistics and data science. But our longer-term agenda is to make research on teaching and learning more relevant and more effective for improving important learning outcomes for all students.

### 2. A few details about the event/course/context

We would like to use Binder to power live code cells in *CourseKata Statistics and Data Science*, a **free**, innovative, interactive online textbook for teaching introductory statistics and data science in colleges, universities, and high schools. The book has around 250 short code exercises (along with another ~1000 other types of interactive exercises) embedded across 12 chapters. The majority of these exercises are for creating simple plots or running standard ANOVA on linear models, and near the end of the book we dip our toes into some very simple simulations to develop an understanding of randomness in distributions.

Currently we use DataCamp Light for all of our exercises, but their service has been unreliable and slow to improve. This is especially true for front-end features and for things like installing or updating R packages we rely on. We feel that we can get much better improvement cycles by developing our own front-end solution for students to work and play with code and by using Binder to actually run the code. 

This year, high school teachers in urban and suburban school districts in California began using CourseKata. In 2021-22, we will be expanding to high schools in additional locations (e.g., New York, DC) with highly diverse populations. CourseKata has also been used by instructors in a variety of higher education settings.  In California, those settings include community colleges, California State Universities, and the University of California. It has also been used in a number of public and private universities in the U.S. and abroad.

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

This book offered free of charge to anyone that wishes to use it. 

### 4. A link to the repository you are using

https://github.com/UCLATALL/binder

### 5. What type of event it is:
- [ ] talk
- [ ] workshop
- [X] lecture course
- [ ] training session

### 6. How many people you expect to attend the event

This varies over time as classes start and stop. Some of these classes are slower moving with lower levels of attendance (e.g. a HS class using the book over the course of a school year, with 40 students), and some are more fast-paced and heavily attended (e.g. a UCLA class may see 250 users over 11 weeks). We have reached approximately 6000 students over ~3 years.

### 7. The exact times and dates of the event(s) (with timezone information)

This is an ongoing course offered at a variety of different institutions. The vast majority of these are in the US on the West Coast.

### 8. How do you plan to give mybinder.org a shout out at the event

We would be more than happy to list and mention MyBinder anywhere we talk about the technologies employed by the team (e.g. on the front page of our website). We also plan to feature MyBinder on the documentation and website for any front-end solution we develop that utilizes MyBinder. In addition we welcome any ideas that would further boost awareness and use of MyBinder. For instance we could use MyBinder as a resource for previewing and sharing other Jupyter related materials with instructors and students.

**Comment by manics** [comment]
This sounds like a great project! The default limit for mybinder repositories is 100 simultaneous servers, so I think you'll be fine for now since it sounds like for the bigger courses not everyone will launch at the same time.

If you're running a live workshop with a large number of users we can temporarily increase your quota for that workshop. If your service ends up being very successful and you're constantly hitting the default quota it's probably best if you have a chat with us, but that's for the future 😀.

**Comment by adamblake** [comment]
> This sounds like a great project!

Thank you, we really believe in it.

> The default limit for mybinder repositories is 100 simultaneous servers, so I think you'll be fine for now since it sounds like for the bigger courses not everyone will launch at the same time.

We do have instructors using the materials in a lecture hall with 300 students, so that's where our chief concerns arise. Teaching a class of students is a very high stakes situation... if students can't do their homework due to a tech issue they can freak out! And, in this case, we wouldn't have a quick way to resolve that issue. So, if instructors are requiring students to do certain amounts of work, the students might be unfairly penalized until we can get them up and running. 

Do you think it would be possible to increase the limit, and then monitor after a while to see what we actually use? I'm not sure how feasible that would be. I would also be happy to set you up to meet @jimstigler who can provide more details about the scope of this project.

Thanks for your consideration, and for the great service you are providing.

**Comment by manics** [comment]
Sorry for the slow response in getting back to you. mybinder.org is powered by donated resources so unfortunately there's limited scope for supporting sustained usage. It's also worth noting that it's run by volunteers and occasionally things break. Obviously we do our best to fix it as quickly as possible, but this means it's not suitable for situations where an outage could unfairly penalise people or cause undue stress, like an assessment.

Have you considered running your own BinderHub? We've [got some docs on deploying BinderHub](https://binderhub.readthedocs.io/en/latest/) and if you need more help you can post on the [Community Forum](https://discourse.jupyter.org/). There's even a [one-click deploy-to-Azure button](https://github.com/alan-turing-institute/binderhub-deploy) if you have access to Azure.

We've got a [public Grafana](https://grafana.mybinder.org/?orgId=1) you can use to see how many launches are taking place during a workshop, this will hopefully give you an idea of how popular your repositories are.

**Comment by rgaiacs** [comment]
Closing because the workshop already happen.
