### ISSUE TITLE
Measure and communicate Cloud compute Financial Transparency

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#205]
@betatim pointed me to https://about.hindawi.com/opinion/a-radically-open-approach-to-developing-infrastructure-for-open-science/ which has several good points about radically open open-science infrastructure. It's a great read, and I think we are already fairly radically open. I've been thinking of how we can be more radical, and one thing would be to start making public how much we are paying our cloud providers in a fairly automated (but still private way).

The way I'm thinking of this is:

1. Every month, we get an invoice
2. We parse the invoice, getting only the data that matters and is not private - so just 'how much we paid for what specific cloud computing resource'
3. We post it somewhere public, automatically

Automating this is important, since otherwise we won't have time to do it. This has several advantages:

1. Sets up a high watermark for others providing open infrastructure to aspire to. (I couldn't find any other org that does this consistently)
2. Provides ways for community input into cutting cost (for example, tweaking instance sizes or properly cleaning up cached images in the registry)
3. Holds us, the operators of mybinder.org, accountable (which is really what radical transparency is for)

Note that this issue is only about financial transparency of operational cloud compute costs, and no other financial transactions.

**Comment by yuvipanda** [comment]
If nobody objects I'll probably work on this around Christmas break.

**Comment by choldgraf** [comment]
looks like this would be a good place to start: https://cloud.google.com/billing/docs/apis

**Comment by yuvipanda** [comment]
But totally not licking this cookie! If someone else wants to do it, go for it too! Just that if nobody does I shall :)

**Comment by betatim** [comment]
Naive Tim question: what is private about the running costs (items on the invoice)?

I can't think of a reason not to share this information. It is good for others to see to make better judgements for their deploys and it makes it super easy for us to tell potential donors: "you can see what we spent for the last quarter, so your donation buys another 2 quarters (if usage remains constant)". Optimistic Tim thinks this might make potential sponsors realise how cheap it would be to sponsor the running cost and get their name out there as the sponsor for the next few months. Or setup another public instance.

You can already see from our dashboard how many nodes there are, how many CPUs and RAM is allocated, etc from which you should be able to make a rough estimate of the cost. So the info is there but obfuscated a bit -> we wouldn't be revealing that much more info.

**Comment by yuvipanda** [comment]
Private items would probably be things like account numbers, identity of methods used to pay invoices, etc. Metadata, rather than actual data in the invoice. All info about running costs itself should be public.

**Comment by choldgraf** [comment]
Yeah I would prefer if my name or credit card # not show up somewhere :-)

other than that I am 👍 on putting that info online.

**Comment by willingc** [comment]
Interesting subject. I'm going to do some thinking on this from an economics perspective (public good, externalities, and behavior). I think that cost is one element to share/document publicly and users/repos/containers served is equally important to generate a cost per "whatever". Having this sort of information also has advantages in documenting operational efficiency gains over time. It also helps drive reasoning for federated binderhubs.

**Comment by fperez** [comment]
I'm +1 on the idea, though I'll try to think a bit more about any potential downsides (I'm assuming no personal CC info, etc).

Implementation-wise, I suggest that any parsing-preprocessing feeds its output into a pre-defined schema, so that only specific fields that we agree a-priori should be divulged go out.  I wouldn't want a parsing mistake to inadvertently put out information that should remain private.

Also, even if automated, the post should probably go through a human review (as simple as clicking 'yes'), at least for the first few months, just to make sure indeed @choldgraf's credit card doesn't end up embedded in the wrong field :)

**Comment by Carreau** [comment]
+1 to all that have been said. Also the cost makes almost no sens without usage statistics.
The page should also be clear on where this money comes from (Donation, Grants, ...)

**Comment by choldgraf** [comment]
good point @Carreau ... let's not forget that our Moore grant to fund Binder only lasts for 1 year! So we need to figure out something more sustainable relatively quickly considering how long it takes for funding mechanisms to flow through Berkeley

**Comment by Carreau** [comment]
May I suggest a Binder post just about the grant on the Jupyter blog pointing out we got a grant from Moore to Pay for Binder. More earlier than later. We can also quickly point out a few of the already new features.

**Comment by choldgraf** [comment]
I think it's a good idea - what kind of timing are you imagining?

**Comment by Carreau** [comment]
> I think it's a good idea - what kind of timing are you imagining?

Only for announcing the grant ? Well, the day it was official , so last month :-) 
My guess is either : before Dec 15, after it's holiday season. Or after Jan 15th.
Mid Jan sounds great we'll likely have the 2017 Advent of Code from Peter Norvig :-)

Ideally I'd like to have minimum one 3 min post on the blog/week (we can schedule them or leave them in draft infinitely for slow week). And we have to be careful not to post too many things either in a short amount of time, but that will be less of an issue.

**Comment by betatim** [comment]
To try and wrap this up a bit: there is no opposition to publishing the items and their cost on the monthly invoice. Caveat: @fperez and others are thinking if they can come up with a reason not to.

Publishing the running costs is only half the story. We also need to make usage stats easier to find/publish with the costs. Good metrics to share:
* total number of repo launches
* number of unique repos launched
* peak concurrent running users

The billing API @choldgraf linked doesn't seem to be able to get line items, however we can setup https://cloud.google.com/billing/docs/how-to/export-data-file (or even to BigQuery). Should we set this up?

**Comment by Carreau** [comment]
> total number of repo launches

can we get a distribution of sessions duration ? That would be cool.

**Comment by minrk** [comment]
> peak concurrent running users

Some kind of summary statistics on traffic might be good as well, e.g. sketch of running users over time, rather than just peak.

**Comment by ellisonbg** [comment]
strong +1 from me. I would like to go further than this eventually and even provide easy paths for us to communicate funding needs and allow people to donate. Maybe we could work with NumFOCUS to add a "help fund binder" badge to the website. Having readily available data on the number of users, number of repos, and the ongoing costs would help in all that. Great idea!

**Comment by choldgraf** [comment]
I would love (maybe at next dev meeting?) to have a conversation with whoever is interested around sustainability models for the Binder (and/or JupyterHub) tech. I got the feeling from Moore that the more we can make these projects live onward without depending on grant money, the happier they'd be. I'm curious what ideas people have for doing this, while maintaining the open/community-focused principles that have guided development thus far.

**Comment by willingc** [comment]
It would be interesting to get some info from the Julia Computing folks re: open source project and services/product business side. How effective it has been? Pros/cons? etc.

**Comment by nthiery** [comment]
For information (though slightly off topic the original thread): we (@fanghor, @dimpase, @minrk and other @OpenDreamKit people) are working with [EGI](http://egi.edu) (the European federation of academic grids and clouds) for the deployement of instances of JupyterHub and Binder (in discussion), accessible to all academics in Europe, and possibly beyond. @enolfc has already setup an [experimental instance of JupyterHub](http://jupyterhub.fedcloud-tf.fedcloud.eu/). The plan for now is to experiment with such instances using hardware ressources that are meant for this kind of experimental services. Then, based on adoption and resource usage patterns, some sustainable solution will have to be found. Options that we discussed are:
- Applying for grants, in particular answering calls related to the European Open Science Cloud (for some more on the later, see this [blog post](http://www.southampton.ac.uk/~fangohr/blog/2017-11-30-towards-the-european-open-science-cloud.html)).
- Convincing some of the national federations of academic grids/clouds that they should sponsor such services by allocating some of their hardware to them.
- ...

Having specific data on resource usage and costs from the mybinder instance will be a great asset in the discussions and planning! So +1 to radically open science :-)

**Comment by Carreau** [comment]
As we are on large-scale deployment, and where actually we  provide this service, how feasible would it be to collect telemetry on how users are using jupyter in MyBinder ? Does it needs IRB ? Telemetry for something as big at what @nthiery describe would be great (but there might be Personal info behind a login), though binder is ephemeral so it might be easier.

**Comment by choldgraf** [comment]
@willingc that's a great idea about Julia folks. Would be great to have a broad conversation around sustainability in the open-source analytics world.

@Carreau I vote mid-January!

**Comment by fperez** [comment]
FWIW, other than my original points above (pre-defined schema for published data and a last-minute human check to avoid accidental disclosure of personal info like CC numbers), I can't think of a reason not to do this, and many benefits :) So, enthusiastic +1.

**Comment by betatim** [comment]
(edited my comment https://github.com/jupyterhub/mybinder.org-deploy/issues/205#issuecomment-349217066 to include suggestions on metrics)

I would be conservative with the metrics we compute (more code to maintain for us) and try and point people to grafana.mybinder.org as much as possible. Adding a chart there is a lot less work than writing our own reporting.

**Comment by choldgraf** [comment]
FYI I figured out how to query our storage objects with `gcloud`, and now have our billing account dump a summary of all billable charges into storage. That means we can grab all that data and do whatever we want with it. However the data only exists since I've turned it on, so only a couple of days. Perhaps we can shift this topic to exactly what kind of viz to show people so that it's informative / interesting.

Here's an example of daily usage:

![index](https://user-images.githubusercontent.com/1839645/34073750-e4745148-e2a0-11e7-863b-01393e5d3bac.png)

**Comment by yuvipanda** [comment]
w00t, this is awesome!

Here's what I'd love for us to do:

1. Write a script that dumps this info into a JSON file
2. Run that script on a cron every day at a set time
3. Push the JSON files into a public github repo
4. Write data generation that's just notebooks in the public github repo, so people can explore it via binder ;)

What do you think, @choldgraf? I can help with setting up parts (2) and (3). This also makes this whole thing generic enough for other projects that would like to be as transparent :)

**Comment by choldgraf** [comment]
@yuvipanda here's https://github.com/choldgraf/binder-billing

it's using a CSV file instead of JSON for now, but that's the general idea anyway. Not sure the best way to automate this (e.g. would we run cron jobs on GKE?), but it seems like running it once daily should be pretty easy.

**Comment by yuvipanda** [comment]
Awesome, w00t!

Yeah, I think we can add this as a [cron job](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) on our mybinder.org prod cluster, similar to how we have https://github.com/jupyterhub/mybinder.org-deploy/tree/staging/mybinder/templates/redirector set up.

What do you think about using https://cloud.google.com/compute/docs/tutorials/python-guide instead of shelling out to gsutil? Also JSON? :D 

This is exciting :)

**Comment by choldgraf** [comment]
I can look into the google python api, shouldn't be too hard once the auth stuff is set up.

re: JSON, I am happy to put it into JSON though I have less of an intuition for an intuitive way for it to be stored. Would you be fine with simply doing https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_json.html ?

**Comment by choldgraf** [comment]
(that said, I gotta go to bed so I'll take another look tomorrow or this week!)

**Comment by choldgraf** [comment]
@yuvipanda do you have strong opinions about the form that this JSON would take? Would you be fine with just `data.to_json()`? I'll push the costs as of now to the repo, and we can work out the cron-ing later. IMO having an automated daily dump isn't super crucial to do now, as the billing is basically the same each day.

**Comment by choldgraf** [comment]
latest pink is here, btw: 

https://mybinder.org/v2/gh/choldgraf/binder-billing/master?filepath=analyze_data.ipynb

either way, what if we created a repo in `jupyterhub` called `binder-meta` that would contain the code that's currently in `binder-billing` as well as `binder-statistics`...could iterate on this there rather than it being under my account...

**Comment by betatim** [comment]
Is the code sufficiently generic that I could use it with my own binder instance? Otherwise why not put it here (like [pod-health-check.ipynb](https://github.com/jupyterhub/mybinder.org-deploy/blob/staging/scripts/pod-health-check.ipynb))? We can also use a travis cron job to run this once a day. Not as cool as using kubernetes but maybe more accessible??

**Comment by choldgraf** [comment]
That's a good idea! Forgot about that. Actually I should move binder stats here as well. For Travis we could do it but we'd need to embed the authentication for Google cloud on there... Maybe it's already there though?

**Comment by yuvipanda** [comment]
I'm happy to clean up the json :)

**Comment by betatim** [comment]
> we'd need to embed the authentication for Google cloud on there... Maybe it's already there though?

I guess we have all we need $somewhere in this repo as it can make deploys. How exactly the encrypted setup works however is still magic to me ;)

**Comment by choldgraf** [comment]
ya - in the meantime I am just gonna move the notebook / munging code into a folder in this repository, and then we can make PRs on that to get the JSON the way we want it etc. For now the data itself is contained within the repository, but we can change that and integrate w/ the deployment setup when the time is right

**Comment by choldgraf** [comment]
actually, @yuvipanda would you like me to just add you to my `binder-billing` repo so we can get things set up properly there, and then decide how we want to integrate it with this repo? I feel like we probably don't want to be intermixing the billing data (e.g. the CSV right now) with the mybinder.org deployment...

(I'm gonna add you to the `binder-billing` repo just in case

**Comment by yuvipanda** [comment]
I agree, add me there and we can sort it out.

The billing transparency code needs to have no dependency on binder itself,
so we should keep it generic and simple and re-usable by other projects :)

**Comment by choldgraf** [comment]
Hey all - just a note that I've been periodically updating the data that's in `binder-billing`. We don't have this process automated yet, but some data is better than no data :-)

https://mybinder.org/v2/gh/choldgraf/binder-billing/master?filepath=analyze_data.ipynb

**Comment by willingc** [comment]
Cool @choldgraf. Would you mind adding this somewhere in the SRE guide? Perhaps a section on monitoring.

**Comment by choldgraf** [comment]
yes! I'll do that and transfer over the repo to the new org as well

**Comment by choldgraf** [comment]
could somebody make me an admin on the jupyterhub org? I think I just have "member" status right now

**Comment by choldgraf** [comment]
hey folks - I spent a bit of time this morning moving the billing repositories to the jupyterhub repo, here's a binder link for the new billing analysis notebook!

https://mybinder.org/v2/gh/jupyterhub/binder-billing/master?filepath=analyze_data.ipynb

The general structure is:

* `binder-data` is a repository that has a script to download the latest billing data and process it into a `json` file that is readable by pandas
* `binder-billing` is a repository with a notebook that downloads the latest `json` in `binder-data` and lets you analyze/plot/etc. This is the sharable repository.

The goal here is to decouple the data from the analysis so that the `binder-billing` repo doesn't get too bloated, and so that if we change the data structure / location it won't be a big deal. I know that storing data as a `json` object in a github repo is *not* a long-term plan, but at least this gets the data up there for the world to see if they're interested.

*note that `binder-data` uses `gsutil` so you'll need to get that set up on your machine before it'll run properly*

Now, what would be *really* interesting is if we could add in a stream of usage statistics to `binder-data` so that we could cross reference things like # users with daily $$$...that'd be quite useful for folks!

Anyway, I propose that we close this issue so that we can have more specific issues in the future...does that work for people?

Also, are people OK with me sharing this binder link etc? One way we should write a blog post on binder costs...

**Comment by choldgraf** [comment]
as the core goal of this issue is now solved, I'm going to close this in lieu of https://github.com/jupyterhub/mybinder.org-deploy/issues/345 which I just opened, and is specifically about automating this process
