### ISSUE TITLE
Matplotlib.org binder link

### ISSUE THREAD

**Issue by jklymak** [jupyterhub/mybinder.org-deploy#2060]
### A link to the repository

https://github.com/matplotlib/mpl-brochure-binder
https://mybinder.org/v2/gh/matplotlib/mpl-brochure-binder/main?labpath=MatplotlibExample.ipynb

### Why are you concerned this repository maybe liable for banning?

Matplotlib would like to link the binder above from our new landing page which will be served at https://matplotlib.org/ to show folks that Matplotlib is interactive.  

We are not really sure how many hits this will make, but likely quite a few when we put the new page up, and then intermittent after that.  

Happy to talk about if this is even reasonable or not, or discuss figuring out hosting for our own binder instance somewhere. (cc @QuLogic, @tacaswell, @story645)

**Comment by yuvipanda** [comment]
Did this go live?

**Comment by jklymak** [comment]
Its live on our brochure site that will be copied over to the main site in the next day or two?  https://matplotlib.org/mpl-brochure-site/

**Comment by tacaswell** [comment]
This went live a few hours ago.

**Comment by rgaiacs** [comment]
I'm closing this as it seens resolved.
