### ISSUE TITLE
Canadian Open Neuroscience Platform Lunch & Learn Workshops 2021

### ISSUE THREAD

**Issue by jerdra** [jupyterhub/mybinder.org-deploy#2063]
### 1. Who you are

We're a cross-institutional team of Canadian researchers who've come together to provide open-source learning modules for the neuroscience community to increase the computational competencies of trainees. In collaboration with the Software Carpentries we've established several modules that are available to be taught at any institution.

### 2. A few details about the event/course/context

We're currently hosting a weekly series of workshops under the title "CONP Lunch & Learn" which is aimed at teaching how to organize, analyze, and visualize neuroimaging data using Python; to promote development of open-source analysis code and to garner adoption of community-supported neuroimaging python tools by new trainees. The workshop this week (Friday Nov. 12) will be focused on resting state functional neuroimaging analysis using material provided in the following repository:

https://github.com/carpentries-incubator/SDC-BIDS-fMRI

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

No, the workshop and material are free for all to use and teach

### 4. A link to the repository you are using

https://github.com/carpentries-incubator/SDC-BIDS-fMRI, gh-pages branch

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

### 6. How many people you expect to attend the event

Our recent workshops in this series have had 50-80 attendees

### 7. The exact times and dates of the event(s) (with timezone information)

Friday Nov 11 11:00am-3:30pm EST

### 8. How do you plan to give mybinder.org a shout out at the event

We will verbally acknowledge and promote mybinder as an excellent tool to share analysis notebooks within the science community. In addition, we plan on emphasizing the usefulness of the easy-to-startup environment provided for by the mybinder service. Finally, all our carpentries courses heavily rely on mybinder as the central platform for enabling teachability, we're know that new instructors that take on our material will also use the mybinder platform to facilitate teaching.   

We're hoping to have an increase for both the memory quota as well as the timeout interval during the workshop period. Thanks!

**Comment by manics** [comment]
Unfortunately I don't think we can easily bump the memory or timeout for individual repositories.

A possible workaround for the memory limit is to use https://notebooks.gesis.org/binder/ which is one of the members of the mybinder.org federation, but at present has a larger memory quota than others. It would mean temporarily changing your URLs though- long term it's best to use the official `mybinder.org` URL as it's more stable over the longer term, but as a one-off you could direct people to https://notebooks.gesis.org/binder/
