### ISSUE TITLE
2021-12-03,07 Temporary increase in limits for a repository

### ISSUE THREAD

**Issue by inchinn1** [jupyterhub/mybinder.org-deploy#2079]

**Comment by minrk** [comment]
👍 If you'd like to open a PR bumping for your repo(s) like https://github.com/jupyterhub/mybinder.org-deploy/pull/2078 , we can merge it before the workshop. If you're not comfortable with that for any reason, we can do the PR.

**Comment by inchinn1** [comment]
Hi,

I am sorry I am not entirely sure how to do this, I did attempt it but got lots of errors when the checks were performed..

I would appreciate it if you were able to help with this..

On 23 Nov 2021, 15:34 +0000, Min RK ***@***.***>, wrote:

👍 If you'd like to open a PR bumping for your repo(s) like #2078<https://github.com/jupyterhub/mybinder.org-deploy/pull/2078> , we can merge it before the workshop. If you're not comfortable with that for any reason, we can do the PR.

**Comment by minrk** [comment]
No worries! Bumped in #2085
