### ISSUE TITLE
Begin logging true origin as well as internal IPs for requests

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#209]
I'm not sure if this is something wrong in our ingress config here, or in an upstream chart, but we are again (still?) logging only internal kubernetes ips associated with requests, rather than the true origin, which is important for diagnosing issues.

**Comment by minrk** [comment]
Now that we are having traffic issues, discarding this information is becoming a real impediment to diagnostics.

**Comment by yuvipanda** [comment]
@minrk do we do this now?

**Comment by betatim** [comment]
If we are (or not) we should add to the SRE guide what a good way of looking at this is. We do have the real IP in some of the logs on stackdriver. I think mostly in the CHP logs. The single user notebook servers only log internal IPs.

Right now I am asking myself "why is https://github.com/QuantStack/xeus-cling so popular since about 12h ago?" and struggling to find an answer that satisfies me. Seeing the referrer site would help as well as having the real IP in the pod logs.

**Comment by minrk** [comment]
I believe this is fixed everywhere but the singleuser logs, where we need to set `trust_xheaders = True`. This would be true by default for jupyterhub, but since we override it back to the vanilla notebook, it doesn't trust these by default.

**Comment by minrk** [comment]
I'd like to try addressing this with #760

**Comment by minrk** [comment]
Actually, no, we are already doing this. All our logs have the right ips, looks like.

**Comment by betatim** [comment]
When I look at the logs of a user pod I see lines like:
```
[I 10:25:12.753 NotebookApp] 302 GET /user/my-repo-here-6sl70jup/ (10.12.0.69) 0.84ms
```
from your above comment it sounds like the IP here should be the external one or is this one more thing we need to enable?

**Comment by minrk** [comment]
That's a request that is indeed coming from inside the cluster. It's JupyterHub's internal check that the server is up. Check the subsequent logs, or [in general 302 messages](https://console.cloud.google.com/logs/viewer?project=binder-prod&minLogLevel=0&expandAll=false&timestamp=2018-10-31T10:41:41.184000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2018-10-31T09:43:51.789Z&dateRangeEnd=2018-10-31T10:43:51.789Z&interval=PT1H&resource=container&scrollTimestamp=2018-10-31T10:43:40.000000000Z&logName=projects%2Fbinder-prod%2Flogs%2Fnotebook&filters=text:302) which show real ips.

**Comment by betatim** [comment]
Aha! Thank you :)
