### ISSUE TITLE
HTTP 413: payload too large

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#210]
There may be a problem with the ingress configuration. I'm seeing "HTTP 413: Payload too large" when trying to save a large-ish notebook with figures. We fixed this with an annotation before, but ingress configuration has changed recently. The annotation probably just got lost somewhere.

**Comment by yuvipanda** [comment]
I still see it here: https://github.com/jupyterhub/mybinder.org-deploy/blob/staging/mybinder/values.yaml#L39

**Comment by yuvipanda** [comment]
We also have https://github.com/jupyterhub/mybinder.org-deploy/blob/staging/mybinder/values.yaml#L107

**Comment by minrk** [comment]
Not sure what's the cause. Reproducible with this cell:

```python
from IPython.display import publish_display_data
publish_display_data({
    'text/plain': 'this is big!',
    'application/big-data': 'x' * (1024 * 1024),
})
```

(produces 1MB output, indicating 1MB cutoff, which is the nginx default and the same line we had before we added the proxy file size config). Maybe there's a typo somewhere? Or one more ingress to set it on?

**Comment by yuvipanda** [comment]
@minrk I think it's from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/346. Should be fixed when that gets deployed

**Comment by yuvipanda** [comment]
We fixed this!
