### ISSUE TITLE
Allow prime cluster to be full?

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#2115]
Currently the federation-redirect doesn't allow the prime cluster to be full, even when it has a quota. We do this in part because we've never been cost-constrained on GKE, which we no longer assume.

Should we allow the prime cluster to be full and have a 'no healthy backends' state for the redirector when everyone is full up?

**Comment by minrk** [comment]
BTW, the prime cluster can consider _itself_ to be full, but the federation-redirector still does not. So this means that launches will be rejected, but the requests will still be routed to the prime cluster.

**Comment by betatim** [comment]
If the prime host is full full (hard limit) it will show an error message to the user, right? If that is the case I think we can keep sending traffic to the prime (especially after #2129) and have it fail there. My assumption is that if we stopped traffic at the redirector all it would do is show an error. So better to just have one place where there is an error message.

**Comment by minrk** [comment]
We do this now - prime cluster still gets traffic only when everybody else is full/unhealthy, which mostly results in "I'm full" messages
