### ISSUE TITLE
Request for extra resource during STFC Particle Physics Masterclass (15th and 16th March)

### ISSUE THREAD

**Issue by olaiya** [jupyterhub/mybinder.org-deploy#2137]
### 1. Who you are
STFC (UK research organisation) staff

### 2. A few details about the event/course/context
We are running a virtual event introducing school students to particle physics, with some hands-on data analysis examples.
https://www.eventbrite.co.uk/e/registration-of-interest-particle-physics-masterclass-2022-with-ral-tickets-169778850111

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
The event is free of charge to all participants.

### 4. A link to the repository you are using
https://github.com/olaiya/zboson-exercise/

### 5. What type of event it is:
- [ ] talk
- [ ] workshop
- [ ] lecture course
- [x ] training session

### 6. How many people you expect to attend the event
500 people simultaneously

### 7. The exact times and dates of the event(s) (with timezone information)
9:00 - 17:00 GMT, Thursday 15th and 16th March

### 8. How do you plan to give mybinder.org a shout out at the event
We will thank mybinder for the contribution while running the session, and it will also be listed on slides.

Happy to discuss or clarify any of this.

**Comment by manics** [comment]
Hi! Unfortunately mybinder.org is short on funding at the moment and we don't yet know when it'll be resolved https://github.com/jupyterhub/mybinder.org-deploy/issues/2138

Feel free to check with us in a week's time, but if you can find an alternative host for your workshop that would be better.

I took a quick look at https://github.com/olaiya/zboson-exercise/blob/master/Exercise.ipynb and it looks like you're only using matplotlib, pandas, numpy. If so there's the experimental [JupyterLite project](https://jupyterlite.readthedocs.io/en/latest/) which runs JupyterLab entirely in your browser. It's not the same as running a notebook on mybinder.org, but if you can't find a suitable host this is worth considering. If you need help on porting your repository to work with JupyterLite post a message on https://discourse.jupyter.org/ or https://github.com/jupyterlite/jupyterlite
