### ISSUE TITLE
Université Laval : Request for a workshop (7th March)

### ISSUE THREAD

**Issue by gacou54** [jupyterhub/mybinder.org-deploy#2141]
### 1. Who you are
Gabriel Couture, scientific software developer at Université Laval

### 2. A few details about the event/course/context
Workshop on how to use REST API for (engineering) physics students (part of a larger event). We have set up a REST API and want to deploy Jupyter notebooks for participants from which they will be able to interact with the API.  
[link to the event](http://www.dcclab.ca/progfest/?lang=fr)

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
Regular attendees pay a fee of 20$CAD for the whole event (the fee is for food), speakers and organizers do not receive any compensation.

### 4. A link to the repository you are using
https://github.com/ulaval-rs/prog-fest-web-workshop

### 5. What type of event it is:
- [ ] talk
- [x ] workshop
- [ ] lecture course
- [ ] training session

### 6. How many people you expect to attend the event
30 to 40

### 7. The exact times and dates of the event(s) (with timezone information)
14:30 - 16:00 EST, 7th Mars

### 8. How do you plan to give mybinder.org a shout out at the event
Binder will be listed on the slides, and its contribution will be highlighted when participants will have to open the notebook.

Thank you very much!

**Comment by gacou54** [comment]
I just saw that the default concurrent user limit is 100 for a single repo (https://mybinder.readthedocs.io/en/latest/about/user-guidelines.html?highlight=limits#maximum-concurrent-users-for -a-repository). That should be more than enough for my needs. Sorry about that. We will still make a Shout out to mybinder.org :).  Have a nice day!

**Comment by minrk** [comment]
@gacou54 you should know that mybinder.org is currently running at reduced capacity due to a funding shortage, so while the _per repo_ limit is unlikely to affect you, Binder as a whole may be full.

**Comment by gacou54** [comment]
@minrk thanks for the information. Do you know if I should find another solution for next Monday? (by the way sorry for the short notice for my event)

**Comment by rgaiacs** [comment]
Closing because the workshop already happen.
