### ISSUE TITLE
temporary increase in limits for a repository to help with running an event

### ISSUE THREAD

**Issue by JussiRoos** [jupyterhub/mybinder.org-deploy#2149]
### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [ ] training session

**Comment by JussiRoos** [comment]
Not relevat

**Comment by JussiRoos** [comment]
Not relevat, closing

**Comment by rgaiacs** [comment]
Closing because the workshop already happen.
