### ISSUE TITLE
extending the 10 minutes of inactivity

### ISSUE THREAD

**Issue by panoramasofcinema** [jupyterhub/mybinder.org-deploy#2151]
### 1. Who you are
hello. my name is Jorge and I would like to tell you how helpful mybinder is for my research. thank you.
I co-lead a course at ETH Zurich's Department of Architecture and mybinder is an essential part of it. my request is regarding the 10min of idle time after which the server is disconnected. would it be possible to extend this time (to 20min, for example) for a few days? since the course's assignment requires the students to multi-task, this idle time would really help them to ease their work.
I believe that our notebooks do not consume extraordinary resources.
### 2. A few details about the event/course/context
the course lasts 4 weeks-time each semester. 
### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)
ETH Zurich is a public research university. students don't pay for the course.
### 4. A link to the repository you are using
https://github.com/panoramasofcinema/search_images
https://github.com/panoramasofcinema/characters_notebook
https://github.com/panoramasofcinema/movies_notebook
https://github.com/panoramasofcinema/create_panorama
### 5. What type of event it is:
- [ ] talk
- [ ] workshop
- [x] lecture course
- [ ] training session
### 6. How many people you expect to attend the event
~25 students attend the course.
### 7. The exact times and dates of the event(s) (with timezone information)
16.3. until 12.4. all-day, Zurich time.
### 8. How do you plan to give mybinder.org a shout out at the event
mybinder is mentioned and linked to on the course's website, and mentioned during the introductory lectures. in addition, I would be happy to place mybinder's logo online.
https://panoramasofcinema.ch/search

thanks for considering this requests!

**Comment by betatim** [comment]
Hi @panoramasofcinema (greetings from "down the lake" 👋 )

We can't increase the timeout on a per repository level and increasing it for all repositories would increase the number of "idle" repositories hanging around.

Instead our recommendation is that you ask users to do something to prevent the timeout from happening. For example you can open a terminal or add a cell to your notebook that does something like `time.sleep(20 * 60)` (as long as a cell is running the idle timeout won't apply).

Would that work?

**Comment by panoramasofcinema** [comment]
hello neighbor @betatim ☀️

thanks a lot for the message.
i understand the situation and think that your proposal should work.

have a good weekend !

**Comment by betatim** [comment]
Thanks a lot! I will close this issue as it sounds like you are happy. If for some reason this doesn't work or there are follow up questions feel free to re-open (for a new/different topic please make a new issue).
