### ISSUE TITLE
Request to bump resources for day event

### ISSUE THREAD

**Issue by dehann** [jupyterhub/mybinder.org-deploy#2165]
### 1. Who you are

NavAbility is a small company working to make robotic navigation software accessible through open-source.
- (marketing site) https://www.navability.io/
- (open project) https://juliarobotics.org/Caesar.jl/latest/

### 2. A few details about the event/course/context

IEEE International Conference on Robotics and Automation (ICRA).  We are hosting a workshop tutorial  called "Canonical DIY Tutorials on Non-Gaussian SLAM and Computation" with purpose of communicating and demonstrating new algorithmic techniques for processing sensor data for calibration / localization / mapping.  The event is intended to drive networking with community and industry, and educate a wider audience on what the open-source technology is capable of.  We intend for this to attract more people to the overall project.
- https://icra2022.org/program/workshops-and-tutorials
- https://www.navability.io/icra-2022-non-gaussian-slam-workshop/

The event caters for both in person and virtual attendance.

### 3. If money is changing hands (attendees pay a fee, speaker is getting paid, free, etc)

Both in-person attendees and the we the presenters are paying IEEE conference fees to attend the event.  Virtual registration for the event is free.

### 4. A link to the repository you are using

There are 5 Tutorials in different programming languages, all kept together in one repo here:
- https://github.com/NavAbility/BinderNotebooks

### 5. What type of event it is:
- [ ] talk
- [x] workshop
- [ ] lecture course
- [x] training session

### 6. How many people you expect to attend the event

Current registration numbers has ~120 in person attendees plus ~150 virtual attendees.  There may be more virtual attendees visiting throughout the day long event,  as well as more in-person attendants who walk-in during the day too.

### 7. The exact times and dates of the event(s) (with timezone information)

Daylong 27 May 2022 (Philadelphia, USA), 8AM-5PM Eastern Daylight Time, USA.

### 8. How do you plan to give mybinder.org a shout out at the event

We will promote Binder as a sponsor for the event via logo shoutout on both the Repo README, and NavAbility's marketing releases regarding the event.  Thank you very much for considering, MyBinder.org is already empowering more people to be part of the future robotics technologies.

**Comment by dehann** [comment]
Hi, just a bump on this issue please.  Thanks for considering!

**Comment by GearsAD** [comment]
Hi, we're giving the conference talk in two days - could you please help us with this ticket? Thanks!

**Comment by GearsAD** [comment]
No worries, thank you so much! I'll make a PR in a few moments.

**Comment by GearsAD** [comment]
Here we go, thanks again - https://github.com/jupyterhub/mybinder.org-deploy/pull/2179

**Comment by manics** [comment]
Thanks, good luck with the workshop!
