### ISSUE TITLE
Repo got banned. No idea why

### ISSUE THREAD

**Issue by thht** [jupyterhub/mybinder.org-deploy#2169]
Hi,
my repo (https://gitlab.com/thht-teaching/ss22-music-markov) got banned. I have no idea why. If I violated any policies, I am truly sorry, but please tell me what my offense was so I can do better next time.

Best,
Thomas

**Comment by manics** [comment]
Hi! Your repo doesn't appear to be banned, and I can trigger a mybinder build (which then fails, but that's nothing to do with any bans). Can you show us your entire error message please?

**Comment by thht** [comment]
hi,
i just tried it again and i get this error message:
```
Sorry, thht-teaching%2Fss22-music-markov/HEAD has been temporarily disabled from launching. Please contact admins for more info!
```

in order to be able to maybe reproduce the problem better, here is the direct mybinder url: https://mybinder.org/v2/gl/thht-teaching%2Fss22-music-markov/HEAD

**Comment by thht** [comment]
ok. if i launch it but select the repo to be a generic git repo instead of a gitlab repo, it launches....

**Comment by MridulS** [comment]
Yeah, I banned all gitlab repos couple of months back as it seems pretty easy to create spam accounts on gitlab and upload the mining binaries. I have done some other things to fight the miners so I think its safe to turn on gitlab now.

**Comment by MridulS** [comment]
@thht you didn't do anything wrong here, it was the cryptocurrency miners that forced me to ban all gitlab repos. Sorry about that! It should work now.
