### ISSUE TITLE
Upgrade linux distro on OVH nodes 

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#2176]
In https://github.com/jupyterhub/mybinder.org-deploy/pull/2174#issuecomment-1134272131, we learn that OVH nodes are on Linux Kernel 4.15, which [reached EOL](https://lkml.iu.edu/hypermail/linux/kernel/1804.2/03399.html) on April 2018. I'm guessing Ubuntu still supports it in some form as it was shipped with Ubuntu 18.04. But it'll definitely make it a bit more complicated to deploy cryptnono and other [bpftrace](https://github.com/iovisor/bpftrace) based anti-cryptomining measures.

How can we upgrade the base distro on those nodes? Even bringing it up to 20.04 will help as that brings us to Kernel 5.x

**Comment by yuvipanda** [comment]
@mael-le-gal do you think you can help us? :)

**Comment by consideRatio** [comment]
I thumbed up https://github.com/ovh/public-cloud-roadmap/issues/259 :)

**Comment by yuvipanda** [comment]
We're on a new enough version of the base OS now. Just verified.
