### ISSUE TITLE
Update cert-manager - almost two years outdated

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/mybinder.org-deploy#2183]
Maybe we have worked around/avoided the problems in https://github.com/jupyterhub/mybinder.org-deploy/issues/2051 already caused by using an old version of cert-manager. But overall, I think we should try get cert-manager updated anyhow as we are at 0.15.2, released .on Jul 1, 2020 while 1.8.0 is out now, released Apr 5, 2022.

https://github.com/jupyterhub/mybinder.org-deploy/blob/0cf568bd468c5dd5dbe5c29dfd394057cdd849e0/.github/workflows/cd.yml#L39-L46

Since cert-manager is installed without helm instead of as a dependency of the mybinder chart, this may actually possibly be as easy as updating the version and migrating configuration if needed. I'm not sure. Any helm chart with CRDs like cert-manager is a bit tricky to manage with `helm` as `helm` won't upgrade CRDs part of a Helm chart.

Looking at https://cert-manager.io/docs/release-notes/ and inspecting how we do things, we should be good to make a few upgrade steps at least, to 1.1 based on what I've read so far.

https://github.com/jupyterhub/mybinder.org-deploy/blob/3804b1046b6524e3ec70e6fcd6f6857405ee92ef/deploy.py#L248-L253

---

This issue relates to ingress-nginx upgrades, because cert-manager needs to be able to manipulate and handle Ingress resources. I think the right call is to merge #2214 before doing anything to cert-manager, but since cert-manager isn't critical for function short term, I suggest we finish all upgrade of ingress-nginx if possible without intermixing a cert-manager upgrade in between.

**Comment by minrk** [comment]
closed by #2242
