### ISSUE TITLE
OVH k8s version update, to k8s 1.21 from k8s 1.20

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/mybinder.org-deploy#2225]
If possible, it would be great to have OVH catch up to k8s 1.21. All other federation members managed in this repo are at k8s 1.21. Note that we can't yet upgrade to k8s 1.22 because of outdated versions of various helm chart dependencies though.

It is something relevant to get done over time no matter what, but I think it can could help me avoid issues or only tackle them at a single time when migrating our PodDisruptionBudget resources from v1beta1 to v1.

Ping @mael-le-gal

**Comment by mael-le-gal** [comment]
Done !

```
k get nodes
NAME     STATUS   ROLES    AGE     VERSION
node-1   Ready    <none>   2y10d   v1.21.5
node-2   Ready    <none>   2y3d    v1.21.5
node-3   Ready    <none>   2y3d    v1.21.5
```

**Comment by consideRatio** [comment]
Nice, thanks @mael-le-gal!
