### ISSUE TITLE
cert-manager-webhook intermittently reachable from turing's k8s api-server cause issues

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/mybinder.org-deploy#2249]
NOTE: This issue was originally about killing all coredns pods, as that was believed to be causing an issue for the k8s api-server to reach the cert-manager-webhook.

---

@minrk while there are two coredns replicas and an rollingupdate is made by coredns, this logic bypasses it.

```python
            print("Reloading dns pods")
            kube.delete_collection_namespaced_pod(
                "kube-system",
                label_selector="k8s-app=kube-dns",
            )
```

We could either do...

```
kubectl rollout restart deploy coredns
```

Or we could make a label change on the pod spec of the coredns deployment to have a key=value with a new hash to make the deployment controller rollout a new version of the pods etc.

I think `kubectl rollout restart` may be to actually submit a patch request. See https://github.com/kubernetes-client/python/blob/251a1b3f86bc5e9aba17c5b764a0368167e6f73e/examples/dynamic-client/deployment_rolling_restart.py#L82-L95.

**Comment by consideRatio** [comment]
#2265 made us restart the coredns pods using a rollout. But, I think the readinessProbe is slow to react and makes a terminating pod still be considered ready, and due to that ends up receiving traffic a while too long.

Due to this, I think we must await the restart to avoid issues. I think... But I'm not sure. Hmmm...

Do we expect a failure like below if ... ?:
1. the dns pod doesn't respond to the lookup request for some reason
2. the dns pod responds with "not found" to the lookup request for some reason

 I'm not sure. Well I figure the k8s api-server could experience a DNS issue itself, or the cert-manager mutating webhook pod could experience it and fail to respond to the k8s api-server in time.

```
Error: UPGRADE FAILED: cannot patch "letsencrypt-staging" with kind ClusterIssuer: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "[https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s](https://cert-manager-webhook.cert-manager.svc/mutate?timeout=10s)": context deadline exceeded && cannot patch "letsencrypt-prod" with kind ClusterIssuer: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "[https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s](https://cert-manager-webhook.cert-manager.svc/mutate?timeout=10s)": context deadline exceeded
```

Aaargh... Well, I think tweaking the readinessProbes of the coredns pod could improve things, to make it not ready on termination quicker maybe. Hmmm... How fast do they terminate?

**Comment by consideRatio** [comment]
I'm testing the webhook over and over by making `kubectl edit` on a clusterissuer resource `letsencrypt-staging`, adjusting a dummy annotation. I've found that the k8s api-server is unreliable in getting a response from the webhook, and that the webhook doesn't log incoming requests served either.

**Comment by consideRatio** [comment]
Conclusion: there are k8s api-server -> cert-manager-webhook service/pod intermittent issues of some kind, and there is no trace of what may go wrong that I've found.

**Comment by consideRatio** [comment]
```
(base) ~/dev/jupyterhub/mybinder.org-deploy (master)$ kubectl edit clusterissuer letsencrypt-staging 
error: clusterissuers.cert-manager.io "letsencrypt-staging" could not be patched: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": context deadline exceeded
You can run `kubectl replace -f /tmp/kubectl-edit-1035928687.yaml` to try this update again.
(base) ~/dev/jupyterhub/mybinder.org-deploy (master)$ kubectl edit clusterissuer letsencrypt-staging 
clusterissuer.cert-manager.io/letsencrypt-staging edited
(base) ~/dev/jupyterhub/mybinder.org-deploy (master)$ kubectl edit clusterissuer letsencrypt-staging 
clusterissuer.cert-manager.io/letsencrypt-staging edited
(base) ~/dev/jupyterhub/mybinder.org-deploy (master)$ kubectl edit clusterissuer letsencrypt-staging 
clusterissuer.cert-manager.io/letsencrypt-staging edited
(base) ~/dev/jupyterhub/mybinder.org-deploy (master)$ kubectl edit clusterissuer letsencrypt-staging 
clusterissuer.cert-manager.io/letsencrypt-staging edited
(base) ~/dev/jupyterhub/mybinder.org-deploy (master)$ kubectl edit clusterissuer letsencrypt-staging 
clusterissuer.cert-manager.io/letsencrypt-staging edited
(base) ~/dev/jupyterhub/mybinder.org-deploy (master)$ kubectl edit clusterissuer letsencrypt-staging 
clusterissuer.cert-manager.io/letsencrypt-staging edited
(base) ~/dev/jupyterhub/mybinder.org-deploy (master)$ kubectl edit clusterissuer letsencrypt-staging 
clusterissuer.cert-manager.io/letsencrypt-staging edited
(base) ~/dev/jupyterhub/mybinder.org-deploy (master)$ kubectl edit clusterissuer letsencrypt-staging 
clusterissuer.cert-manager.io/letsencrypt-staging edited
```

I noticed that the first request failed, and then the second took a while but succeeded, but then the following were fast. It was as if it was a spinup duration, and once handled, things went fine.

**Comment by consideRatio** [comment]
@callummole I think the following debugging is needed, and I can't do it without AKS web admin console access, which I don't have afaik.

1. Try `kubectl edit clusterissuer letsencrypt-staging` where you modify some dummy annotation until you experience a failure with `context deadline exceeded`.
2. Try figure out what the k8s api-server logs about this incident, it is what received the request and probably it is what tried to reach out to the cert-manager-webhook as registered via the MutatingWebhook (`kubectl get mutatingwebhookconfiguration cert-manager-webhook -o yaml`).
   I suspect it for example could have a DNS cache, and everything works well as long as it can successfully translate the domain `cert-manager-webhook.cert-manager.svc` to an IP, but that something with the DNS lookup is intermittently failing. But hopefully we can get information about what is really wrong when the k8s api-server makes these requests with more details than just `context deadline exceeded`.

**Comment by minrk** [comment]
I don't think awaiting the restart is likely to help much - this restart is not that common an event (the majority of the time, this does not restart because the stub file didn't change).

See https://github.com/jupyterhub/mybinder.org-deploy/issues/2252#issuecomment-1150956296 for why I think the health issues are actually _disk_ related. I don't think this restart has any significant effect on turing's health, and we don't need to put more effort into rolling out coredns more robustly.
