### ISSUE TITLE
new upgrade bot loses most useful changelog: binderhub, 

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#2290]
binderhub and repo2docker bumps include the git hash, and henchbot created automatic GitHub compare links to show the changes (extracted hash from image/chart tag and put `https://github.com/repo/compare/$before...$after` in the body).

It would be handy if our new bot could preserve that functionality, since it's the most relevant change set to have a link to from the PRs.

**Comment by manics** [comment]
I just started looking into this, I think the easiest way is to pull out the short commit SHA from the image name, e.g. `7580a30..0345a86`
```diff
-      build_image: quay.io/jupyterhub/repo2docker:2022.02.0-88.g7580a30
+      build_image: quay.io/jupyterhub/repo2docker:2022.02.0-90.g0345a86
```
and modify https://github.com/executablebooks/github-activity to
- pull out the list of PRs between commits (I've got an old PR in https://github.com/executablebooks/github-activity/pull/54 that almost does that)
- add some output flags to only output the list of PRs

**Comment by manics** [comment]
I decided it'd be easier to write a script: https://github.com/jupyterhub/mybinder.org-deploy/pull/2348
