### ISSUE TITLE
Request to allow upto 500 users to access the repository at one time for Grace Hopper Conference 2022

### ISSUE THREAD

**Issue by aamodini** [jupyterhub/mybinder.org-deploy#2321]
supportLabel: support

I am creating a Level Up Lab for the Grace Hopper Conference 2022 (hosted Sept 20-24th) for 60 minutes that will require all workshop attendees (350-500) to access and work through this repository. Can you please let me know if this is possible? The repository I want to use is this: ![Bias-Testing-Framework](https://github.com/aamodini/bias-testing-framework)

**Comment by manics** [comment]
Hi. Sorry for not responding to this, hope the workshop went well. In future if no-one responds please ping us again.
