### ISSUE TITLE
Request to bump resources for tutorials and notebook talks at PyHEP 2022

### ISSUE THREAD

**Issue by matthewfeickert** [jupyterhub/mybinder.org-deploy#2333]
### Who you are

@matthewfeickert ([PyHEP 2022 workshop](https://indico.cern.ch/event/1150631/) organizer contact and contact for [PyHEP 2020 and PyHEP 2021 resource requests](https://github.com/jupyterhub/mybinder.org-deploy/issues?q=is%3Aissue+author%3Amatthewfeickert+is%3Aclosed)).

### About the event

This is for tutorials and notebook talks at the [PyHEP 2022 workshop](https://indico.cern.ch/event/1150631/) 2022-09-12 through 2022-09-16.

### Any money changing hands?

No, all speakers and organizers are volunteers. The workshop is free of charge and all resources will be made publicly available both on the [workshop website/Indico page](https://indico.cern.ch/event/1150631/) and on the [High Energy Physics Software Foundation YouTube channel](https://www.youtube.com/channel/UCv4hukXGkCYvBClQMKzypnQ).

### Repository link

TBD. Given a request from 2021 (https://github.com/jupyterhub/mybinder.org-deploy/issues/1947#issuecomment-873577455) I'm asking for resources to be bumped by PRs submitted by me for the repos.

### Type of event

workshop

### Number of attendees

There are over 1000 attendees registered, but we would anticipate that an upper _estimate_ would be maybe 300-500 would connect at this time based on PyHEP 2020, 2021 which had similar numbers.

### Dates and times

14:00 to 18:00 UTC+2 each day from 2022-09-12 through 2022-09-16.

### More than 2 weeks before event

Yes

### How you will support Binder

We will make an announcement at the start of the workshop about Binder, the service, and how the resources are being provided. If there is specific language the Binder team would like us to use we are happy to integrate this in. c.f. [PyHEP 2021 announcements](https://indico.cern.ch/event/1019958/contributions/4430363/) for an example of what we have planned. Given the large usage request if additional support would be viewed as necessary we would be happy to discuss (I missed the last Jupyter Hub meeting, else I would have explicitly asked about this there).

### Extra information

@matthewfeickert is happy to manage all PRs to control the allocations for each day. c.f. PR #1980 and PR #1986 for examples of PyHEP 2021 allocations.

**Comment by matthewfeickert** [comment]
Based on last year's request, I'll tag @manics and @yuvipanda for this (my apologies if there are other people that are on shift that should be getting tagged instead).

**Comment by yuvipanda** [comment]
This seems good to me, can you open PRs and tag me, @matthewfeickert?

**Comment by matthewfeickert** [comment]
> This seems good to me, can you open PRs and tag me?

Sure! I won't be able to do that until probably at least the first week of September as we'll need to get the repository URLs from all the presenters.

What is more desirable on your end? 1 PR per repo (like I did in 2020), or 1 PR for the whole week (like in 2021 with PR #1980)?

**Comment by yuvipanda** [comment]
@matthewfeickert 1 PR for whole week sounds easier :)
