### ISSUE TITLE
Prod deploys are blocked due to turing-staging failure

### ISSUE THREAD

**Issue by manics** [jupyterhub/mybinder.org-deploy#2337]
Recent merges to master weren't deployed to production, as the `turing-staging` job is failing. E.g.
https://github.com/jupyterhub/mybinder.org-deploy/runs/7915393603?check_suite_focus=true

Both staging jobs must pass before the production deploys.

This means we've got a backlog of changes that aren't in production, and it also means requests for increased quotas (e.g. https://github.com/jupyterhub/mybinder.org-deploy/issues/2333 in September) won't go live.

Should we mark `turing-staging` as allowed to fail to unblock things?

**Comment by consideRatio** [comment]
- Closing as resolved by #2388
- Have commented about it in #2252, to help us recall removing the workaround
