### ISSUE TITLE
Document banning rules

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/mybinder.org-deploy#240]
Sometimes there's good reason to ban a repository from launching on Binder, but we should make sure that our reasons are clear for doing so in order to avoid making people unnecessarily unhappy. Let's include a section about our banning policies for the `mybinder.org` deployment. Not sure where this should go, maybe for now just a text file like `guidelines.md` that we can point people to in case we need to? For now this file could just have text like:

```
# Jupyter Usage Guidelines

This page details some guidelines and policies that we follow at mybinder.org.

## Temporary Banning

Temporary banning means that `mybinder.org` will stop building / serving Binder sessions for
a given repository. This usually happens because of some undesired behavior with the repository, such as a large, unexpected spike in traffic.

If you are temporarily banned, contact us on the [Gitter Channel](link-to-gitter) or [Open an Issue](issues-link) to discuss how to un-ban the repository.
```

**Comment by minrk** [comment]
Do we need to allow a non-public channel?

**Comment by betatim** [comment]
Do you have an idea for when we'd need a private discussion? My intuition would be that to keep ourselves honest and transparent we should document in public when a repo is getting banned and why (*). This would also be the place to discuss unbanning it or disagreeing with the ban.

What about a workflow like the following:
* create an issue documenting why a repo (or group of repos) is being banned,
* PR that implements the ban
* tag issue with a "bans" label
* issue stays open until the ban is lifted

---

(*) One potential reason for a private communication is that in the spur of the moment people will be angry and say things they later regret/are unreasonable. I'd rather deal with this in a public forum than privately.

**Comment by yuvipanda** [comment]
I like the text, @choldgraf. I also agree with @betatim re banning. I think we should have a private channel for *abuse* complaints, but that's unrelated.
