### ISSUE TITLE
Use case question: Container that deploys other containers

### ISSUE THREAD

**Issue by pm0kjp** [jupyterhub/mybinder.org-deploy#2408]
Hi!  I'm working with a use case in which a Docker container "A" spawns another container "B" to do a separate job.  Barring memory constraints, etc., and assuming A and B are in a container registry, is this architecture supported by Binderhub / mybinder.org?  TYSM.

**Comment by minrk** [comment]
No, you can't use docker to create containers from within a binder user environment (it's just a container itself). Maybe a user-space container package like podman could work? I'm not sure, though.

**Comment by pm0kjp** [comment]
Thank you, this is so useful!
