### ISSUE TITLE
Request to bump resources for Mark Cuban Foundation bootcamps

### ISSUE THREAD

**Issue by bdares** [jupyterhub/mybinder.org-deploy#2409]
## Who you are
The Mark Cuban Foundation

## About the event
This is an AI bootcamp for students

## Any money changing hands?
No, this is a free camp for students

## Repository link
https://github.com/markcubanai/Language

## Type of event
AI Bootcamp

## Number of attendees
There are 600 students and mentors

## Dates and times
Nov 12 2022, at 12PM-5PM CST

## More than 2 weeks before event
No

## How you will support Binder
We will make an announcement at the start of the bootcamp about using MyBinder.

**Comment by minrk** [comment]
Sorry, this was not enough notice for volunteers to handle the request. I hope your workshop went okay!
