### ISSUE TITLE
Temporary quota increase for a workshop

### ISSUE THREAD

**Issue by inchinn1** [jupyterhub/mybinder.org-deploy#2489]
I would like to request a temporary increase in users for a repository. Below I provide as much detail as I can.

**My details:** Jamie Johnston, Lecturer in Neuroscience

**A few details about the event/course/context:** A coding workshop to introduce coding basics to biomedical science students. Workshop tackles a biomedical data problem and illustrates how easy analysis can be with some programming skills. Workshop is designed to spark an interest in learning programming as it is increasingly necessary for biomedical research.

Workshop is part of an undergraduate module at the University of Leeds (technically a charity)

**Repository requiring a bump in users:**: https://mybinder.org/v2/gh/inchinn1/BMSC3393.git/HEAD

**What type of event it is:** Workshop

**How many people you expect to attend the event:** ~ 284

**The exact times and dates of the event(s):** Thursday 9th February 11: - 17:30 (GMT) and 10th December 10:00 to 13:30 (GMT)

**How do you plan to give mybinder.org a shout out at the event:** At the start of the workshop there will be a discussion on reproducibility in science and how Jupyter notebooks can aid this. In particular the ability to publish analysis alongside papers using myBinder will be highlighted. The intro notebook includes a 'brought to you by binder" logo

**Comment by manics** [comment]
Please could you open a PR similar to
https://github.com/jupyterhub/mybinder.org-deploy/pull/2085
a few days before your event? If you don't get a response from us please remind us, sometimes things get busy!

**Comment by inchinn1** [comment]
Great thanks, I have submitted the PR (#2498)

All the best

Jamie

Dr. Jamie Johnston
School of Biomedical Sciences
Garstang Building
University of Leeds
Leeds LS2 9JT
www.johnstonlab.org<http://www.johnstonlab.org>
https://neural.leeds.ac.uk

Tel: 0113 343 0105
On 2 Feb 2023, 22:13 +0000, Simon Li ***@***.***>, wrote:

Please could you open a PR similar to
#2085<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjupyterhub%2Fmybinder.org-deploy%2Fpull%2F2085&data=05%7C01%7Cj.johnston%40leeds.ac.uk%7Ce82b6b1674734054d38d08db056aa65d%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638109727836797913%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ynNGQirKHYTwQFuOFsl2Nx%2FMaYmYQ%2BLx%2BdDvS0I0p%2Bo%3D&reserved=0>
a few days before your event? If you don't get a response from us please remind us, sometimes things get busy!
