### ISSUE TITLE
Starkware Sessions 2/1

### ISSUE THREAD

**Issue by drspacemn** [jupyterhub/mybinder.org-deploy#2490]
**Who**
We are hosting a workshop of more than 100 people:

**What**
STARK 101 Workshops
Rothschild Blvd 57 57 Rothschild Boulevard Tel Aviv-Yafo, Tel Aviv District
Wed, February 1, 2023, 10:00 AM – 4:00 PM IST

**# Attendees**
250 Attendees

Per your [user guidelines](https://mybinder.readthedocs.io/en/latest/about/user-guidelines.html#events-and-workshops) we would like to request added capacity during the event window for the following repo:

**Repository**
https://mybinder.org/v2/gh/starkware-industries/stark101/master

**How you will support Binder**
We will make an announcement at the beginning of the workshop about the direction and usage of MyBinder

**Comment by manics** [comment]
Sorry we didn't get to this in time, it was a bit too short notice. Hopefully your workshop went well.

If possible try and give us a couple weeks notice next time, and feel free to bump the issue if there's no response after a week.
