### ISSUE TITLE
Remove Turing from the federation

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/mybinder.org-deploy#2524]
I just received an email from Docker Hub stating that they are sunsetting Free Team organisations, which is the subscription type of the account that the Turing federation member is using. https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf (There is also no option to transform the org into a regular user either, apparently.)

However, we've had discussions about removing the Turing federation member completely. I believe it is currently out of rotation due to some bugs, and the folk that were maintaining it at the Turing Institute have moved onto other things. So I'm taking this as a sign that we should clear out any Turing-related config from the repo.

**Comment by minrk** [comment]
I think that's probably right. Still a bummer.

**Comment by Vad1mo** [comment]
If, for some reason, the Docker-Sponsored Open-Source Program isn't working out, we are happy to help you out. We operate a Harbor-based [container registry as a service ](https://container-registry.com/)that has many benefits over most of the other registries out there.

There are also features regarding containerized image distribution, that might be valuable too as well.

Don't underestimate the value of owning and controlling your data, it is easier to migrate if the domain is under your control.

**Comment by sgibson91** [comment]
@Vad1mo the bigger problem is that there's no one left at the Turing institute available to maintain the kubernetes cluster. So just swapping the container registry doesn't really solve the problem. Thanks though.
