### ISSUE TITLE
Request for increase in quota: up to 1000 users and potentially 30 min session timeouts for European Space Agency (ESA) education event

### ISSUE THREAD

**Issue by MNGuenther** [jupyterhub/mybinder.org-deploy#2534]
Dear Binder Team,

Many thanks on behalf of us ESA Science and ESA Education users for maintaining this wonderful project, and offering the unique opportunity to reach classrooms worldwide with space-based data science. ESA Science and ESA Education have collaborated over the past year to develop and launch an global science education project, dubbed [HackAnExoplanet](https://hackanexoplanet.esa.int/about/). In this framework, the ESA CHEOPS mission observed two exoplanets, whose data all participating high schoolers can now examine, investigating their sizes, orbital periods, and other physical quantities.

To this end, we developed a Python/Jupyter Notebook based minimalist software mimicking a graphical interface, that allows the pupils to analyse the data using state-of-the-art tools. This software is, of course, hosted in Binder! In particular, we hosted the [active notebook](https://github.com/MNGuenther/hackanexoplanet) and its respective [Python environment](https://github.com/MNGuenther/hackanexoplanet-env) in two different GitHub repos, following the Binder FAQs for a smoother development and launch. The full link launching the Binder instance is [here](https://mybinder.org/v2/gh/MNGuenther/hackanexoplanet-env/main?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252FMNGuenther%252Fhackanexoplanet%26urlpath%3Dtree%252Fhackanexoplanet%252FGUI.ipynb%26branch%3Dmain). We are rapidly nearing the launch (3 April) and expect a large participation by global high schools from the get-go, with a particular peak at an in-parallel hackathon on 18 April. 

Would you grant us a temporarily increase in quota for up to 1000 users from 1 April until 31 May? This would cover all our main events.  If this is too long, please let us know and we can try to work out a reduced window accordingly.

On a second note, is it also possible to temporarily amend the timeout of the sessions to, say, 30 minutes? A lot of teachers indicated that they want to launch the software a bit in advance, as the Binder loading times can vary from 1 to 20 minutes in our past experience.

Many thanks
Max
On behalf of ESA's HackAnExoplanet

**Comment by minrk** [comment]
This is a super cool project! I think 1000 _additional_ concurrent users is more than we can handle on this free service (it would roughly triple peak mybinder.org load). Our current overall  capacity of the mybinder.org federation is 620, with typically around 400 users at peak, so we'd be able to handle ~200 students _at most_.

We don't currently have the ability to change the idle timeouts for a subset of projects, so increasing the idle timeout would also reduce our overall capacity.

Since this is a more single-purpose application, I'd recommend you contact [2i2c](https://2i2c.org) about operating a dedicated JupyterHub, which is much more controllable for something like this than mybinder.org.

**Comment by MNGuenther** [comment]
Thanks for the swift feedback, @minrk! Oh, we were not aware that the Binder resources are so limited, sorry! I will also reach out to 2i2c immediately - but it might be hard to switch platforms on short notice.

Would Binder be able to grant us a temporary increase to 200 simultaneous users in that case? If 1 April through 31 May is too long of a window, our expected peak days are 4 April and 18 April, in particular. That would already be a big help.

**Comment by minrk** [comment]
increasing to 200 for those two weeks is definitely within our typical range. I'm not sure about 2 months.

**Comment by minrk** [comment]
@MNGuenther quota is bumped to 300 for now (#2541), we'll see how it goes. If you really have that many students at the same time, Binder will very likely experience some trouble, so having an alternative choice is definitely advisable.

jupyterlite is far more scalable, but not every package can be installed in that environment yet. I took a stab with your repo and it didn't quite work.

**Comment by MNGuenther** [comment]
Amazing, thanks so much @minrk! We will encourage the school classes to be conscious of the resources and monitor the situation.

Also many thanks for testing it on jupyterlite, even if it did not work. Indeed, we had tried several options before, and found Binder to be the most robust and user-friendly so far.

**Comment by rgaiacs** [comment]
I'm closing this as the event already happen.
