### ISSUE TITLE
Bring back GESIS to Federation

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/mybinder.org-deploy#2543]
Hi,

as announced at https://github.com/jupyterhub/team-compass/issues/634, I joined [GESIS](https://gesis.org/). @MridulS's previous resposabilities with GESIS' BinderHub had been transfered to me.

I will be working to keep GESIS' node healthy.

Can I have a extra mentor in addition to @MridulS and @arnim? Thanks!

**Comment by arnim** [comment]
Thank you @rgaiacs. Becoming again a reliable member is of importance to GESIS :)

**Comment by yuvipanda** [comment]
yay welcome @rgaiacs :)

**Comment by rgaiacs** [comment]
Hi @minrk, thanks for the message. Our server didn't rebooted properly and we couldn't make progress in the last two weeks. We have our server running again and I'm organising things. I will open a PR when things are up and running here.

**Comment by arnim** [comment]
We need also to keep in mind that we should scale up the max pods slowly, we had some problems with stale pods in the past. But I hope that we can provided reliable capacity for 110 pods within 2 weeks 🤞
