### ISSUE TITLE
mybinder.org Julia environments fail to build: "Error during build: Failed to fetch available Julia versions: {e}"

### ISSUE THREAD

**Issue by fonsp** [jupyterhub/mybinder.org-deploy#2554]
Hi all! Thanks for your awesome work, I hope this is the right repo for this issue!

Today, my Julia repo is failing to build. 

Test URL: https://mybinder.org/v2/gh/fonsp/pluto-on-binder/v0.19.24

Full logs:

```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2docker1csadg3w'...
HEAD is now at fdda6b0 Update Manifest.toml
Python version unspecified, using current default Python version 3.10. This will change in the future.Building conda environment for python=3.10
Error during build: Failed to fetch available Julia versions: {e}
```

This error is caused by:

https://github.com/jupyterhub/repo2docker/blob/c5be2a7e3ab10efead7c207e309e6232274f9a92/repo2docker/buildpacks/julia/julia_project.py#L25-L30

which requests the list of Julia versions:

https://julialang-s3.julialang.org/bin/versions.json

And this file is currently online! Perhaps there is a networking issue?

Thanks in advance!

**Comment by fonsp** [comment]
It looks like this is an issue for all repos that use Julia: from the template https://github.com/binder-examples/demo-julia I created my repo https://github.com/fonsp/binder-demo-julia-1, and it also does not build (same error):

https://mybinder.org/v2/gh/fonsp/binder-demo-julia-1/HEAD

**Comment by minrk** [comment]
The lack of the error is https://github.com/jupyterhub/repo2docker/pull/1264

but the _fact_ of the error is the real problem. It seems like it might be an access control thing based on where mybinder.org is running? Building that repo works fine with local repo2docker.

And while I did see the failure a few minutes ago, as I debug now it seems to have gone away. So maybe it was an intermittent problem with Julia's s3 buckets?

**Comment by fonsp** [comment]
@manics I believe that the `binder-examples/conda` still runs because it was built before this error started happening, and the build is cached. So only new Julia repos/versions are affected.

**Comment by fonsp** [comment]
@minrk Thanks for looking into this issue!

It looks like it's working on `ovh`, but still an issue on `gke`. Yesterday, I only checked gke (I believe).

https://gke.mybinder.org/v2/gh/fonsp/binder-demo-julia-1/HEAD
https://ovh.mybinder.org/v2/gh/fonsp/binder-demo-julia-1/HEAD

**Comment by fonsp** [comment]
@manics Sorry for misunderstanding your post before! I know that https://julialang-s3.julialang.org/ is hosted on S3, but they also have mirrors on GCE, Azure (maybe more) to benefit from free bandwidth within those datacenters.

So this probably means that the GCE mirror is down, right? That would explain why the request works locally, and on other binder providers.
