### ISSUE TITLE
Remove turing from grafana

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/mybinder.org-deploy#2572]
Turing is still listed in Grafana dashboard:

![Screenshot 2023-04-25 at 13-52-24 1  Overview - Dashboards - Grafana](https://user-images.githubusercontent.com/1506457/234268332-90a36f55-24ec-4ec3-8234-0823802a0141.png)

**Comment by minrk** [comment]
It has been removed, thanks!
