### ISSUE TITLE
Providing resource / support for workshop

### ISSUE THREAD

**Issue by M0hsend** [jupyterhub/mybinder.org-deploy#2622]
Hello,
We organise an annual workshop, covering multi-spectral data analysis packages in microscopy (for last year info please see [here](https://diamondlightsource.atlassian.net/wiki/spaces/EPSICWEB/pages/847773697/Hyperspy+Workshop-+2022)). This year we are organising for the week of 22-26th May. We were wondering if you have any possibility of allocating more resource - in light of [this ](https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f)news - for an event like this? We will be asking for our participants to have local installations but would be ideal to have binder as back-up if this fails for some.
Many thanks,
Mohsen

**Comment by minrk** [comment]
We do not currently have any resources to allocate, but are looking for sources to support additional federation members.

**Comment by rgaiacs** [comment]
I'm closing this as the event already happen.
