### ISSUE TITLE
Request for Increase in BinderHub quota

### ISSUE THREAD

**Issue by a3chiang** [jupyterhub/mybinder.org-deploy#2650]
Hello,

My colleague, Varshini, and I are running a coding bootcamp event with middle school students at an underresourced school in San Diego on Tuesday, May 30. We are hoping to have an increased quota so that students can complete the activities individually and can get the most enriched experience out of the event. 

The repo we are using is: https://github.com/VarshiniSathish/GMBE_GS_Coding_Wrkshp

Thank you so much, 
Alyssa

**Comment by manics** [comment]
Hi! Unfortunately we've got limited capacity at the moment due to 
https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f
We're still looking for additional funding and compute.

**Comment by rgaiacs** [comment]
Hi @a3chiang, thanks for the issue. I hope you had a successful coding bootcamp event.

I'm closing this issue because the event already happen (Tuesday, May 30).
