### ISSUE TITLE
GESIS Binder "service": "JupyterHub API", "ok": false

### ISSUE THREAD

**Issue by arnim** [jupyterhub/mybinder.org-deploy#2668]
The GESIS Binder health API
https://notebooks.gesis.org/binder/health
gives 
```
{"ok": false, "checks": [{"service": "Docker registry", "ok": true}, {"service": "JupyterHub API", "ok": false}, {"service": "Pod quota", "total_pods": 60, "build_pods": 0, "user_pods": 60, "quota": 200, "ok": true, "_ignore_failure": true}]}
```

for launching this is
```
Found built image, launching...
Launching server...
Launch attempt 1 failed, retrying...
Launch attempt 2 failed, retrying...
Launch attempt 3 failed, retrying...
```

also strange is https://grafana.mybinder.org/d/nDQPwi7mk/node-activity?orgId=1&var-cluster=GESIS&from=1686645009386&to=1686663294558&viewPanel=34

cc @rgaiacs

**Comment by rgaiacs** [comment]
This is related to https://github.com/jupyterhub/mybinder.org-deploy/issues/2667.

**Comment by rgaiacs** [comment]
@arnim Thanks for your report. I believe this was resolved. Please reopen if you still encounter the same error.
