### ISSUE TITLE
GESIS Kubernetes cluster is overwhelm with Succeeded pods

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/mybinder.org-deploy#2670]
This all started around 18:45 CEST.

![Screenshot 2023-06-13 at 22-09-36 Pod Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/3c1c0a3a-e75e-4e65-b280-8c0c5b103b15)

**Comment by arnim** [comment]
Looks good now :)
https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&var-cluster=GESIS&from=1686667661164&to=1686722900508&viewPanel=3

**Comment by rgaiacs** [comment]
A manual delete of the Succeeded pods temporarily resolved the issue.

![Screenshot 2023-06-14 at 08-05-10 Pod Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/aaa13aa1-a2a1-40f0-a053-79714609cb9a)

https://github.com/jupyterhub/mybinder.org-deploy/blob/main/scripts/delete-pods.py was wrote to automate the resolution of this issue.

**Comment by arnim** [comment]
<img width="830" alt="image" src="https://github.com/jupyterhub/mybinder.org-deploy/assets/265541/91efd7a2-aba3-43f6-8372-6e601e20f9ca">

**Comment by rgaiacs** [comment]
I'm closing this as we have a script to prevent this now.
