### ISSUE TITLE
https://github.com/Qiskit/platypus-binder has twice the number of launches of other repositories

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/mybinder.org-deploy#2684]
![Screenshot 2023-06-20 at 15-53-58 Pod Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/96878daf-0acc-4c50-8e15-08a329d52cd0)

Should we ban https://github.com/Qiskit/platypus-binder as https://github.com/ines/spacy-binder (deleted) was banned in https://github.com/jupyterhub/mybinder.org-deploy/pull/582?

**Comment by minrk** [comment]
spacy-binder was blocked because of a bug causing excessive requests. Now spacy is still one of the biggest users, but more reasonable. We can contact Qiskit if their load is too high to discuss reducing the load.

**Comment by rgaiacs** [comment]
I contacted the project yesterday: https://github.com/Qiskit/platypus/issues/751#issuecomment-1598881251

**Comment by rgaiacs** [comment]
https://github.com/Qiskit/platypus/pull/2132 reduced the traffic from https://github.com/Qiskit/platypus-binder.

![Screenshot 2023-06-22 at 08-26-53 Pod Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/a1f103a4-a9a3-4d6c-8ba8-f8a9a5a0c2a4)

Closing this as resolved.
