### ISSUE TITLE
GESIS Error during build: UnixHTTPConnectionPool

### ISSUE THREAD

**Issue by arnim** [jupyterhub/mybinder.org-deploy#2704]
Building
https://mybinder.org/v2/gh/yuvipanda/example-inherit-from-community-image/yuvipanda-patch-1

at GESIS resulted in 

```
...

Removing intermediate container cf948abd4cb4
 ---> 957473d57f52
Step 8/8 : LABEL repo2docker.version=2023.06.0
 ---> Running in 56a88e5e1fc2
Removing intermediate container 56a88e5e1fc2
 ---> 6aaa1263c7d7
{"aux": {"ID": "sha256:6aaa1263c7d70651cc5843a6ff3dbd5cc905c46164bb32265ed7489db6bc4a05"}}[Warning] One or more build-args [NB_USER NB_UID] were not consumed
Successfully built 6aaa1263c7d7
Successfully tagged gesiscss/binder-r2d-g5b5b759-yuvipanda-2dexample-2dinherit-2dfrom-2dcommunity-2dimage-6e5a3d:8b672d45bcba4145c7602dc487735995ce195e6e
Error during build: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
```

CC @rgaiacs

**Comment by rgaiacs** [comment]
@arnim Thanks for the issue. GESIS BinderHub is using a cache version of https://github.com/yuvipanda/example-inherit-from-community-image/tree/yuvipanda-patch-1. Interestingly,

```
$ ls
image-tests  work
```

which is very different from https://github.com/yuvipanda/example-inherit-from-community-image/tree/yuvipanda-patch-1. For example,

1. The container does **not** have `README.md`
2. The repository does **not** have the `work` directory

Maybe @yuvipanda or @minrk can provide some clarification here regarding the difference.

I think the `Read timed out` is a network issue. Things looks OK now. https://grafana.mybinder.org is return 503 Service Temporarily Unavailable for me (reported as https://github.com/jupyterhub/mybinder.org-deploy/issues/2703) and I can't have a picture of what was happening at 3AM GMT+2 of 21 July 2023.

**Comment by rgaiacs** [comment]
I'm closing this in favour of https://github.com/jupyterhub/mybinder.org-deploy/issues/2704.
