### ISSUE TITLE
GESIS server overwhelming with `Terminating` pods

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/mybinder.org-deploy#2722]
Around 18h ago (14:00 CEST 09 August 2023) user pods started to stuck at terminating status.

**Comment by rgaiacs** [comment]
After some investigation, I found

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd container: read-only file system
```

in the logs.

Trace down why the disk switch to read-only is taking more time. I created https://github.com/jupyterhub/mybinder.org-deploy/pull/2723 to improve user experience until the server is back.

**Comment by MridulS** [comment]
@rgaiacs does the server work fine? Could you check the disk space?

**Comment by rgaiacs** [comment]
GESIS IT staff got involved in the disk switch to read-only. This is related with a problematic disk in the server.

**Comment by rgaiacs** [comment]
I'm waiting for GESIS IT staff to replace the fault disk in the server.
