### ISSUE TITLE
Getting Too Many Users error - but pretty sure there are no users...

### ISSUE THREAD

**Issue by jazzmind** [jupyterhub/mybinder.org-deploy#2725]
Hi - I have set up the following URL to configure a simple notebook for the purpose of teaching basic data science with python.

https://mybinder.org/v2/gh/intersective/binder-base/trunk?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fintersective%252Fdata-capstones%26urlpath%3Dlab%252Ftree%252Fdata-capstones%252Fskillsbuild%252Fsustainability%252Fnyc_water_project_1.ipynb%26branch%3Dtrunk

Clicking on this link creates a "too many users" error but this hasn't even been deployed to students yet... just run by people reviewing the content. Am I doing something fundamentally wrong here or perhaps the instances aren't terminating?

**Comment by lisakmalins** [comment]
I'm getting the same error ("`Too many users on this BinderHub! Try again soon.`") on a new repository that I haven't shared with anyone. This has been happening for the past couple of days. I think the issue might be that mybinder.org as a whole is overloaded at the moment?

**Comment by MridulS** [comment]
Currently mybinder.org can support 300 concurrent users.

You can check the current usage at https://mybinder.readthedocs.io/en/latest/about/status.html#federation-status.

**Comment by rgaiacs** [comment]
@jazzmind and @lisakmalins you should encounter "Too many users" less frequently after https://github.com/jupyterhub/mybinder.org-deploy/pull/2726 is merged.

**Comment by lisakmalins** [comment]
It's working for me now. Thank you @MridulS and @rgaiacs for your time! 🙏🏻

**Comment by jazzmind** [comment]
Thank you - it also is working for me... I did notice GESIS was "down". If we find that this course scales further we will look into running our own binderhub servers.
