### ISSUE TITLE
GESIS node fail to launch repository

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/mybinder.org-deploy#2729]
When building a new repository commit,

```
Successfully built ccb5723cecd5
Successfully tagged gesiscss/binder-r2d-g5b5b759-gesiscss-2dorc2-2dtest-2dbuild-ced273:01429fa5102ba6035419cf9bad2e04157bcc4391
Error during build: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
```

Is this `UnixHTTPConnectionPool` related to push the image?

# List of Related Material

- https://discourse.jupyter.org/t/i-get-read-timed-out-errors-on-when-pushing-image-ovh/1394/3

  Similar problem with OVH in 2019. ["Resolved" (?) with different docker registry for the OVH cluster.](https://discourse.jupyter.org/t/i-get-read-timed-out-errors-on-when-pushing-image-ovh/1394/10?u=rgaiacs)
- https://github.com/jupyterhub/repo2docker/issues/711

  Upstream issue at `repo2docker`.
- https://github.com/2i2c-org/utoronto-image/issues/20

  Similar issue from https://github.com/jupyterhub/repo2docker-action
- https://github.com/jupyterhub/repo2docker/pull/1124

  Pull request to repo2docker

**Comment by arnim** [comment]
Still wandering if we could mitigate these if we had an on prem container registry with pass through

**Comment by arnim** [comment]
To allow any training workshop where students can build their own binders we need to support at least 30 concurrent builds. This is fare from what we currently can do.

**Comment by rgaiacs** [comment]
A workaround to try is to extend the allowed time as suggested in https://github.com/docker/compose/issues/3927#issuecomment-1176162099

**Comment by rgaiacs** [comment]
https://github.com/docker/docker-py/issues/398 suggests that the problem is overloading GESIS machine.

**Comment by rgaiacs** [comment]
This issue is old and I cannot look at the logs.
