### ISSUE TITLE
Request to bump resources for tutorials and notebook talks at PyHEP 2023

### ISSUE THREAD

**Issue by matthewfeickert** [jupyterhub/mybinder.org-deploy#2731]
### Who you are

@matthewfeickert ([PyHEP 2023 workshop](https://indico.cern.ch/event/1252095/) organizer contact and contact for [PyHEP 2020, PyHEP 2021, PyHEP 2022 resource requests](https://github.com/jupyterhub/mybinder.org-deploy/issues?q=is%3Aissue+author%3Amatthewfeickert+is%3Aclosed)).

### About the event

This is for tutorials and notebook talks at the [PyHEP 2023 workshop](https://indico.cern.ch/event/1252095/) 2023-10-09 through 2023-10-12.

### Any money changing hands?

No, all speakers and organizers are volunteers. The workshop is free of charge and all resources will be made publicly available both on the [workshop website/Indico page](https://indico.cern.ch/event/1252095/) and on the [High Energy Physics Software Foundation YouTube channel](https://www.youtube.com/channel/UCv4hukXGkCYvBClQMKzypnQ).

### Repository link

TBD. Given a request from 2021 (https://github.com/jupyterhub/mybinder.org-deploy/issues/1947#issuecomment-873577455) I'm asking for resources to be bumped by PRs submitted by me for the repos.

### Type of event

workshop

### Number of attendees

There are over 300 attendees registered and we expect over 800 to register in total, but from previous years we would anticipate that an upper _estimate_ would be maybe 100-200 would connect simultaneously at any point.

### Dates and times

14:00 to 18:00 UTC+2 each day from 2023-10-09 through 2023-10-12.

### More than 2 weeks before event

Yes

### How you will support Binder

We will make an announcement at the start of the workshop about Binder, the service, and how the resources are being provided. If there is specific language the Binder team would like us to use we are happy to integrate this in. c.f. [PyHEP 2022 announcements](https://indico.cern.ch/event/1150631/contributions/5023604/) for an example of what we have planned. Given the large usage request if additional support would be viewed as necessary we would be happy to discuss (I missed the last Jupyter Hub meeting, else I would have explicitly asked about this there).

### Extra information

@matthewfeickert is happy to manage all PRs to control the allocations for each day. c.f. PR https://github.com/jupyterhub/mybinder.org-deploy/pull/2349 and PR https://github.com/jupyterhub/mybinder.org-deploy/pull/2352 for examples of PyHEP 2022 allocations.

We (the PyHEP workshop organizers) know that [Binder has had resources cut](https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f) in April, 2023 and that the full scope of this workshop would be too much. However, we are working with out partners in CERN IT to see if we can use CERN's BinderHub instance for some of the resources, with the goal of having MyBinder.org's resources be used primarily by workshop attendees without CERN accounts.

**Comment by manics** [comment]
Unfortunately the cut in funding means we're still at reduced capacity, so if you can use other resources, or even spin up your own temporary BinderHub (or JupyterHub with a fixed singleuser environment which is much easier) that would be very helpful and guarantee everyone can run the workshop.

You're still welcome to use mybinder.org but we can't guarantee availability.
