### ISSUE TITLE
[Documentation / Governance ] New Documenation Working Group issue under JupyterLab org for all Jupyter docs

### ISSUE THREAD

**Issue by willingc** [jupyterhub/mybinder.org-deploy#2732]
For visibility: https://github.com/jupyterlab/team-compass/issues/212

@yuvipanda @choldgraf @minrk @betatim @consideRatio @sgibson91 FYI. I'm not sure that JupyterLab org is the right place for the working group. It seems like Jupyter org would make more sense.

**Comment by yuvipanda** [comment]
Discussion on moving chat formats also happening in the jupyterlab team-compass: https://github.com/jupyterlab/team-compass/issues/213.

I have asked about the scope of that discussion

**Comment by yuvipanda** [comment]
I also posted in the documentation WG issue! https://github.com/jupyterlab/team-compass/issues/212#issuecomment-1728385508

**Comment by andrii-i** [comment]
@yuvipanda Thank you for raising this question. Change is intended for the whole Project Jupyter, not for a certain subproject. Edited description of jupyterlab/team-compass#212 to clarify this, created jupyter/governance#182 to match the scope of the issue.

**Comment by willingc** [comment]
Future discussions will be held at [`jupyter/docs` repo](https://github.com/jupyter/docs)

**Comment by yuvipanda** [comment]
Thanks for opening this issue here, @willingc! I'd have never known about it otherwise :)
