### ISSUE TITLE
Is email alert on Grafana enable?

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/mybinder.org-deploy#2820]
I would like to configure some alerts in mybinder.org Grafana server https://grafana.mybinder.org to notify @arnim and I. I try to do it but send a test email resulted in

```
Failed to send test alert.: failed to send notification to email addresses: R***@gesis.org;a***@gesis.org: dial tcp 127.0.0.1:25: connect: connection refused
```

Thanks for the help.

**Comment by yuvipanda** [comment]
afaik it was not set up, because it requires an smtp setup and what not and those are hard

**Comment by rgaiacs** [comment]
Thanks! I'm closing as "won't implement". 👍

**Comment by manics** [comment]
@rgaiacs Grafana has a webhook notifier.
https://grafana.com/docs/grafana/latest/alerting/alerting-rules/manage-contact-points/webhook-notifier/
I think with a bit of manipulation we could probably make that create a GitHub issue (in a public or private repo) and you could subscribe to that to get email notifications? Or we could hook it up to Matrix, Zulip, etc.

**Comment by MridulS** [comment]
BTW, I used to use a telegram bot hooked up to grafana alerts for my "on call" with the GESIS specific grafana. It was pretty painless and easy to maintain if I remember correctly.

**Comment by rgaiacs** [comment]
Thanks @manics and @MridulS for the suggestions. It was on my list to look notification Matrix, ...

**Comment by yuvipanda** [comment]
ya, i think telegram or pagerduty is easier to do than email.
