### ISSUE TITLE
beta.mybinder.org certificate expiry

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#283]
I got this in the mail today:

```
Hello,

Your certificate (or certificates) for the names listed below will expire in
19 days (on 01 Feb 18 01:45 +0000). Please make sure to renew
your certificate before then, or visitors to your website will encounter errors.

beta.mybinder.org

For any questions or support, please visit https://community.letsencrypt.org/.
Unfortunately, we can't provide support by email.

For details about when we send these emails, please visit
https://letsencrypt.org/docs/expiration-emails/. In particular, note
that this reminder email is still sent if you've obtained a slightly
different certificate by adding or removing names. If you've replaced
this certificate with a newer one that covers more or fewer names than
the list above, you may be able to ignore this message.

Regards,
The Let's Encrypt Team
```

Need to investigate why it hasn't been renewed by kube-lego yet and make sure we renew it before it expires!

**Comment by yuvipanda** [comment]
This would be a service disruption for the users who still have links to beta.mybinder.org.

**Comment by yuvipanda** [comment]
Does anyone else want to take this on?

**Comment by choldgraf** [comment]
I did a quick Google and didn't find anything, will look into it again
either tomorrow or Tuesday (unless somebody else beats me to it) but have
been offline as much as possible over the long weekend. I'll update here if
I figure anything out.

**Comment by yuvipanda** [comment]
I just realized how our HTTPS operates is still tribal knowledge between me and @minrk, even though it's in the config. One way to do this is perhaps for us to write this down and keep adding enough info so someone else can debug this. Am happy to pair with someone to do that!

**Comment by choldgraf** [comment]
Happy to do this on Tuesday

**Comment by yuvipanda** [comment]
+1, go enjoy your holidays in the meantime, @choldgraf!

**Comment by choldgraf** [comment]
Could this be a letsencrypt bug? I just checked the SSL certificate for `beta.mybinder.org` here:

https://www.ssllabs.com/ssltest/analyze.html?d=beta.mybinder.org&latest

And it says that it expires on April 3rd.

**Comment by choldgraf** [comment]
Just rechecked the ssllabs verifier, and we're now good thru June so the updating seems to be working. I think we can close this!
