### ISSUE TITLE
Large number of requests waiting on build

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/mybinder.org-deploy#2870]
@arnim contacted me because GESIS server has a large (>100) number of requests waiting on build step as indicated in Graphana

![Screenshot 2023-12-22 at 20-40-19 View panel - 1  Overview - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/46a0ede4-741c-4e35-9cd8-3592e88fac22)

Screenshot source: https://grafana.mybinder.org/d/3SpLQinmk/1-overview?orgId=1&var-cluster=000000002&from=1700682034622&to=1703274034623&viewPanel=34

A similar large (>200) number of requests waiting on build step is observed on OVH:

![Screenshot 2023-12-22 at 20-43-14 View panel - 1  Overview - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/46d65794-a822-4d5c-a2f1-dbf53d92f792)

Screenshot source: https://grafana.mybinder.org/d/3SpLQinmk/1-overview?orgId=1&var-cluster=000000004&from=1700682278831&to=1703274278832&viewPanel=34

And Curvenote:

![Screenshot 2023-12-22 at 20-45-02 View panel - 1  Overview - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/2b3d5e43-997c-4a4b-a769-f3e9270e22fc)

Screenshot source: https://grafana.mybinder.org/d/3SpLQinmk/1-overview?orgId=1&var-cluster=b67087d4-25bd-41aa-8ecd-940252a85e24&from=1700682335597&to=1703274335599&viewPanel=34

I suspect that https://github.com/jupyterhub/mybinder.org-deploy/pull/2857 introduced some change that is causing this.

**Comment by rgaiacs** [comment]
The builds counter was reset https://grafana.mybinder.org/d/3SpLQinmk/1-overview?orgId=1&var-cluster=000000004&from=1709017624637&to=1709622424638&viewPanel=34

![Screenshot 2024-03-05 at 08-06-04 1  Overview - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/f40e7d0a-5a16-4cc3-a9d6-27b13cb217c8)

Maybe related to https://github.com/jupyterhub/mybinder.org-deploy/pull/2937

**Comment by manics** [comment]
Or it might be https://github.com/jupyterhub/mybinder.org-deploy/pull/2938 which includes https://github.com/jupyterhub/binderhub/pull/1828
Can you check the dind logs for `Removing incorrect socket directory {{ $hostSocketPath }}`?

**Comment by rgaiacs** [comment]
This is old and I cannot look at the logs.
