### ISSUE TITLE
Sort-term strategy to improve the launch success rate 

### ISSUE THREAD

**Issue by arnim** [jupyterhub/mybinder.org-deploy#2890]
Hi 👋 

Background: Just had a sort discussion with Markus Stocker from the [ORKG](https://orkg.org) team. They are doing (meta-) data management for various research output artefacts and are evaluating ways to make some of them online reproducible & executable. For this they have a binder specific example.  https://orkg.org/comparison/R44930/ > "Visualizations with Jupyter"

In testing their example we produced many launch failures before successfully launching it. The example redirects to OVH. 

In general OVH and GESIS are currently configured with the same weights of 100. I would naively assume that everything else being equal we would at average see similar numbers for launches /  running pods. OVH, however, reports most of the time fare fewer running pods than GESIS. Is it possible that the difference are launch failures?

Would it help if we try to reduce slightly the relative weight of OVH?  OVH is currently configured with a weight of 100.

What do you think?

CC @rgaiacs

**Comment by manics** [comment]
Changing the weight to bias launches towards Gesis sounds fine to me! We need to spend some time figuring out where the problems are occurring on OVH

**Comment by arnim** [comment]
Jup, **Sort-term strategy** only :)

I would also ask @rgaiacs if he feels comfortable with it.

**Comment by rgaiacs** [comment]
@rgaiacs works for me.

**Comment by arnim** [comment]
Should I open a pull request to set the OVH2 [weight](https://github.com/jupyterhub/mybinder.org-deploy/blob/c4efa315da72a36b886aec7c435d159714287d31/config/prod.yaml#L239) to 60, so we can test if this approach is effective?

**Comment by manics** [comment]
Sounds fine to me!

**Comment by rgaiacs** [comment]
This has been addressed in https://github.com/arnim/mybinder.org-deploy/commit/64330034571e420c9f2f47916333161d8df16770.
