### ISSUE TITLE
Upcoming workshop maximum concurent users limit.

### ISSUE THREAD

**Issue by STReichert** [jupyterhub/mybinder.org-deploy#2906]
Hi, I am running a data science workshop for a variety of transportation professionals on March 11th using this repository that I am currently developing: https://mybinder.org/v2/git/https%3A%2F%2Fbitbucket.org%2Fhigh-street%2Fdsps24/main 

We anticipate having as many as 200 users join us in a combination of in person and virtual attendance while we cover an intro to python syntax, data wrangling and machine learning algorithms. Would it be possible for you to increase the concurrent user limits to 200 people on our repository for that day so that we can better serve our audience?

Thank you in advance for your help!

Best,
Seth

**Comment by STReichert** [comment]
Hi @rgaiacs, thanks for getting back to me! I hadn't heard of JupyterLite, it seems very interesting. It doesn't seem like it will quite work for our current project since we are hosting our project on BitBucket rather than GitHub, but I'll keep it in mind for the future. 

We can keep the interactive component of our workshop to the current limit of 100 concurrent users with those who may be there over the limit "auditing" by just following along. Just so I know, what is the expected behavior for Binder as we reach the threshold? Will the 101st person to attempt accessing the repository receive an error or a stalled loading page of some kind? Or will person no. 1 have their session ended? I am just trying to gauge how attentive I should be as a gatekeeper to which of our participants are able to follow the workshop in Binder vs those that won't be able to so everyone has the best possible experience.

**Comment by rgaiacs** [comment]
> Or will person no. 1 have their session ended?

We only end a session if it becomes idle or maximum time allowed is reach.

**Comment by STReichert** [comment]
Ok! Thank's for the help!
