### ISSUE TITLE
How to remove a node from our cluster

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#292]
Some instructions on how to delete a node from our cluster: http://pminkov.github.io/blog/removing-a-node-from-a-kubernetes-cluster-on-gke-google-container-engine.html

Before you follow that blog post you should first cordon off the node `kubectl cordon gke-prod-a-ssd-pool-972e4826-w742`, wait for there to be no `jupyter-*` pods on it anymore `kubectl get pods --namespace=prod -o wide | grep "gke-prod-a-ssd-pool-972e4826-w742$" | grep "^jupyter-"`, and then drain the node `kubectl drain gke-prod-a-ssd-pool-972e4826-w742`.

Should this go in WISDOM or the docs/?

**Comment by choldgraf** [comment]
+1 to a "how do I" section of the sre guide

**Comment by betatim** [comment]
The `kubectl drain` command will most likely give you an error about certain pods running on the node that prevent it from draining the node. It is Ok (and expected) to use the suggested flags to force the draining: `kubectl drain gke-prod-a-ssd-pool-972e4826-tl75 --ignore-daemonsets --force --delete-local-data`

**Comment by choldgraf** [comment]
what if we changed http://mybinder-sre.readthedocs.io/en/staging/command_snippets.html so that instead of "command snippets" it was called "how do I..." and we could include this information in there?
