### ISSUE TITLE
GESIS was "down" from 10:40 UTC+1 until 13:20 UTC+1

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/mybinder.org-deploy#2922]
@arnim pointed this to me.

[![Screenshot 2024-02-06 at 19-38-18 1  Overview - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/6212d7ba-1df9-4d82-8677-673f62f7234f)](https://grafana.mybinder.org/d/3SpLQinmk/1-overview?orgId=1&var-cluster=000000004&from=1707195600000&to=1707231600000&viewPanel=31)

The drop in the number of users

[![Screenshot 2024-02-06 at 19-47-39 Node Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/18693622-1203-4e39-97fe-9b06762df60b)](https://grafana.mybinder.org/d/nDQPwi7mk/node-activity?orgId=1&var-cluster=000000002&from=1707195600000&to=1707231600000&viewPanel=26)

correspond to a increase in the number of builds

[![Screenshot 2024-02-06 at 19-47-55 Node Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/ef3bdf6d-14fc-44eb-8fce-e9dc52160fa7)](https://grafana.mybinder.org/d/nDQPwi7mk/node-activity?orgId=1&var-cluster=000000002&from=1707195600000&to=1707231600000&viewPanel=44)

The increase in the number of builds was drive by https://github.com/hughshanahan/CS2900-Lab-1

[![Screenshot 2024-02-06 at 19-48-44 Pod Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/50b41e82-1b7d-446f-9c8d-8852244c75b0)](https://github.com/hughshanahan/CS2900-Lab-1)

The server is running OK now.

[![Screenshot 2024-02-06 at 19-38-57 1  Overview - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/a486310f-5123-4623-8a94-15002176f335)](https://grafana.mybinder.org/d/3SpLQinmk/1-overview?orgId=1&var-cluster=000000004&from=1707233997135&to=1707244797136&viewPanel=31)

**Comment by manics** [comment]
I thought BinderHub only launched one build pod per (repo, git-commit) combination.... Is it actually one build pod per (repo, git-commit, browser session)?

**Comment by rgaiacs** [comment]
> I thought BinderHub only launched one build pod per (repo, git-commit) combination

This is my understanding.

I will have to dig the logs to compare the Git commit ID used in the build requests.

**Comment by rgaiacs** [comment]
This issue is too old for me to be able to look into the logs.
