### ISSUE TITLE
Point letsencrypt account to use the google groups email

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/mybinder.org-deploy#293]
Now that we have a google groups email, we should use it as the point-of-contact for various automated services, emails, etc:

binder-team@googlegroups.com

We should confirm that incoming emails from non-members work as well

**Comment by yuvipanda** [comment]
This needs to be slightly carefully done so we don't lose our certificates for any intermediate time period!

**Comment by choldgraf** [comment]
I see that we still seem to be [using yuvi's email for kube-lego](https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/values.yaml#L159) which tells this is still not resolved. Is that correct?

**Comment by betatim** [comment]
I think this is done.
