### ISSUE TITLE
Subscribe binder-team shared address to ubuntu-announce mailing list

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#296]
https://lists.ubuntu.com/mailman/listinfo/ubuntu-announce is a very low traffic mailing list that emails about upcoming support changes and new releases - an email every few months. We should subscribe the shared address to this so we can be aware of upcoming deprecations / major security issues.

**Comment by choldgraf** [comment]
+1

**Comment by choldgraf** [comment]
I've just added binderhub-dev@googlegroups.com to this list
