### ISSUE TITLE
Service (at GESIS?) potentially down

### ISSUE THREAD

**Issue by arnim** [jupyterhub/mybinder.org-deploy#2961]
Service (at GESIS?) potentially down

<img width="1013" alt="image" src="https://github.com/jupyterhub/mybinder.org-deploy/assets/265541/2b7a47c7-2eac-42d2-befd-22973d4cb2d1">

https://grafana.mybinder.org/d/3SpLQinmk/1-overview?orgId=1&viewPanel=31&from=1712943455495&to=1712960802330

Potential deployment issue at GESIS after [c362539](https://github.com/jupyterhub/mybinder.org-deploy/commit/c362539e0cbac17a626fb511bc31ef2e91c730dd) 

CC  @rgaiacs  @manics

**Comment by arnim** [comment]
Jup, it's us 
https://grafana.mybinder.org/d/3SpLQinmk/1-overview?orgId=1&from=1712945583035&to=1712959506028&viewPanel=36

**Comment by rgaiacs** [comment]
I re-run the deployment. It should be fixed. https://grafana.mybinder.org/d/3SpLQinmk/1-overview?orgId=1&from=1713010615449&to=1713011515449&viewPanel=36

![Screenshot from 2024-04-13 14-31-40](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/5741940d-56ee-4008-a4fc-dc377a21342b)

My understanding is that our deployment script does not like when there is multiple merge request at the "same time" like

![Screenshot from 2024-04-13 14-34-10](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/2ed608b3-ac04-4c51-9a8a-d4162d2facd3)

**Comment by manics** [comment]
GitHub lets you limit concurrent workflows
https://docs.github.com/en/actions/using-jobs/using-concurrency
Do you have the equivalent in GitLab?

**Comment by rgaiacs** [comment]
>  Do you have the equivalent in GitLab?

Yes. I will look into https://docs.gitlab.com/ee/ci/yaml/#resource_group

**Comment by rgaiacs** [comment]
https://github.com/gesiscss/orc2/commit/e8a2a0628383d146cadb4b8acdf4d8154512531d should make updates more stable when multiple PR are merged in a short time.
