### ISSUE TITLE
Large number of pending pods for GESIS server

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/mybinder.org-deploy#2995]
This started around 8:00 am CEST of 5 June 2024.

# OVH

[
![Screenshot 2024-06-05 at 09-31-42 Pod Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/c35f6f7b-0701-451d-bf31-a20bae267fe2)
](https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&var-cluster=000000004&from=1717562036610&to=1717572836610&refresh=2h&viewPanel=3)

# GESIS

[
![Screenshot 2024-06-05 at 09-31-11 Pod Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/5c14f09b-d9d7-458f-a980-f5e9cb5d67e9)
](https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&var-cluster=000000002&from=1717562005614&to=1717572805614&refresh=2h&viewPanel=3)

`kubectl get -n gesis pods --sort-by='{.metadata.creationTimestamp}' | grep Terminating` produces

```
jupyter-deepchecks-2ddeepchecks-2dgeaqun29                       0/1     Terminating       0               38m
jupyter-psuastro528-2dtltdemo-2dstart-2dr2ww36mg                 0/1     Terminating       0               37m
jupyter-ohbm-2dcomcom-2d202-2dommunity-2dsurvey-2d9l4zs8t3       0/1     Terminating       0               37m
jupyter-intermine-2dinter-2d-2dws-2dpython-2ddocs-2dsngwm720     0/1     Terminating       0               37m
jupyter-deltares-2dra2ce-2df4pmreer                              0/1     Terminating       0               37m
jupyter-china-2dluoyaxiong-2dkeshihua50-2de8ah20zg               0/1     Terminating       0               36m
jupyter-py4basics-2dpy4basics-2egithub-2eio-2d16sqkroj           0/1     Terminating       0               36m
jupyter-wjbmattingly-2dpython-5ffor-5fdh-2d7yufgbtt              0/1     Terminating       0               34m
jupyter-defeo-2dcimpa-2drabat-2dp85f236l                         0/1     Terminating       0               34m
jupyter-deltares-2dra2ce-2de71ih71s                              0/1     Terminating       0               34m
jupyter-codingalzi-2dalgopy-2dke3xmcz4                           0/1     Terminating       0               34m
jupyter-ianhi-2dmpl-2dinteractions-2dktn2iy4l                    0/1     Terminating       0               32m
jupyter-apache-2dsedona-2di24qd44h                               0/1     Terminating       0               31m
jupyter-sbrg-2dssbio-2dhvfq3bjw                                  0/1     Terminating       0               30m
jupyter-jrzaurin-2dinfinitoml-2dq26uboq7                         0/1     Terminating       0               29m
jupyter-guiwitz-2dyrd2024-2da9qhs327                             0/1     Terminating       0               29m
jupyter-tadpoleloop-2didle-5fapocalypse-2dzr81a9ag               0/1     Terminating       0               28m
jupyter-trustimaging-2dstride-2dbghm32h5                         0/1     Terminating       0               28m
jupyter-tadpoleloop-2didle-5fapocalypse-2d9nzc4g29               0/1     Terminating       0               27m
jupyter-tadpoleloop-2didle-5fapocalypse-2dyw17cs7c               0/1     Terminating       0               27m
jupyter-guiwitz-2dyrd2024-2d608uvoqc                             0/1     Terminating       0               27m
jupyter-gbrunkhorst-2dwebsite-2d42o8wdbv                         0/1     Terminating       0               27m
jupyter-trustimaging-2dstride-2da60i1kvc                         0/1     Terminating       0               27m
jupyter-deltares-2dra2ce-2djifu02j0                              0/1     Terminating       0               27m
jupyter-deltares-2dra2ce-2dest1glcr                              0/1     Terminating       0               27m
jupyter-joegreiner-2dbind-2danalysissandbox-2dtwk8wst9           0/1     Terminating       0               26m
jupyter-joegreiner-2dbind-2danalysissandbox-2dtfi260rg           0/1     Terminating       0               25m
jupyter-tadpoleloop-2didle-5fapocalypse-2dc1lal175               0/1     Terminating       0               25m
jupyter-guiwitz-2dyrd2024-2dm6xnrr63                             0/1     Terminating       0               25m
jupyter-tadpoleloop-2didle-5fapocalypse-2dmhnyqouy               0/1     Terminating       0               25m
jupyter-apache-2dsedona-2dm6ix15ks                               0/1     Terminating       0               25m
jupyter-frederic-2djunier-2dpremiere-2d9vnocr4c                  0/1     Terminating       0               22m
jupyter-gesiscss-2dorc2-2dtest-2dbuild-2do0cu52nn                0/1     Terminating       0               22m
jupyter-saphety-2ddevelopers-2dapi-2dnotebooks-2dp7b7sv02        0/1     Terminating       0               19m
jupyter-mdtanker-2dinvert4geom-2dkr1uwerf                        0/1     Terminating       0               15m
jupyter-guiwitz-2dyrd2024-2drrt8j13z                             0/1     Terminating       0               15m
jupyter-joegreiner-2dbind-2danalysissandbox-2dwf3qn2vo           0/1     Terminating       0               15m
jupyter-ploixs-2denergycommunitymodel-2d4oq74dkr                 0/1     Terminating       0               15m
jupyter-nelsonfrz-2dgauss-2dalgorithm-2dp43r3p5b                 0/1     Terminating       0               15m
jupyter-lucasjamar-2dpandas-2dor-2djfp3g4py                      0/1     Terminating       0               14m
jupyter-lucasjamar-2dpandas-2dor-2dvernw7nz                      0/1     Terminating       0               13m
jupyter-lucasjamar-2dpandas-2dor-2dimh47u9f                      0/1     Terminating       0               12m
jupyter-dynamicslab-2dpysindy-2dg5pje18e                         0/1     Terminating       0               12m
jupyter-gesiscss-2dorc2-2dtest-2dbuild-2dkvt8gbxl                0/1     Terminating       0               12m
jupyter-meg-2dsimula-2din-2ds-2dbrain-2dtransport-2dhrdln0yz     0/1     Terminating       0               12m
jupyter-harpaf13-2ddata-2ecopper-2dphosphides-2driehw043         0/1     Terminating       0               11m
jupyter-apache-2dspark-2d0rjq4kie                                0/1     Terminating       0               10m
jupyter-meg-2dsimula-2din-2ds-2dbrain-2dtransport-2d9aztyszv     0/1     Terminating       0               9m11s
jupyter-anonymous-2d4383682-2d6fqnuwd9                           0/1     Terminating       0               8m33s
jupyter-theinze-2dmachinelearningdemo-2dftg5cews                 0/1     Terminating       0               7m5s
jupyter-meg-2dsimula-2din-2ds-2dbrain-2dtransport-2dtactif8v     0/1     Terminating       0               7m1s
jupyter-release-2dcandidate-2dlunazodiaco-2d7yl93v78             0/1     Terminating       0               5m58s
jupyter-meg-2dsimula-2din-2ds-2dbrain-2dtransport-2dvf6jyalm     0/1     Terminating       0               5m18s
jupyter-theinze-2dmachinelearningdemo-2d3b6168kp                 0/1     Terminating       0               5m18s
jupyter-joegreiner-2dbind-2danalysissandbox-2d9t3u66oz           0/1     Terminating       0               5m16s
jupyter-ploixs-2denergycommunitymodel-2db0unxfj4                 0/1     Terminating       0               5m11s
jupyter-bogdanhel-2dqpl-2dqi-2dsdk-2d3e3i3oqp                    0/1     Terminating       0               5m5s
```

This is because GESIS server is not able to download the Docker images fast enough.

[
![Screenshot 2024-06-05 at 10-05-25 Node Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/f1cf356b-9842-4529-b2b8-abd831269d3a)
](https://grafana.mybinder.org/d/nDQPwi7mk/node-activity?orgId=1&var-cluster=000000002&from=1717563988978&to=1717574788978&viewPanel=28)

# CurveNote

Not effected yet.

[![Screenshot 2024-06-05 at 09-34-42 Pod Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/4fe7662e-a24d-4f14-9fcb-38f6f01304c5)](https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&var-cluster=b67087d4-25bd-41aa-8ecd-940252a85e24&from=1717562070397&to=1717572870397&refresh=2h&viewPanel=3)

**Comment by rgaiacs** [comment]
@arnim my feeling says that something is different from after the machine reboot. But I can't see a correlation. 

[
![Screenshot 2024-06-06 at 09-44-18 View panel - Pod Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/c376a186-d245-425b-ac0d-8e963bb5b373)
](https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&var-cluster=000000002&from=1717486803644&to=1717659603644&refresh=2h&viewPanel=3)

[
![Screenshot 2024-06-06 at 09-46-24 View panel - Node Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/56f74dbf-153b-4b00-a716-b8f1fd6c142b)
](https://grafana.mybinder.org/d/nDQPwi7mk/node-activity?orgId=1&var-cluster=000000002&from=1717487161963&to=1717659961963&viewPanel=36)

[
![Screenshot 2024-06-06 at 09-48-08 View panel - Node Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/e970bf86-e8e9-4a36-8a39-97f3906db274)
](https://grafana.mybinder.org/d/nDQPwi7mk/node-activity?orgId=1&var-cluster=000000002&from=1717487264957&to=1717660064957&viewPanel=29)

We clean the image cache a few times but only on some we have a spike on pull.

**Comment by rgaiacs** [comment]
cc @arnim 

The number of pending pods at GESIS server reduced. In the last 24 hours, we had

[![Screenshot 2024-06-07 at 08-35-09 View panel - Pod Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/34ac2c38-dd33-4fbc-be35-ba21c45c8a78)](https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&var-cluster=000000002&from=1717655678346&to=1717742078346&refresh=2h&viewPanel=3)

My impression is that the pending pods are waiting for a image to be available because the image needs to be build on our server, pushed to Docker Hub and downloaded again to our server.

The peak of pending pods has a time correlation with the peak of build pods.

[![Screenshot 2024-06-07 at 08-35-18 View panel - Pod Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/a3cb1edc-efe3-4a91-b723-20937c84af21)](https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&var-cluster=000000002&from=1717655698845&to=1717742098845&refresh=2h&viewPanel=4)

**Comment by manics** [comment]
Do you think we need to add an additional limit to BinderHub for the number of pending spawns, to prevent too many pods being created or queued up?

**Comment by rgaiacs** [comment]
> Do you think we need to add an additional limit to BinderHub for the number of pending spawns, to prevent too many pods being created or queued up?

My hypothesis is that BinderHub receives a launch request and allocates a new Kubernetes pod for the launch. Because the image required for the Kubernetes pod does not exists yet, the pod goes into pending mode. BinderHub adds a building request to the queue. During some periods, the number of new image build is larger than GESIS server capacity and the pending pods start to accumulate.

[![Screenshot 2024-06-07 at 15-56-58 Pod Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/14a5029f-8b09-44e9-bf39-80910a36f055)](https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&var-cluster=000000002&from=1717682690832&to=1717769090832&refresh=2h&viewPanel=5)
 
[![Screenshot 2024-06-07 at 15-57-07 Pod Activity - Dashboards - Grafana](https://github.com/jupyterhub/mybinder.org-deploy/assets/1506457/26557d3b-f6b1-4391-92e8-439d9190c71a)](https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&var-cluster=000000002&from=1717682718824&to=1717769118824&refresh=2h&viewPanel=4)

**Comment by manics** [comment]
Is a particular spike of pods related to the same repository?

Assuming your prometheus labels are the same as on Curvenote try this prometheus query for a time window around the spike: `sum(label_replace(kube_pod_status_phase{phase="Pending",pod=~"jupyter-.*"}, "repo", "$1", "pod", "jupyter-(.+)-[^-]+")) by (repo)`
E.g. https://prometheus.binder.curvenote.dev/graph?g0.expr=sum(label_replace(kube_pod_status_phase%7Bphase%3D%22Pending%22%2Cpod%3D~%22jupyter-.*%22%7D%2C%20%22repo%22%2C%20%22%241%22%2C%20%22pod%22%2C%20%22jupyter-(.%2B)-%5B%5E-%5D%2B%22))%20by%20(repo)&g0.tab=0&g0.display_mode=lines&g0.show_exemplars=0&g0.range_input=30m&g0.end_input=2024-08-01%2010%3A30%3A00&g0.moment_input=2024-08-01%2010%3A30%3A00

**Comment by rgaiacs** [comment]
Thanks @manics.

> Is a particular spike of pods related to the same repository?

Yes, there is.

![Screenshot 2024-08-01 at 14-57-15 Prometheus Time Serie](https://github.com/user-attachments/assets/84c21a37-9f44-4000-969d-893a85aa5c67)

A big number of the pending pods were the same repository. My assumption is that someone is giving a lecture / course. 10+ learners access mybinder.org at the same time. Because the server does not have the Docker image cached, all 10+ users are on the pending status until the Docker image is downloaded.

I'm closing this as "won't fix".

cc @arnim

**Comment by rgaiacs** [comment]
@arnim This is my current understanding of the problem:

1. User visits https://mybinder.org/ and requests a launch
2. mybinder.org assigns the request to GESIS server
3. GESIS server allocates a kubernetes pod to fulfil the request
4. Kubernetes waits for image to be available to pod
5. BinderHub waiting times out. BinderHub sends a request to terminate the pod to Kubernetes.
6. Kubernetes can only kill the pod when it is running but the pod can only run when the image is available. Kubernetes goes into a scenario where it is waiting a pod to start only to be killed.

The short video highlights one pod in this scenario described above: https://github.com/user-attachments/assets/131cda9f-c9c6-4195-b219-0d7a48e217ff

**Comment by rgaiacs** [comment]
OVH and GESIS is observing a large number of pending pods. Curvenote looks OK.

# OVH

[![Screenshot 2024-08-07 at 16-59-26 Pod Activity - Dashbo](https://github.com/user-attachments/assets/8f954c8b-f5c5-47d8-9b39-0e33b9188755)](https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&var-cluster=000000004&from=1721599200000&to=1723042773559&viewPanel=3)


# GESIS

[![Screenshot 2024-08-07 at 17-01-28 Pod Activity - Dashbo](https://github.com/user-attachments/assets/2518beae-8487-4f81-a5b9-8d9f5f5bc1e4)](https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&var-cluster=000000002&from=1721599200000&to=1723042892401&viewPanel=3)

It is getting worse and worse.
# Curvenote

[![Screenshot 2024-08-07 at 17-00-21 Pod Activity - Dashbo](https://github.com/user-attachments/assets/298eb851-5e63-4118-beb9-9fd89395f0b9)](https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&var-cluster=b67087d4-25bd-41aa-8ecd-940252a85e24&from=1721599200000&to=1723042827597&viewPanel=3)

**Comment by rgaiacs** [comment]
I'm closing this in favour of https://github.com/jupyterhub/mybinder.org-deploy/issues/3056.
