### ISSUE TITLE
GESIS GitLab is not working as expected

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/mybinder.org-deploy#3041]
GESIS IT updated GitLab yesterday. GitLab is not working as expected. For example, I can't merge branches. GESIS IT was already informed of the problem. @arnim and I asked for IT to prioritize the resolution of it.

@manics can you hold merging any pull request that would change the binderhub version for the next 24 hours until we hear back from GESIS IT? Thanks!

**Comment by rgaiacs** [comment]
Thanks @manics for the understanding.

I'm in contact with GESIS IT and they are looking into the problem.

Yesterday, I noticed that our GitLab instance is also not starting CI jobs trigger by push to the main branch.

![Screenshot 2024-07-25 at 11-40-58 Pipelines · integrate](https://github.com/user-attachments/assets/dd1d8135-9fe3-4f92-ac08-efb4fabeccdc)

Because of this, even if our bot is able to merge changes to binderhub version, the Kubernetes server will not be updated.

Unfortunately, this might only be fixed next week. 😢 

cc @arnim

**Comment by manics** [comment]
Don't worry, thanks for the update!

**Comment by rgaiacs** [comment]
This has been resolved by GESIS IT around 16:30 CEST of 25 July 2024.
