### ISSUE TITLE
Latest Cryptnono chart is incompatible with OVH

### ISSUE THREAD

**Issue by manics** [jupyterhub/mybinder.org-deploy#3053]
The latest Cryptnono chart fails on OVH due to https://github.com/cryptnono/cryptnono/pull/38 requiring kernel 5.16+

OVH nodes have `5.15.0-107-generic`

Original PR https://github.com/jupyterhub/mybinder.org-deploy/pull/3051,  reverted in https://github.com/jupyterhub/mybinder.org-deploy/pull/3052

FYI @yuvipanda

**Comment by manics** [comment]
https://github.com/cryptnono/cryptnono/pull/39 failed to deploy, so I had to revert it:
https://github.com/jupyterhub/mybinder.org-deploy/pull/3110

**Comment by yuvipanda** [comment]
:( do you have logs on why?

**Comment by manics** [comment]
It's working 😄
