### ISSUE TITLE
Agreement with Anaconda

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/mybinder.org-deploy#3068]
From https://prefix.dev/blog/towards_a_vendor_lock_in_free_conda_experience

> A recently published [article](https://www.theregister.com/2024/08/08/anaconda_puts_the_squeeze_on) by The Register re-ignited a lot of concern amongst conda users. The article mentions that Anaconda is contacting some instances that are making use of the [“defaults” Anaconda Distribution channels](https://docs.anaconda.com/working-with-conda/reference/default-repositories/) and are requesting payment. This pertains to their terms of service change in [2020](https://www.anaconda.com/blog/sustaining-our-stewardship-of-the-open-source-data-science-community). In turn this has led to renewed discussion on [X](https://x.com/choldgraf/status/1821853119824716008), [reddit](https://www.reddit.com/r/bioinformatics/comments/1emekxo/anaconda_licensing_terms_and_reproducible_science/) and other social media that users may have to pay, or might have to pay in the future for access to packages

Does mybinder.org have an agreement with Anaconda?

@arnim and I want to know to provide information to GESIS's legal team.

In the German RSE list, Alex said

> There was a program for research institute where you write a 2 page summary with some use cases which Anaconda can publish on their blog, kind of advertisement, which grants you some licenses and would have solved the problem. However, we were not allowed to do that because there were some tax relevant legal issues (key word "Tauschgeschäft").

@arnim I don't know how the above tax relevant legal issue applies to GESIS regarding GESIS relationship with mybinder.org.

**Comment by minrk** [comment]
mybinder.org uses conda-forge, not Anaconda. The Anaconda commercial terms do not apply to anything we do, only the `defaults` channel, which we don't use. https://github.com/jupyterhub/repo2docker/pull/1365 should make sure no defaults packages get installed by accident.

**Comment by rgaiacs** [comment]
https://github.com/jupyterhub/repo2docker/pull/1365 has been merged. I'm closing this.
