### ISSUE TITLE
Give @rgaiacs write permissions on this repo

### ISSUE THREAD

**Issue by manics** [jupyterhub/mybinder.org-deploy#3082]
This is to document that I've upgraded @rgaiacs's permissions on this repo from triage to write (so PRs can be merged)

**Comment by rgaiacs** [comment]
Thanks @manics!

I believe that I had merge rights before, see https://github.com/jupyterhub/mybinder.org-deploy/pull/3076#issuecomment-2311791088.

![Screenshot 2024-08-30 at 07-52-22 Update donate button by manics · Pull Request #3076 · jupyterhub_mybinder org-deploy](https://github.com/user-attachments/assets/210e567a-e7d6-491a-b72c-30be2dc18b95)
