### ISSUE TITLE
500: Internal Server Error on mybinder.org

### ISSUE THREAD

**Issue by arnim** [jupyterhub/mybinder.org-deploy#3099]
<img width="728" alt="image" src="https://github.com/user-attachments/assets/24375fec-105e-4bf9-b146-62a0c719ca00">

https://downforeveryoneorjustme.com/mybinder.org

**Comment by arnim** [comment]
It's coming back, but had a similar message yesterday.

**Comment by rgaiacs** [comment]
This has also been reported on the Jupyter Discourse Forum yesterday: https://discourse.jupyter.org/t/500-server-error-on-mybinder-org

**Comment by minrk** [comment]
Seems to be a health problem in the curvenote deployment

**Comment by manics** [comment]
Both Curvenote nodes are out of disk space. There's an AMI update available anyway so I'll replace them.

**Comment by manics** [comment]
Should be working now.
