### ISSUE TITLE
BANNED: ds100 repos

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/mybinder.org-deploy#357]
In https://github.com/jupyterhub/mybinder.org-deploy/pull/329 we banned the following repos:

* `github.com/ds-100/textbook.*`
* `github.com/samlau95/nbinteract-image.*`

We should unban them when we believe that the issue is resolved.

**Comment by SamLau95** [comment]
Related issue: https://github.com/SamLau95/nbinteract/issues/34

**Comment by betatim** [comment]
Ban has been lifted a while back https://github.com/jupyterhub/mybinder.org-deploy/blob/b7d820677c8d1f18680907ae20e86dfd85d9ee1e/mybinder/values.yaml#L5-L7
