### ISSUE TITLE
Secure our Kubernetes Clusters

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#36]
We're running a public service allowing arbitrary code execution, and so have responsibilities on how secure we have to be. Here's a baseline on getting started:

- [x] 1. Make sure we have kubernetes [RBAC](https://kubernetes.io/docs/admin/authorization/rbac) enabled, with hub & binder allowed only the permissions they need & nothing more.
- [ ] 2. Enable Kubernetes [Network Policy](https://kubernetes.io/docs/concepts/services-networking/network-policies/), restricting user pods' network access. 
    1. Only the hub pod can talk to the proxy's API port
    2. The user pods can only talk to the hub & the proxies inside the cluster (so not other services in the kubernetes cluster nor other user pods)
    3. (When GKE supports Egress network policy) we should lock down the network ports pods can connect to. At a minimum we should block outgoing traffic on port 25 (to prevent spamming). We might also consider making a port whitelist instead.
- [ ] 3. Run [go-auditd](https://github.com/slackhq/go-audit) on all our nodes, for reasons outlined in this excellent [blog post](https://slack.engineering/syscall-auditing-at-scale-e6a3ca8ac1b8) from Slack's security team.
- [ ] 4. Make sure our users can not escalate to root by setting appropriate parameters in the pod spec.
- [x] 5. Make sure users can never access the kubernetes API itself, since this allows for a lot of escalation points.
- [x] 6. Make sure useres can not access the [GCE Metadata Service](https://cloud.google.com/compute/docs/storing-retrieving-metadata) from inside the containers. This might already be the case, but we should verify.) (#174)

Eventually, I'd love for us to spend some money getting JupyterHub & BinderHub security audited by an actual security firm!

**Comment by yuvipanda** [comment]
I've already done 1 today, and we have strict RBAC enabled!

**Comment by minrk** [comment]
FOR 2.iii [according to docs](https://cloud.google.com/compute/docs/networks-and-firewalls), Google already blocks outgoing 25 (and other spam avenues), which is nice.

**Comment by yuvipanda** [comment]
I just did #6 with #174

**Comment by yuvipanda** [comment]
I ticked the boxes we have done.

**Comment by consideRatio** [comment]
Besides doing go-auditd on the nodes, I think we are done with this issue. Overall this is upstream work in z2jh and binderhub repos in general.

I note that the binderhub Helm chart doesn't have network policies defined for its pods, but I'll go ahead and close this anyhow.

**Comment by yuvipanda** [comment]
@consideRatio  should we open another issue for network policies in binderhub?

**Comment by consideRatio** [comment]
@yuvipanda I found https://github.com/jupyterhub/binderhub/issues/362
