### ISSUE TITLE
Histogram plugin on grafana returns 404

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/mybinder.org-deploy#363]
When I try to add a histogram to grafana, I get a 404:

![image](https://user-images.githubusercontent.com/1839645/36136491-a1fa8f8a-1045-11e8-9060-01a0ff0598f3.png)

any idea what's up? @minrk I think you were the one that added this plugin

**Comment by choldgraf** [comment]
hmm, I tried SSH-ing into the grafana pod and uninstalling + re-installing that plugin, but when I tried to restart the grafana server with 

```
service grafana-server restart
```


I got 

```
root@prod-grafana-5f689b4fd-jzkw7:/# service grafana-server restart
[ ok ] Stopping Grafana Server: Grafana Server is not running but pid file exists, cleaning up.
[FAIL] Starting Grafana Server: failed!
```

that said...`grafana.mybinder.org` still seems to be up...so I'm not really sure what's going on

**Comment by minrk** [comment]
huh, I didn't notice that! Maybe we should remove the histogram plugin from this chart, then.

**Comment by choldgraf** [comment]
I played around with it and it's a bit wonky (the x-axis for some reason has much less fine-grained control over bucket sizes than the y-axis does), but you can also achieve a similar kind of effect with the heatmaps (which is basically just a histogram over time)
