### ISSUE TITLE
Staging only deploy proposal

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#403]
I actually wrote up a really large proposal here that was somewhat complex on how to do staging-only deploys, but realized there's a much simpler way for most cases!

Use config/staging.yaml instead. This overrides values from mybinder/values.yaml, and can be harmlessly deployed to prod too. It also makes everything fairly explicit, and does not require complex deployment techniques.

The disadvantage of this is that we can not use this to do a staging-only deploy of any change to `requirements.yaml`, but I don't think we've had a need for that yet. When that happens, we can build that out.

**Comment by yuvipanda** [comment]
This is primarily in response to @willingc's comment in https://github.com/jupyterhub/mybinder.org-deploy/pull/367#issuecomment-365608992

But also because @choldgraf wants to do #373 just to staging

**Comment by choldgraf** [comment]
Hey all - we have this now: http://mybinder-sre.readthedocs.io/en/latest/deployment/how.html#deploying-to-only-staging so closing!
