### ISSUE TITLE
Document the cloud services we use in mybinder.org

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#417]
In running mybinder.org, we use many cloud services. We should document what these are, why we use them, and how we use them!

Current list is:

- [ ] Google Kubernetes Engine
- [ ] Google Container Registry
- [ ] StackDriver logging
- [ ] Google Network Load Balancer

This will also let us be explicit and clear about the cloud-specific things we are doing. None of these services are unique to Google, and we should continue to stay that way!

**Comment by willingc** [comment]
@yuvipanda If you can do this easier as handwritten versus typed, I would be happy to craft the text to go with it on Monday.

**Comment by yuvipanda** [comment]
@willingc Thank you for the generous offer! I generally prefer text however, so have made a PR #488.

@minrk  / @betatim I think either of you know more about the current state of stackdriver than I do, so I've left a stub in the PR around stackdriver. Hopefully one of you can help fill it up afterwards!
