### ISSUE TITLE
blank page on Firefox Klar

### ISSUE THREAD

**Issue by das-g** [jupyterhub/mybinder.org-deploy#426]
### To reproduce:

1. Launch Firefox Klar (a version of Firefox Focus for Germany, Austria and Switzerland, [available on F-Droid](https://f-droid.org/en/packages/org.mozilla.klar/))
2. In Klar, navigate to https://github.com/betatim/talk-swiss-python-summit-2018 (or to this issue)
3. Tap the [![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/betatim/talk-swiss-python-summit-2018/master) badge

#### Expected behavior

- The loading animation is shown
- After a while, you get redirected to a pod and see the jupyterhub tree view

#### Observed behavior

- The loading animation is shown ![screenshot_20180218-125457](https://user-images.githubusercontent.com/97746/36351505-8533e5a8-14ab-11e8-8f7c-ab40a73f412e.png)
- After a while, you get redirected to what appears to be a blank page ![screenshot_20180218-125509](https://user-images.githubusercontent.com/97746/36351506-85525790-14ab-11e8-9028-1c13a32fbfca.png)

**Comment by choldgraf** [comment]
hmmm - this one is going to be a little bit hard to debug, as we have limited resources to spot-check and debug outside of the major modern-day browsers (firefox and chrome...we only just recently added Microsoft Edge support, and still don't have IE support). @betatim did you have an idea for how to proceed on this one?

**Comment by betatim** [comment]
No idea, just thought we should create an issue so it doesn't get forgotten (and in the hopes that  someone who knows about privacy enhanced browsers could chime in with places to start looking).

It seems weird that it doesn't render anything :-/

**Comment by willingc** [comment]
This would be a great issue for a community member to try to run on Firefox Klar and report back. We would appreciate the help on this.

**Comment by yuvipanda** [comment]
Going to close this now. Do re-open if this is still a problem!

**Comment by das-g** [comment]
Sorry for not reporting back earlier.

This issue can remain closed: In Firefox Klar 6.1.1 (F-Droid build 22) it's currently working fine. :+1:

**Comment by yuvipanda** [comment]
Thanks for verifying, @das-g!
