### ISSUE TITLE
grafana has occasionally been serving default-404

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#429]
Noticed by @betatim ca. 2018-02-20T13:00Z

grafana.mybinder.org served the default-404 backend for a brief period (likely <5min). This suggests that the ingress controller didn't have a record that grafana.mybinder.org should be accepting routes. It is unclear what the cause is, and it resolved itself quickly. There was no deploy at the time.

I saw this yesterday as well, but it was shortly after a deploy so I assumed it had to do with the ingress controller reloading config after `helm upgrade`. That doesn't appear to have been the case this time, so it may have been a coincidence that it was shortly.

We should keep an eye on this if it recurs.

**Comment by willingc** [comment]
Grafana may need to be refreshed or cache cleared/refreshed in the browser to remove a stale 404

**Comment by minrk** [comment]
Checking the logs, we can see that [grafana is segfaulting](https://console.cloud.google.com/logs/viewer?project=binder-prod&minLogLevel=0&expandAll=false&timestamp=2018-02-22T11%3A25%3A45.000000000Z&dateRangeStart=2018-02-22T10%3A39%3A23.677Z&dateRangeEnd=2018-02-22T11%3A39%3A23.677Z&interval=PT1H&resource=container%2Fcluster_name%2Fprod-a&logName=projects%2Fbinder-prod%2Flogs%2Fgrafana&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.pod_id%3D%22prod-grafana-5f9999dc4f-n77vj%22%0Aresource.labels.zone%3D%22us-central1-a%22%0Aresource.labels.project_id%3D%22binder-prod%22%0Aresource.labels.cluster_name%3D%22prod-a%22%0Aresource.labels.container_name%3D%22grafana%22%0Aresource.labels.namespace_id%3D%22prod%22%0Aresource.labels.instance_id%3D%22210694033853395397%22%0Atimestamp%3D%222018-02-22T11%3A25%3A45.000000000Z%22%0AinsertId%3D%221od3ybg1fftndi%22) (link only works for access to cloud console). Excerpt:

```
E 2018-02-22 12:25:45.000 CET [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xecc172]
E 2018-02-22 12:25:45.000 CET fatal error: unexpected signal during runtime execution
```

**Comment by choldgraf** [comment]
Could this be related to the low memory limits in the Grafana pod that Yuvi
mentioned?

**Comment by yuvipanda** [comment]
I think this works fine now. Re-open if not!
