### ISSUE TITLE
Create a support cluster with debugging & deployment tooling

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#438]
Currently, tools critical to deploying changes are running in the same cluster they are deploying to. This includes at least Grafana, and possibly new tools being added (#425, etc).

These should be in a separate cluster that is in a different region than the one we run, to make sure they can stay up regardless of various problems we might be having.

**Comment by minrk** [comment]
Makes sense. Re: file layout, does this mean putting a `mybinder-support` directory with grafana, etc. next to `mybinder` with the Binder deployment itself?

**Comment by yuvipanda** [comment]
There are two options:

1. Have a top-level 'mybinder-support' or 'support' dir in this repo
2. Make a different repo that has just these.

I'm torn between preferring (1) for simplicity but (2) for full isolation, since it'll let us deploy to support code even in times when our primary deployment is fubar.

**Comment by choldgraf** [comment]
I'm happy with either of these options

**Comment by yuvipanda** [comment]
I think we decided to not have a separate cluster just for this.
