### ISSUE TITLE
Review stopped-binder error page

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#462]
We are now serving [this html](https://github.com/jupyterhub/mybinder.org-deploy/blob/055f218f7835b3f408521f9cf238612cade5ac3e/mybinder/templates/proxy-patches/configmap.yaml#L29) when a user tries to visit a stopped pod. It would be useful to get some review passes on the text there to best communicate to users what may have happened and what they can/should do next.

Cases include:

- their own binder stopped
  - due to an error
  - culled by idle culler
  - culled for max age
- they were given a link from someone copy/pasting from their browser address bar

You can test the current version of the page by visiting https://hub.mybinder.org/user/doesntexist

cc @willingc @choldgraf

**Comment by willingc** [comment]
Agreed! Thanks for the link @minrk.
