### ISSUE TITLE
Organize our dashboards

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#475]
Currently we have a 'main' dashboard that has too many things in it.

We should figure out some underyling principles for organizing dashboards, and split the dashboards we have across those.

**Comment by choldgraf** [comment]
a couple quick thoughts:

* I find it really useful to have things time-aligned vertically, so we can investigate interactions between metrics.
* To that extent, what if we cap the # columns to be 2 per page.
* It might be useful to *duplicate* particularly important metrics in each column, so it's easier to cross-ref with other plots
* Shall we organize dashboards by high-level topic (e.g. debugging, SLO, etc) or by infrastructure-level topic (e.g., kubernetes dashboard, pod statistics dashboard, etc)? I lean towards the former.
* Also we can always have a "sandbox" dashboard that is more "kitchen-sinky" and can be used to protoype new plots to add to the others

**Comment by betatim** [comment]
+1 on time alignment.

+1 for topic based dashboards. Maybe we can have a "normal" and "verbose" version of dashboards. The normal version would contain 6 (or so) graphs which are the most popular to look at, in verbose mode you get "all the plots".

(The components resource metrics dash has a lot of plots on it but it doesn't bother me, the ones I look at together are grouped so I just scroll there and ignore the rest, but the other plots are easy to find if I want to look at them. So if we can replicate what ever clever design thinking went into that dash... :) )

**Comment by yuvipanda** [comment]
+1 for topic based dashboards and normal/verbose versions too.

**Comment by yuvipanda** [comment]
@betatim yeah, the component resource metrics one was primarily designed with 'vertical alignment for graphs that might show correlations', which seems like a decent thing to design all dashboards around.

**Comment by choldgraf** [comment]
we've now got several more specific dashboards to make things easier to follow, I'm closing this! Feel free to reopen if need be.
