### ISSUE TITLE
Consider moving away from NGINX for ingress

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/mybinder.org-deploy#496]
We've had a few problems pop up on Binder because of the reliance on the relatively old tech of NGINX. This most recently manifested in Binder downtime because the NGINX pods froze up and stopped responding.

Is there another option that's a bit newer and can handle the more dynamic nature of our k8s clusters?

cc @yuvipanda who had some thoughts. Also please confirm this is the right repo for this :-)

From a previous thread:

> YP: This is only for the nginx-ingresses.
>
> I think we should consider https://github.com/containous/traefik. That
seems the most mature of the lot for now.

> CW: @jupyterhub/binder-team FYI. NGINX Ingress webinar on 2/28: https://www.nginx.com/resources/webinars/kubernetes-ingress-controller-getting-started/

closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/528

**Comment by willingc** [comment]
As an FYI for clarification, we use the [community maintained nginx ingress controller](https://github.com/kubernetes/ingress-nginx) not the two controllers maintained by Nginx.

**Comment by yuvipanda** [comment]
I think nginx-ingress has really rallied in the k8s community and is the default-good choice now. Let's stick to it.
