### ISSUE TITLE
Stop using omgwtf.in domains

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#5]
Currently we use that for a bunch of stuff, and we no longer need to.

1. beta hub should be hub.beta.mybinder.org
2. staging binder should be staging.mybinder.org
3. staging hub should be hub.staging.mybinder.org

**Comment by minrk** [comment]
We're waiting on nameserver updates for mybinder.org, then we can do this. What's the next step there?

**Comment by minrk** [comment]
I've updated the DNS on cloudflare to match the current values, so as soon as the nameservers are pointing to cloudflare we can update here.

**Comment by minrk** [comment]
If there's some holdup there, we can also use jovyan.org or jupyter.org domains for the temporary values, since we have access to those.

**Comment by minrk** [comment]
The mybinder.org DNS has disappeared from CloudFlare, so we'll apparently have to start that process again.

**Comment by yuvipanda** [comment]
Looks like the DNS is now with @choldgraf in his bluehost setup. I've asked him to make the A records we need.

**Comment by choldgraf** [comment]
Changes made!

**Comment by yuvipanda** [comment]
Staging is now https://staging.mybinder.org/!

**Comment by choldgraf** [comment]
nice!
--

**Comment by yuvipanda** [comment]
And beta hub is now at hub.beta.mybinder.org! 

Closing now.

**Comment by yuvipanda** [comment]
Also, RIP omgwtf.in. You were loved, at least by one person.

**Comment by choldgraf** [comment]
I loved it too!

**Comment by minrk** [comment]
@yuvipanda where's the DNS? It's not on CloudFlare anymore.

**Comment by minrk** [comment]
Blah, not reading back far enough. I see it now.

**Comment by choldgraf** [comment]
@yuvipanda @minrk do you guys think it's fine for us to document this stuff on the `mybinder.org-deploy` repo? We should have information about staging/prod/etc somewhere for our internal uses at least.

**Comment by choldgraf** [comment]
ah nvm, it looks like the readme already has some of this information in it. I think it's fine for now - maybe at some point we can take another pass through and clean things up but there are bigger fish to fry right now
