### ISSUE TITLE
deploys have become less reliable again

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#521]
A few recent deploys have started failing on Travis and needing relaunch to succeed. When we did the gke upgrade, a deploy took several attempts, perhaps due to the fact that all nodes were fresh, and thus there was lots of new image-pulling and all dind instances had an empty layer cache.

**Comment by choldgraf** [comment]
@minrk did we decide this was because of instability we need to fix, or just general travis timeout because of lots of k8s changes under the hood?

**Comment by yuvipanda** [comment]
I think this is old enough, and our deployment setup has changed enough that we can close this.
