### ISSUE TITLE
Reorganizing Grafana

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/mybinder.org-deploy#524]
I took a stab at reorganizing grafana a little bit - the "main" page was starting to really get bogged down, and also had a bit of "information overload" to it. So, I split it off into three dashboard:

1. Overview - this is meant to be a high-level "overview" of the cluster - it doesn't give node- or pod-specific metrics, and focuses on things like total memory, total number users, etc.
2. Network activity - this includes cluster-level and component-level metrics for network activity
3. Node activity - includes node-specific metrics that will hopefully make it easier to spot if a node is being wonky.

This was a first take but please feel free to make further edits!

**Comment by betatim** [comment]
If like me you are wondering: Where do I go to see the second and third dashboard? The "obvious" list of dashboards you see is the list of your recently visited ones. Click on the dropdown at the top of the page to see them all 🔍 :)

**Comment by choldgraf** [comment]
This is now done! Here are the relevant links:

[Node activity](https://grafana.mybinder.org/dashboard/db/node-activity?refresh=1m&orgId=1)
[Pod activity](https://grafana.mybinder.org/dashboard/db/pod-activity?orgId=1)
[Overview](https://grafana.mybinder.org/dashboard/db/1-overview?refresh=5m&orgId=1)
