### ISSUE TITLE
upgrading helm

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#542]
current helm is 2.8.2 (2.9.0 has a release candidate), but our deployment is using helm 2.7.0. Since helm doesn't have any sort of version management, compatibility, or installation support, this makes it complicated to switch versions. We need to be able to upgrade the version of helm in our clusters.

I *believe* we just need to add `helm init --upgrade` to our deploy steps to ensure that helm is the right version.

**Comment by betatim** [comment]
For what it is worth: I've been using helm 2.8.2 for a jupyterhub deployment on GCE for a while now and it works. I switched because it appeared to fix some issues around apparently failed deployments. However this deployment started from 2.8.2 so no upgrading was involved.
