### ISSUE TITLE
Visualize pod status by node

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/mybinder.org-deploy#552]
I suspect that lots of failures happen on a specific node, and it'd be valuable to visualize the pod status, or the binderhub status (fail/success) broken down by node. I think there are two ways to do this:

1. Figure out how to join two prometheus queries together.

    e.g., kube_pod_status_phase will give us the pods that are in state running/pending/failed/etc, BUT it 
    doesn't tell us which node the pods are on. However, kube_pod_info tells us which node the pod is on, 
    but doesn't tell us status information.

    If we could query each of these and then join them together on the pod name, we can
    get a plot of "pod status by node".
2. Add a `node` attribute to our binderhub launch metrics

   If we could add "node" to `binderhub_launch_time_seconds_count`, then we could also get a plot of binder success broken down by node.

anyone have thoughts on how to do that? I spent some time looking through prometheus docs but I can't figure out how to do `join(` operations.

cc @minrk @yuvipanda who maybe have experience with this.

**Comment by minrk** [comment]
I spent a bit of time fiddling with joins in the prometheus UI and came up with this query:

```prometheus
sum(
    kube_pod_status_phase{pod=~"jupyter-.*",phase!="Running"}
    * on (pod) group_left(node)
    kube_pod_info{pod=~"jupyter-.*"}
) by (node, phase)
```

which produces [this chart](https://grafana.mybinder.org/dashboard/db/1-overview?refresh=1m&panelId=29&fullscreen&orgId=1) of counts of pods not in the Running state per node (we can also include Running pods by removing the phase filter).

I'm not sure how informative it is, yet. I mostly see evidence of the Pending spikes caused when new nodes show up in the autoscaler.

**Comment by choldgraf** [comment]
I added it to the "nodes" dashboard - let's see if it seems useful in the
coming weeks and, if not, we can get rid of it. Thanks for taking the time
to figure out that query! I was having a hell of a time figuring out how to
use the group_left function :-P
--
