### ISSUE TITLE
Cannot bump JupyterHub chart due to networkpolicy error

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/mybinder.org-deploy#559]
This issue is trying to distill some trouble that @betatim, @willingc, and I ran into when trying to upgrade JupyterHub on the Binder deployment.

When bumping the JupyterHub chart, we ran into this error on deploy:

https://travis-ci.org/jupyterhub/mybinder.org-deploy/builds/367366526#L600

```
Error: UPGRADE FAILED: Deployment.apps "proxy" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"hub.jupyter.org/network-access-singleuser":"true", "name":"proxy", "release":"staging", "component":"proxy", "heritage":"Tiller", "hub.jupyter.org/network-access-hub":"true"}: `selector` does not match template `labels`
```

It seems that there's a bug in the chart somewhere, but we weren't able to spot it. We should figure this out.

Gitter chat about this begins ~ here: https://gitter.im/jupyterhub/binder?at=5ad60b78102fac7b7b202ddb

**Comment by choldgraf** [comment]
cc @yuvipanda @minrk @manics who have done some networkpolicy stuff lately

**Comment by betatim** [comment]
I think we have this problem: https://github.com/kubernetes/helm/issues/2494#issuecomment-311691146 namely we don't have a `.spec.selector.matchLabels` in `jupyterhub/templates/proxy/deployment.yaml`

**Comment by betatim** [comment]
I think the reason this fails on "upgrade" is that helm auto generates `.spec.selector.matchLabels` for us and is then confused when the now stored on the cluster bit doesn't match any more. Maybe the long term solution is to also specify this in the template? (after using what Min suggested in [gitter](https://gitter.im/jupyterhub/binder?at=5ad61cce5f188ccc1574db76) to get ourselves unstuck)

**Comment by minrk** [comment]
On a test deployment, I was able to do the upgrade if I deleted the proxy proxy deployment prior to upgrade:

    kubectl delete deployment proxy

From the Issue @betatim linked, we should note that changing labels will not appear to be allowed going forward, so we appear to have to delete and redeploy every time we want to change labels.

**Comment by betatim** [comment]
So the way forward for getting staging and prod back to being "deployable" we delete the proxy deployment by hand and then let travis deploy automatically? Or is it better to make a PR that modifies travis to first delete, then `helm upgrade...` and after that has been deployed make a new PR that changes it back to the default behaviour? Second option sounds more convoluted/more steps but probably minimises time where the proxy deployment is gone.

**Comment by minrk** [comment]
We can do the second one. I'll give it a go. The other perhaps simplest option, is to do this one deploy by hand locally, then push to Travis, which will be a no-op, since the version hasn't actually changed. But doing it all on Travis will leave a record, which is probably best.

**Comment by minrk** [comment]
https://github.com/jupyterhub/mybinder.org-deploy/pull/560 does option 2, deleting the proxy deploy on Travis.

**Comment by minrk** [comment]
This was fixed by #561 adding `--force` to deploy, which deletes and recreates objects if the `patch` operation fails. This is needed for the latest deploy because labels changed on the proxy deployment, and changing labels must always be done this way.

**Comment by choldgraf** [comment]
Nice! Is this something we'll need to do when we add labels in the future?
Should we add to the sre guide?

**Comment by minrk** [comment]
I think so. Since we've added `--force`, we should be okay for future label changes. This probably belongs in the z2jh docs, because upgrading from one release to another will need this flag.
