### ISSUE TITLE
Increase proxy read timeout to match culler

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/mybinder.org-deploy#572]
When I use [nbnovnc](https://github.com/ryanlovett/nvnovnc) on mybinder.org, the websockify websocket connection is closed after 60s which matches the default [proxy-read-timeout](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization). For mybinder.org, would it make sense to set the proxy-read-timeout to match the cull timeout? This way the websocket lasts as long as the notebook server.

**Comment by minrk** [comment]
We definitely can do that, but as network hops are added in different configurations, it's easy for this to crop up again in different deployment scenarios.

The Jupyter websocket handlers [use websocket pings](https://github.com/jupyter/notebook/blob/5.4.1/notebook/base/zmqhandlers.py#L173), which are a [websocket protocol feature](https://tools.ietf.org/html/rfc6455#section-5.5.2), for a keepalive to prevent exactly this sort of thing. Is that available to you?

**Comment by ryanlovett** [comment]
Yes, I do want to [setup pinging](https://github.com/ryanlovett/nbnovnc/issues/1#issuecomment-382475595), but I'm just being lazy. I'll give it a go so that the extension works in more places out of the box.

**Comment by ryanlovett** [comment]
@minrk I'm using Chrome developer tools to try to debug websocket traffic. I've a notebook behind an nginx proxy but I don't see WS ping frames in the devtools window on the channels socket. I do see regular notebook-related ws messages though. My kernel remains alive so I must be receiving pings. Do you know how can one observe ws pings coming in to the client?

**Comment by minrk** [comment]
Does chrome log pings? They don't show up at the user-level on the javascript side, as far as I know.

**Comment by ryanlovett** [comment]
Not from what I can tell! I had to believe my logging that the pings were actually happening.

I added a ping callback to nbserverproxy so that server-side pings will now keep the connection alive.
