### ISSUE TITLE
Set GitHub Auth token for binderhub

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#58]
Or we're limited to a 60 req/hour rate limit, which we will exhaust quickly. Each launch *and* build requires a request.

Temporarily, restarting the pod gets it a new IP and hence new limits. However, real way is to put a token in there.

**Comment by minrk** [comment]
I've got support for github auth in binderhub and tested it with minikube. Now I just need to figure out how to add the secrets to this repo for the deploy. It looks like I need the decrypted `deploy-secrets.tar.gz`, but as far as I can tell, only Travis and the original committer (@yuvipanda) have access to that, which means that only Yuvi can add secrets to the repo right now.

**Comment by minrk** [comment]
Deployed to beta
