### ISSUE TITLE
`status.mybinder.org` page

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/mybinder.org-deploy#626]
We often get questions from people like "I'm pretty sure Binder is down can you help with XXX". Oftentimes Binder is doing fine, and it's a problem with the configuration files etc in the repository.

One way to mitigate these issues is to have something like `status.mybinder.org`. It could basically reflect one or two of the graphs on our grafana dashboard. How do folks feel about:

1. Creating a status page on the binder docs (`docs.mybinder.org/status`) and then redirecting `status.mybinder.org` to this page as well)

**Comment by betatim** [comment]
should this point to https://mybinder.readthedocs.io/en/latest/reliability.html#site-metrics ?

**Comment by choldgraf** [comment]
it could, but site-metrics is generally over a much larger period of time. I'd think the "status" page would just go a few hours back in history

**Comment by betatim** [comment]
Sounds reasonable. Maybe we add a sentence/link from the status page to the site metrics which says "for long term trends check out site metrics" to make that distinction.

**Comment by choldgraf** [comment]
ok, I'll whip up a PR later today or this week

**Comment by choldgraf** [comment]
@betatim see https://github.com/jupyterhub/binder/pull/103
