### ISSUE TITLE
Bumping Prometheus and Grafana charts

### ISSUE THREAD

**Issue by willingc** [jupyterhub/mybinder.org-deploy#641]
It's been a couple of months since we bumped these. May help with the Prometheus/Grafana issues of memory usage and latency (or maybe not).

| chart           | stable chart version | mybinder | stable project version | mybinder |
|------------|---------------------|-----------|-----------------------|----------|
| prometheus | 6.7.2 | 6.2.1 | 2.2.1 (+ fixes) | 2.2.1 |
| grafana | 1.10.2 | 1.2.0 | 5.1.3 | 5.0.4 |

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/mybinder.org-deploy/blob/73ccdeab6279ea606e18ca6b47ae3bff523cbf55/mybinder/Chart.yaml#L27 this has been bumped up now.
