### ISSUE TITLE
Migrate to cert-manager from kube-lego

### ISSUE THREAD

**Issue by willingc** [jupyterhub/mybinder.org-deploy#642]
kube-lego is in maintenance mode with no ongoing development. It's replacement is cert-manager. I don't believe there is any urgency to do this as long as kube-lego is renewing the lets encrypt certs.

[Migration docs](https://cert-manager.readthedocs.io/en/latest/tutorials/acme/migrating-from-kube-lego.html) also has a table with comparisons (including multi-tenancy)

[Docs](https://cert-manager.readthedocs.io/en/latest/index.html)

**Comment by yuvipanda** [comment]
This has been done - see https://github.com/jupyterhub/mybinder.org-deploy/pull/1415 and linked issues.
