### ISSUE TITLE
Microsoft deep learning tutorial

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#653]
@fboylu stopped by the gitter chat just now asking if Microsoft could use mybinder.org for a large scale demo. [gitter message](https://gitter.im/jupyterhub/binder?at=5b3e4dbba99e1e52b71917c8)

> Hi everyone, I have a quick question. We are planning to use binder for a lab with 200 people and was wondering if it would be able to support that kind of load. I appreciate if you can help.
They will all click on the same binder repo link to start the notebooks.

The repo they want to run is https://github.com/fboylu/binder on 27th July 2018. They are not sure when during the day it will be but between 9am and 5pm PST that day. For about an hour, kind of a follow along.

I suggested that we should get together on a quiet day/moment for normal binder users and do some testing to see what the user experience is like if 200 people arrive at the same time. This means probably sometime at the weekend, Sunday morning-ish EU times??

What would be an appropriate favour to ask in return for us trying to get the resources together to support them in making this a good experience for everyone? Maybe some of their engineering team have time and interest to chip in?

**Comment by betatim** [comment]
Other questions I am thinking about:

* do we have the time to do the pre-work to make this a good experience?
* do we have enough resources to be around during the event to keep an eye on things?
* what kind of metrics and stats do we want to record while it is happening? (for me this is like getting slashdotted but with advance notice)

**Comment by willingc** [comment]
Hi @fboylu. Looks like an interesting demo.

I agree with @betatim that there should be some load testing done prior to the workshop. It would be great to get some support from Microsoft on the testing and monitoring. Microsoft folks like @nnja or others who work with Kubernetes and Python would be ideal to help with the testing.

**Comment by betatim** [comment]
There are some benchmarking results in #654

**Comment by yuvipanda** [comment]
Gonna close this as this workshop is done. @betatim do re-open / split off if you think there's things here we still need to address
