### ISSUE TITLE
max file size is 1MB

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#66]
Create a notebook with the cell:

```python
from IPython.display import publish_display_data
kB = 1024
publish_display_data({
    'application/x-fake-size-test': 'x' * 1024 * kB 
})
```

run that cell, and save will fail with HTTP 413 (too big!).

We have [this annotation](https://github.com/jupyterhub/mybinder.org-deploy/blob/614d6f59c1677c5a385552947226e3afa46a8f2e/config/common.yaml#L25), which I assume is meant to address exactly this, but it doesn't appear to have the desired effect.

**Comment by yuvipanda** [comment]
I've set it in the configmap (manually for now) and that seems to work - I can't repro this failing now.
