### ISSUE TITLE
Incorrect restartPolicy for singleuser pods

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#662]
The singleuser pods currently have a restartPolicy of "Always". This means when they exit (because they are idle) they will be restarted by k8s. You can see this by looking at the restart count of singleuser pods. It should be zero but there are many pods with a count >0.

It is a bit of a mystery why we end up with this restart policy as we explicitly set it [here](https://github.com/jupyterhub/mybinder.org-deploy/blob/765983115802556b5c5459d5530c6a467d7d312e/mybinder/values.yaml#L76) and the default  is [explicitly set](https://github.com/jupyterhub/kubespawner/blob/7ae99005409cb75684a0a1ec792dba4adcb4b4f2/kubespawner/objects.py#L160) in kubespawner.

My guess is that something in the k9s API client/python library we depend on has change?

**Comment by consideRatio** [comment]
Perhaps this is it... Switch to using extra_pod_config, the singleuser_ prefix is deprecated and will since recently be ignored if extra_pod_config without prefix is also set.


```
# from
c.KubeSpawner.singleuser_extra_pod_config.update({'restartPolicy': 'Never'})
# to
c.KubeSpawner.extra_pod_config.update({'restartPolicy': 'Never'})

**Comment by betatim** [comment]
That is what I did in #663, sorry for not linking this here. I think there is one more thing to follow up with kubespawner as I wrote in the PR. Will close this issue once that has happened.

**Comment by yuvipanda** [comment]
I think this is done. Thanks, @betatim!
