### ISSUE TITLE
Lower guaranteed memory for user pods

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#691]
We currently guarantee 1G of RAM to each pod. Most users never get anywhere close to that. As a way to save money we should reduce this to 512MB and see what happens.

https://github.com/jupyterhub/mybinder.org-deploy/blob/32655f123260d6f7a1e5aff2f02b94253e6473a1/config/prod.yaml#L33 is the line to edit.

When we do this we also need to switch the node type in the user pool. The way to do this is to add a new node pool with highmem8 node type. The reason for doing this is that we can only have a max of 110 pods per node. With the current settings we trigger a scale up at around 90 pods. This means lowering the memory requirement would only pack another 20 pods onto a node. Which would lead to even less occupation per node.

Todo:
* [x] add new node pool with highmem8 machines and a user label
* [x] lower memory requirement in the helm chart
* [x] check user pods are launching on the new pool
* [x] cordon machines in the old node pool
* [x] set upper limit of the old node pool to the size of the pool at the time of cordoning so that no new nodes are spawned

We decided against doing this today (Friday) as it will run close to the weekend. Maybe there is time during/before Jupytercon otherwise this is a task for the next deployment Tuesday.

**Comment by minrk** [comment]
For reference, of the 239 current users we have:

- 0 users over 1G
- 2 user over 800M
- 5 users over 512M
- 17 users over 256M
- 171 users under 100M

So a guarantee of 256MB ought to be pretty safe when only 10% of our users are above that and over 60% are below half that.

[this notebook](https://nbviewer.jupyter.org/gist/minrk/55116017ef202843de01906c18541471) illustrates some numbers based on resource usage of user pods, indicating that a guarantee of 512 (or even 256) on n1-highmem-8 should fit pretty comfortably.

**Comment by minrk** [comment]
Finished deploying new pool and removing old pool

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/background-for-jupyterhub-kubernetes-cost-calculations/5289/6
