### ISSUE TITLE
Shiny and R Example Errors

### ISSUE THREAD

**Issue by bentut** [jupyterhub/mybinder.org-deploy#731]
I am using the Shiny feature to render dashboards. The shiny link shown here was working for me about a week and a half ago, but it's not working now: https://github.com/binder-examples/r
http://beta.mybinder.org/v2/gh/binder-examples/r/master?urlpath=shiny/bus-dashboard/

Also, and possibly related: I cloned the binder-example/r repo on my own github and updated the binder badge to point at my new repo instead of the original one and the load is crapping out.
https://github.com/binder-examples/r (works)
https://github.com/bentut/bdac-grad (error- clone of above)

**Comment by betatim** [comment]
The build error (second part of the issue) is related to #732.

The dashboard link was working last Friday for a live demo I did. My guess is we broke something as part of a recent deploy.

I also noticed broken links for sphinx-gallery (https://github.com/sphinx-gallery/sphinx-gallery/issues/418) which I thought were a problem in jupyter lab URL handling. Might be related though.

Once your binder-examples/r instance is up and running you can access the dashboard by manually constructing the URL: https://hub.mybinder.org/user/YOURBINDERTHINGHERE/shiny/bus-dashboard/ the difference seems to be the trailing slash.

**Comment by minrk** [comment]
It's a regression in trailing-slash handling in jupyterhub/binderhub#660 deployed yesterday. jupyterhub/binderhub#668 should fix it
