### ISSUE TITLE
Redirect `matomo.mybinder.org` to https://mybinder.org/matomo/index.php

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/mybinder.org-deploy#747]
Title says it all - this is just to make it easier to remember the URL, since lots of other binder services follow the pattern `XXX.mybinder.org`

**Comment by yuvipanda** [comment]
@choldgraf can you make a DNS entry from matomo.mybinder.org that is a CNAME to mybinder.org?

**Comment by choldgraf** [comment]
You mean *just* mybinder.org right? If so, then done:

![image](https://user-images.githubusercontent.com/1839645/46625113-8b697300-cae7-11e8-9ef4-19fef8d2f24a.png)

**Comment by yuvipanda** [comment]
@choldgraf this works now!
