### ISSUE TITLE
Add status and playground redirects back [do on 17 Oct]

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#772]
On 17 October 2018 investigate adding status.mybinder.org and playground.mybinder.org back to our redirects and DNS.

Before adding status.mybinder.org back we need to check the DNS issues have been fixed, see #131 

This ties up a loose end from #766 and changes made to fix it.

**Comment by choldgraf** [comment]
I edited the issue title a bit so it says "do on oct 17th" instead of "due oct 17th". Maybe it's just me but I interpret "due" as meaning "complete before this time" :-)

**Comment by betatim** [comment]
I'll be (re)setting my ⏲ :)

The intention was indeed "look at this and decide what needs doing/can be done on Oct 17th".
