### ISSUE TITLE
Make matomo accounts for mybinder.org team members

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#782]
Matomo lets you have user accounts in it. Instead of using a single 'admin' account for everyone, we should instead have an account per user. This can be created by any 'admin' user.

I'm gonna create a bunch of accounts for people and make them superusers.

- [x] @choldgraf 
- [x] @jzf2101 
- [x] @minrk 
- [x] @betatim 
- [x] @willingc 

We can add more people if we wish.

Part of #725

**Comment by yuvipanda** [comment]
Created and emailed everyone!

**Comment by betatim** [comment]
When I try to login to matamo I see the following:

> Error: Form security failed. Please reload the form and check that your cookies are enabled. If you use a proxy server, you must configure Matomo to accept the proxy header that forwards the Host header. Also, check that your Referrer header is sent correctly.

When I first visit the page lastpass prefills it with a different account's details, I then replace those with my personal details, click login and get the above error.

If I use the login details that lastpass fills in and click login it works smoothly.

It sounds like a xsrf cookie/form problem? Any ideas on what to debug/look at?

**Comment by yuvipanda** [comment]
@betatim I ran into this too. Refreshing workee. I'm guessing the LastPass filled creds are admin creds. 

My suspicion is that since we run 3 replicas of matomo, it isn't sharing session data leading to xsrf out of sync problems. I'll look into it!

**Comment by yuvipanda** [comment]
@betatim see https://github.com/jupyterhub/mybinder.org-deploy/issues/784
