### ISSUE TITLE
Delete images from registry if they aren't using current prefix

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#800]
We spend about 500$ a month on our image storage. We have kept all images ever, and I suspect that if we delete images that don't match the current prefix, that cost will go down a lot.

**Comment by minrk** [comment]
Working on this. The gcloud API for managing images is *extremely* inefficient, but I think this can be automated.

**Comment by yuvipanda** [comment]
@minrk awesome! ty <3
