### ISSUE TITLE
GKE k8s 1.11 is GA - Upgrade nodes / master

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/mybinder.org-deploy#811]
Switch to the latest version of k8s! :D

**Comment by yuvipanda** [comment]
This *might* come with https://cloud.google.com/kubernetes-engine/docs/concepts/using-containerd as default (not sure). That has implications for our general inode issues and possibly image cleaner. Things to watch out for!

**Comment by yuvipanda** [comment]
We're at 1.18 or something now \o/
