### ISSUE TITLE
Remove trust from all notebooks

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#850]
Should we use an appendix (or different method) to "untrust" all notebooks in a repo?

There are a few repositories that have `jupyter trust` in their `postBuild` which means when you open a notebook JS in any of the output areas will be executed. We could use the appendix to make it a bit more difficult to deliver trusted notebooks to unsuspecting users.

**Comment by minrk** [comment]
We could do this, but trusted notebooks don't really make a difference on binder. The image can already be serving up arbitrary HTML, which is all a trusted notebook is in the end. There isn't really anything to protect users from on Binder, either, which is part of why users should never enter credentials on Binder, *especially* any credentials that might go in a cookie, which would be shared by other Binder sessions.

Binder can only really operate on the assumption that completely arbitrary code can execute in the image, and therefore completely arbitrary HTML and javascript can be served to the user.

**Comment by betatim** [comment]
That makes sense. Do you think it is simple enough to do and provides some benefits towards protecting people from accidentally malicious notebooks? Otherwise I'd close this.

**Comment by mathieuboudreau** [comment]
I've got a question that sounds related to this issue.

If possible, I would like to add `jupyter trust FILENAME.ipynb` in my Dockerfile, so that Plotly plots–which are outputted as javascript–display when notebooks are first loaded instead of having to re-execute the whole notebook. Is this allowed with the current security settings? I tried [here](), but received this error from MyBinder:

>jupyter trust content/01/mvp_sos.ipynb' returned a non-zero code: 1Error during build: 'Repo2Docker' object has no attribute 'debug'

**Comment by betatim** [comment]
(The error about the missing attribute is being tracked as https://github.com/jupyter/repo2docker/issues/563)

You should be able to run `jupyter trust ...` as an extra command in your `Dockerfile` by adding a line like `RUN jupyter trust ..` to it.

**Comment by mathieuboudreau** [comment]
Great, that works now! Thanks.
