### ISSUE TITLE
About page redirect issue (?)

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/mybinder.org-deploy#874]
There is redirect problem with the about page?

See: https://github.com/jupyterhub/mybinder.org-deploy/pull/873

**Comment by choldgraf** [comment]
not anymore :-)

the problem was that it was pointing to `docs.mybinder.org/about.html` which redirects to `mybinder.readthedocs.io/about.html`, but RTD actually needs it to be `mybinder.readthedocs.io/en/latest/about.html`...so this just makes the link go directly there
