### ISSUE TITLE
Cordoning node with ingress controller causes outage

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#885]
According to https://github.com/kubernetes/kubernetes/issues/65013, load-balancers exclude cordoned nodes from targets because a cordoned node is presumed to be cordoned as a precursor to removal, rather than a temporary condition. When we clean images, we cordon the cleaning node because new launches tend to fail while image cleaning is occurring due to very high disk load. Together, this means that image-cleaning on the node with the ingress-controller causes an outage as the load-balancer ignores the node with the ingress-controller as a valid routing target.

The quickest solution is to move the ingress controllers to the core nodes, which don't tend to get cordoned.

A second and probably better solution that's perhaps more appropriate is to use a different node taint that `kubectl cordon` to prevent user pods and builds from being assigned and use nodeSelectors/tolerances to accomplish this.

**Comment by minrk** [comment]
This should also be covered in the SRE for node pool upgrades, because we need to be careful to not leave cordoned nodes with the ingress controller pods during upgrade.

**Comment by betatim** [comment]
We could also add affinity rules to the controllers so they don't both end up on the same node.

**Comment by betatim** [comment]
Closing as we now have the controllers setup with pod anti affinity
