### ISSUE TITLE
The build log does not allow me to copy it

### ISSUE THREAD

**Issue by certik** [jupyterhub/mybinder.org-deploy#913]
I am trying to report a bug, but I can't copy the build log from https://mybinder.org. I am using Firefox 65.0.1 on Ubuntu 18.04. I can select the text, but Ctrl-C will not actually copy it.

**Comment by choldgraf** [comment]
hmmm - did you try right-clicking and selecting "copy"?

**Comment by betatim** [comment]
Could you reopen this issue on https://github.com/jupyterhub/binderhub which is the software that mybinder.org runs. Related issues there are https://github.com/jupyterhub/binderhub/issues/786 and https://github.com/jupyterhub/binderhub/issues/75
