### ISSUE TITLE
mybinder failed to start 

### ISSUE THREAD

**Issue by certik** [jupyterhub/mybinder.org-deploy#914]
Here is the link: https://mybinder.org/v2/gl/lfortran%2Fweb%2Flfortran-binder/b and here is the build log that it produced:
```
Waiting for build to start...
Failed to connect to event stream
```

I am new to binder, this is the first time I am trying to set it up for my project, so I don't know if this sometimes happens or if it is a bug.

P.S. I had to rewrite the log by hand in order to post it here, due to #913.

**Comment by certik** [comment]
This tweet seems relevant to this problem:

https://twitter.com/mybinderteam/status/1108399971437563904

**Comment by betatim** [comment]
I think this is because we emptied our docker image cache this morning and now the cluster is swamped with image building requests :-/ Sorry about that.

For the moment I'd recommend doing something else while we work through the backlog.

**Comment by certik** [comment]
@betatim thanks! I will do something else in the meantime and try in a few days again. I wasn't sure if I did something wrong, thanks for the clarification.

**Comment by betatim** [comment]
If you want to see if your repo would build (and debug/tune the build process) you can use http://repo2docker.readthedocs.io/ locally (if you have a working docker daemon). It is the tool we use on mybinder.org as well. I use it a lot for debugging as the turn around is much quicker.

I'll close this issue now. In general we recommend posting in http://discourse.jupyter.org/ for support kind of questions. This repo should be for technical issues around developing the service (like #913). You'll probably get faster help in the forum as well ;)

**Comment by certik** [comment]
@betatim ah cool. I implemented my own Docker solution (https://gitlab.com/lfortran/web/lfortran-binder/tree/ddc7a99e2bc066478cd6664efa62d70f54b9fe79/test_binder), trying to "emulate" Binder, and I run it on every merge request to ensure that things work. I'll port it to use `repo2docker`.

I'll post on discourse from now on, thanks for the tip!

**Comment by betatim** [comment]
Seems like your repo is building now.

The reason you were having a problem before with your build waiting to start was because there is a bug in BinderHub :) Only found it today due to the high load :-/.

**Comment by certik** [comment]
@betatim thanks for your help. Yes, indeed, it is building and working fine, I put the Binder badge into our README: https://gitlab.com/lfortran/lfortran. Works like a charm!
