### ISSUE TITLE
How are build pods scheduled?

### ISSUE THREAD

**Issue by betatim** [jupyterhub/mybinder.org-deploy#920]
(This is a thread for me to take notes, if you have questions/knowledge to please do pitch in.)

I've noticed that it feels like build pods tend to clump together to one node. This is annoying for the users on that node and the people waiting for their builds. We see load averages of over 20 regularly on a single node which I think is caused by build pods.

This issue is about figuring out how the pods are scheduled and then doing something about it so that they get spread over all nodes in the cluster.

**Comment by consideRatio** [comment]
@betatim relevant questions to answer to gain further insight I think could be:
- what kubernetes _taints_ does all nodes have?
- what kubernetes _tolerations_ does the build pods have?
- what nodeAffinity, podAffinity and podAntiAffinity does the build pods have?

**Comment by betatim** [comment]
Our user nodes have no taints, build pods have (nearly) no tolerations, and no (anti)affinity rules. They are scheduled by the default scheduler (`schedulerName: default-scheduler`).

Build pod tolerations:
```
Node-Selectors:  mybinder.org/pool-type=users
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
```

I remain stumped as to why they seem (very often) to get scheduled on the same node.

**Comment by consideRatio** [comment]
Well on the user nodes, normal users schedule to fit all at the most busy node, but if the build pods use the default scheduler as compared to the user scheduler, they will be positioned on the least busy user node like the default scheduler function. Perhaps this is why

**Comment by betatim** [comment]
Ah! Good point. I thought the default scheduler would spread pods "at random" amongst the available nodes and not on the least busy node.

Maybe we should add a custom scheduler for the build pods that uses a "random" strategy.

**Comment by choldgraf** [comment]
I believe that #834 cleared this up and @consideRatio helpfully answered the question as well, so I'm gonna close this one, but feel free to reopen if there's more to do!
