### ISSUE TITLE
Title of PR, and autopush PRs. 

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/mybinder.org-deploy#95]
It should be possible to automatize sending PRs to Staging with a bot / Travis-Ci; 

It would be also nice to standadise the commit message; I think that a `git log previous...current --oneline` may be better;

**Comment by yuvipanda** [comment]
This would be super awesome :) Do you have time to work on it, @Carreau?

**Comment by Carreau** [comment]
> This would be super awesome :) Do you have time to work on it, @Carreau?

Likely; but I'm training myself to separate week from week-end work. Also need to pack because need to move and visa stuff. 

Assigning myself.

**Comment by choldgraf** [comment]
ping on this again - this would be quite helpful to standardize the update process and relieve some human intervention thats currently needed

**Comment by yuvipanda** [comment]
Henchbot does this now!
