### ISSUE TITLE
Outbound SMTP email from Jupyter Notebook run on myBinder

### ISSUE THREAD

**Issue by Ophirg543** [jupyterhub/mybinder.org-deploy#977]
In mybinder, I am doing a Jupyter Notebook survey and I need the results of those who completed the survey. I set up auto-email on the Jupyter Notebook on my laptop, which would auto-send me the results of those who finished the survey. Now though, when I run this survey through mybinder, the server doesn't let me auto-email the results, saying "Network is unreachable". Is there a way to set up auto-email on mybinder?

**Comment by betatim** [comment]
Outgoing connections are blocked on almost all ports to reduce the attractiveness of mybinder.org as a source of abuse. The SMTP port will not be added to the list of exceptions.

Your best option is to find a HTTP service to send the emails for you, though note we recommend not putting credentials or anything you wouldn't put in a public tweet in your binder repository.
