### ISSUE TITLE
Send analytics events from ovh cluster to archive.analytics.mybinder.org

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#986]
The current pipeline for events is:

binderhub pods (on GKE) -> stackdriver -> google cloud storage -> analytics publisher 

From OVH, we can send the events to stackdriver directly, and nothing else would need to change!

The code for this is currently here: https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/values.yaml#L87

Steps to make this work on OVH:
1. Make a service account in binder-prod that has permissions to write to stackdriver
2. Make our binderhub pods use this service account explicitly, rather than use the implicit account we do now (all GKE pods can write to stackdriver by default. We block this for our singleuser pods)
3. Deploy this to OVH
4. PROFIT!

Pretty simple.

We should also add a 'origin' or 'instance' field to the event schema.

**Comment by betatim** [comment]
Sounds like a plan.

So the analytics publisher would remain disabled on the OVH instance?

When we turn this on we should take a look at the logs inn stackdriver to make sure everyone knows how to tell which lines are from the GKE cluster and which are from the OVH cluster. Or would we not see the standard stdout logs?

**Comment by yuvipanda** [comment]
@betatim we wouldn't see the standard stdout logs. we'll *only* send events through. we can send standard logs later separately if we want, but IMO that's lower priority.

And yes, analytics publisher would remain disabled. We should definitely implement an 'origin' field though.

**Comment by betatim** [comment]
Also needs an edit here https://github.com/jupyterhub/mybinder.org-deploy/blob/c3220437b9d94a697413baa8bace021be54e2c28/config/ovh.yaml#L10-L12 to remove the disabling.

**Comment by betatim** [comment]
Will you work on this @yuvipanda ?

**Comment by yuvipanda** [comment]
@betatim do you wanna take this on? I'm unfortunately running around multiple workshops in the next few days...

**Comment by betatim** [comment]
I can take a look, though I don't know how to do step (2) or what to look at to learn it. If you have a pointer to jump start the googling that would be helpful.

**Comment by yuvipanda** [comment]
We already do it for analytics-archiver.

1. Create a JSON key with appropriate permissions
2. https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/templates/analytics-publisher/secret.yaml puts it into a secret object
3. Mount it on the binderhub pod  (like https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/templates/analytics-publisher/deployment.yaml#L43)
4. Set an environment variable to tell the google logging library where to look for credentials: https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/templates/analytics-publisher/deployment.yaml#L39

This should work without any changes to the code.
